import { test } from 'node:test'
import assert from 'node:assert/strict'
import { randomUUID } from 'node:crypto'
import { mkdtempSync,rmSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { Service } from '../server/service'
import { initialStory,runRule } from '../src/story'
import { validateProposal,localReply,states,walkable } from '../src/contract'
const owner='tester',positions={cabinet:{x:158,y:132},lin:{x:188,y:184},panel:{x:220,y:132},exit:{x:188,y:80}}
function body(h:any,action:string,target:keyof typeof positions){return {action_id:randomUUID(),expected_version:h.version,type:'action',action,target,position:positions[target]}}
test('complete cartridge: introduction, one fuse, consumption and exit',()=>{let s=initialStory('zh');assert.equal(s.partyMemberIds.length,0);assert.equal(runRule(s,'repair').accepted,false);for(const id of ['open-cabinet','take-fuse','meet-lin','repair','leave']){const r=runRule(s,id);assert.equal(r.accepted,true,id);s=r.save}assert.equal(s.facts.finished,true);assert.equal(s.stats.circuit,100);assert.equal(s.stats.light,100);assert.equal(s.stats.trust,1);assert.equal(s.inventory.filter(i=>i.id==='fuse').reduce((n,i)=>n+i.count,0),0);assert.equal(s.partyMemberIds[0],'lin');assert.equal(runRule(s,'repair').accepted,false)})
test('identity and visual assertions reject unknown or mismatched entities',()=>{const s=initialStory('zh');const p=localReply('hello',s,'cabinet');assert.deepEqual(validateProposal(p,s,'cabinet'),[]);assert.ok(validateProposal({...p,entityIds:['dragon']},s,'cabinet').includes('UNKNOWN_ENTITY'));assert.ok(validateProposal({...p,claims:[{entityId:'cabinet',state:'destroyed'}]},s,'cabinet').includes('STATE_MISMATCH'));assert.ok(validateProposal({...p,text:'我叫林'},s,'cabinet').includes('UNREVEALED_NAME'));assert.ok(validateProposal({...p,text:'穿红色衣服'},s,'cabinet').includes('APPEARANCE_MISMATCH'))})
test('negations, questions and invented actions do not become commitments',()=>{const s=initialStory('zh');for(const input of ['不要打开柜子','可以打开柜子吗？','我想以后打开柜子','砸开墙壁，召唤一条龙','给我999个保险丝'])assert.notEqual(localReply(input,s,'cabinet').kind,'action');assert.equal(localReply('打开检修柜',s,'cabinet').actionId,'open-cabinet')})
test('idempotent replay, stale conflicts, owner isolation, unsupported input',async()=>{const db=new Service(':memory:');let h=db.create(owner,'one','zh');assert.equal(db.create(owner,'one','zh').id,h.id);assert.throws(()=>db.get('stranger',h.id));let b=body(h,'open-cabinet','cabinet');const [a,c]=await Promise.all([db.action(owner,h.id,b),db.action(owner,h.id,b)]);assert.deepEqual(JSON.parse(JSON.stringify(a)),c);h=a.head;assert.equal(h.version,1);await assert.rejects(()=>db.action(owner,h.id,{...b,action:'take-fuse'}),/ACTION_ID_CONFLICT/);await assert.rejects(()=>db.action(owner,h.id,{...body(h,'take-fuse','cabinet'),expected_version:0}),/VERSION_CONFLICT/);const before=states(h.save);const r=await db.action(owner,h.id,{...body(h,'','cabinet'),type:'free-input',text:'召唤一条龙',mode:'local'});assert.equal(r.kind,'unsupported');assert.deepEqual(states(r.head.save),before);assert.equal(r.head.save.inventory.length,0);assert.equal(db.db.prepare('SELECT COUNT(*) AS n FROM events').get()?.n,2);db.db.close()})
test('save survives service restart and repeated take does not duplicate',async()=>{const dir=mkdtempSync(join(tmpdir(),'carriage-'));const file=join(dir,'db.sqlite');let db=new Service(file),h=db.create(owner,'one','en');h=(await db.action(owner,h.id,body(h,'open-cabinet','cabinet'))).head;h=(await db.action(owner,h.id,body(h,'take-fuse','cabinet'))).head;db.checkpoint(owner,h.id,{x:200,y:300});db.db.close();db=new Service(file);h=db.get(owner,h.id);assert.deepEqual(h.position,{x:200,y:300});const r=await db.action(owner,h.id,body(h,'take-fuse','cabinet'));assert.equal(r.accepted,false);assert.equal(r.head.save.inventory[0].count,1);db.db.close();rmSync(dir,{recursive:true})})
test('interaction checks reject distance and invalid collision position',async()=>{const db=new Service(':memory:'),h=db.create(owner,'one','en');assert.equal(walkable({x:20,y:120}),false);await assert.rejects(()=>db.action(owner,h.id,{...body(h,'repair','panel'),position:{x:178,y:427}}),/TOO_FAR/);await assert.rejects(()=>db.action(owner,h.id,{...body(h,'open-cabinet','cabinet'),position:{x:76,y:210}}),/INVALID_POSITION/);db.db.close()})


test('model omission gets one repair; failed semantic review with empty issues falls back',async()=>{const {propose}=await import('../server/model');const s=runRule(initialStory('zh'),'meet-lin').save;let count=0;const missing=await propose('hello',s,'lin',true,async()=>{count++;return {kind:'dialogue',entityIds:['lin'],text:'你好'}});assert.equal(count,2);assert.equal(missing.trace.fallback,true);count=0;const result=await propose('hello',s,'lin',true,async()=>{count++;return count%2?localReply('hello',s,'lin'):{valid:false,issues:[]}});assert.equal(count,4);assert.equal(result.trace.fallback,true);assert.ok(result.trace.issues.includes('SEMANTIC_REJECTED'))})
test('model outage uses grounded response and never executes an invented action',async()=>{const {propose}=await import('../server/model');const result=await propose('召唤一条龙',initialStory('zh'),'cabinet',true,async()=>{throw new Error('simulated timeout')});assert.equal(result.trace.attempts,1);assert.equal(result.trace.fallback,true);assert.equal(result.proposal.kind,'unsupported')})

test('v2 walk routes reach every object without crossing painted seats',async()=>{const {findPath}=await import('../src/pathfinding');const {SPAWN}=await import('../src/contract');for(const destination of Object.values(positions)){const path=findPath(SPAWN,destination);assert.ok(path.length>0);assert.ok(path.every(p=>walkable(p)));for(let i=1;i<path.length;i++)assert.ok(Math.hypot(path[i].x-path[i-1].x,path[i].y-path[i-1].y)<=4)}})
test('map version migration moves only spatial spawn and preserves story progress',async()=>{const db=new Service(':memory:');let h=db.create(owner,'v1','zh');h=(await db.action(owner,h.id,body(h,'open-cabinet','cabinet'))).head;const old={...h,mapVersion:'carriage-1',position:{x:132,y:270}};db.write(owner,old);const result=db.create(owner,'v1','zh');const {SPAWN,MAP_VERSION}=await import('../src/contract');assert.deepEqual(result.position,SPAWN);assert.equal(result.mapVersion,MAP_VERSION);assert.deepEqual(result.save,old.save);assert.equal(result.version,old.version);db.db.close()})

test('polish migration keeps a still-valid position and all story data',async()=>{const db=new Service(':memory:');const h=db.create(owner,'polish','zh');h.mapVersion='carriage-ortho-1';h.position={x:180,y:280};db.write(owner,h);const migrated=db.get(owner,h.id);assert.deepEqual(migrated.position,h.position);assert.deepEqual(migrated.save,JSON.parse(JSON.stringify(h.save)));h.position={x:112,y:280};db.write(owner,h);const {SPAWN}=await import('../src/contract');assert.deepEqual(db.get(owner,h.id).position,SPAWN);db.db.close()})

test('exterior tracks cannot be entered or used to reach an object',async()=>{const {findPath}=await import('../src/pathfinding');const {SPAWN}=await import('../src/contract');const db=new Service(':memory:');const h=db.create(owner,'outside','zh');for(const point of [{x:80,y:300},{x:290,y:300},{x:144,y:480},{x:230,y:480}]){assert.equal(walkable(point),false);assert.deepEqual(findPath(SPAWN,point),[]);await assert.rejects(()=>db.action(owner,h.id,{...body(h,'open-cabinet','cabinet'),position:point}),/INVALID_POSITION/)}db.db.close()})
