import {originalReleasedPresentation} from '../server/original-presentation'
import test from 'node:test'
import assert from 'node:assert/strict'
import {DatabaseSync} from 'node:sqlite'
import {randomUUID} from 'node:crypto'
import {OriginalTrainAuthority,originalTrainRuntime} from '../server/original-train-runtime'
import {originalGameEntities} from '../src/original-game-projection'
import {originalBoundWorldPlan} from '../src/original-world-plan'
import {retainOriginalCompanions} from '../src/original-companion-context'
import type {AuthorityStorage} from '../server/session-authority'
const owner='synthetic-companion-owner'
function setup(){const raw=new DatabaseSync(':memory:'),db:AuthorityStorage={all:(q,...b)=>raw.prepare(q).all(...b) as any,run:(q,...b)=>{raw.prepare(q).run(...b)},transaction:work=>{raw.exec('BEGIN');try{const r=work();raw.exec('COMMIT');return r}catch(e){raw.exec('ROLLBACK');throw e}}};const authority=new OriginalTrainAuthority(db,originalReleasedPresentation),h=authority.create(owner,randomUUID(),'zh');h.save.partyMemberIds=['ada-mechanic'];h.save.characters.find(c=>c.id==='ada-mechanic')!.status='companion';raw.prepare('UPDATE journeys SET data=? WHERE id=?').run(JSON.stringify(h),h.id);return {raw,db,authority,h}}
test('checkpoint restores companion positions together with the hero and rejects stale or foreign writes',()=>{const {raw,db,authority,h}=setup();try{const poses={'ada-mechanic':{x:220,y:430}},body={sceneId:h.sceneId,expected_version:h.version,position:{x:220,y:458},companionPositions:poses};authority.checkpoint(owner,h.id,body);const restored=new OriginalTrainAuthority(db,originalReleasedPresentation).get(owner,h.id);assert.deepEqual(restored.companionPositions,poses);assert.deepEqual(restored.position,body.position);assert.deepEqual(restored.save,h.save);assert.equal(restored.version,h.version);assert.throws(()=>authority.checkpoint(owner,h.id,{...body,expected_version:99}),/STALE_POSITION/);assert.throws(()=>authority.checkpoint('another-owner',h.id,body),/SESSION_NOT_FOUND/);assert.throws(()=>authority.checkpoint(owner,h.id,{...body,companionPositions:{'ren-medic':poses['ada-mechanic']}}),/COMPANION_NOT_FOLLOWING/);assert.deepEqual(authority.get(owner,h.id),restored)}finally{raw.close()}})
test('dialogue accepts the moved companion location and UI projects that same position',async()=>{const {raw,authority,h}=setup();try{const poses={'ada-mechanic':{x:220,y:430}},world=originalBoundWorldPlan(h.assets),actor=world.characters.find(c=>c.id==='ada-mechanic')!,target=actor.entities.find(id=>world.entities.some(e=>e.id===id&&e.scene===h.sceneId))!;const request={action_id:randomUUID(),expected_version:h.version,sceneId:h.sceneId,position:{x:220,y:458},companionPositions:poses,target,type:'dialogue',text:'你好'};const reply=await authority.action(owner,h.id,request);assert.deepEqual(reply.head.companionPositions,poses);assert.deepEqual(originalGameEntities(reply.head).find(e=>e.id===target)!.position,{x:224.5,y:445});assert.deepEqual(await authority.action(owner,h.id,request),reply);await assert.rejects(authority.action(owner,h.id,{...request,action_id:randomUUID(),expected_version:reply.head.version,position:{x:92,y:300}}),/TOO_FAR|INVALID_POSITION/)}finally{raw.close()}})
test('scene transitions clear formation and leaving party removes only departing member',()=>{const runtime=originalTrainRuntime(()=>true),h=runtime.initial('zh',randomUUID());h.save.partyMemberIds=['ada-mechanic'];h.companionPositions={'ada-mechanic':{x:220,y:430}};assert.equal(retainOriginalCompanions({...h,sceneId:'train-at-tunnel'},h).companionPositions,undefined);const next={...h,save:{...h.save,partyMemberIds:[]}};assert.deepEqual(retainOriginalCompanions(next,h).companionPositions,{});assert.deepEqual(h.companionPositions,{'ada-mechanic':{x:220,y:430}})})
