import {test} from 'node:test'
import assert from 'node:assert/strict'
import {randomUUID} from 'node:crypto'
import {Service,type Head} from '../server/service'
import {currentScene,sceneEntities,entities,walkable,sceneContract,validateProposal,MAP_VERSION,type EntityId} from '../src/contract'
import {approachPoints,scenes,sceneIds,portalArrivals} from '../src/scene-layout'
import {findPath} from '../src/pathfinding'
const owner='scene-tester'
function intent(h:Head,target:EntityId,action:string){return {action_id:randomUUID(),expected_version:h.version,sceneId:currentScene(h.save),position:approachPoints[target],type:'action',target,action}}
async function repaired(db:Service){let h=db.create(owner,randomUUID(),'zh');for(const [id,action] of [['cabinet','open-cabinet'],['cabinet','take-fuse'],['lin','meet-lin'],['panel','repair']] as const)h=(await db.action(owner,h.id,intent(h,id,action))).head;return h}
test('all scenes have traversable portals and reachable interactions at the same actor size',()=>{for(const id of sceneIds){for(const target of sceneEntities(id)){const path=findPath(scenes[id].spawn,approachPoints[target],id);assert.ok(path.length,`${id}/${target}`);assert.ok(path.every(p=>walkable(p,id)));assert.ok(walkable(approachPoints[target],id))}for(const object of [...scenes[id].furniture,...scenes[id].fixtures])assert.equal(walkable({x:object.x,y:object.y},id),false)}for(const arrival of Object.values(portalArrivals))assert.ok(walkable(arrival.position,arrival.scene))})
test('three scenes complete, both connections return, and consumed items do not return',async()=>{const db=new Service(':memory:');let h=await repaired(db);const act=async(target:EntityId,action:string)=>{const r=await db.action(owner,h.id,intent(h,target,action));h=r.head;return r};await act('exit','leave');assert.equal(currentScene(h.save),'baggage');assert.equal((await act('supply','take-battery')).accepted,false);await act('supply','open-supply');await act('supply','take-battery');assert.equal((await act('supply','take-battery')).accepted,false);await act('forward','enter-cab');await act('radio','install-battery');assert.equal((await act('radio','send-signal')).accepted,false);await act('cabBack','back-baggage');await act('record','read-record');await act('back','back-carriage');assert.equal(h.save.facts.repaired,true);assert.equal(h.save.facts.fuse_taken,true);await act('exit','go-baggage');await act('forward','enter-cab');assert.equal((await act('radio','install-battery')).accepted,false);await act('radio','route-radio');await act('radio','call-yard');assert.equal(h.save.facts.rescue_sent,false);await act('radio','send-signal');assert.equal(h.save.facts.rescue_sent,true);assert.equal((await act('radio','send-signal')).accepted,false);assert.equal(h.save.inventory.filter(i=>i.id==='battery'||i.id==='fuse').reduce((n,i)=>n+i.count,0),0);assert.equal(h.save.map.filter(m=>m.visited).length,3);assert.equal(currentScene(db.get(owner,h.id).save),'cab');db.db.close()})
test('lost transition response replays once and stale positional checkpoint cannot move the new scene',async()=>{const db=new Service(':memory:');let h=await repaired(db);const oldVersion=h.version;const body=intent(h,'exit','leave');const first=await db.action(owner,h.id,body);const replay=await db.action(owner,h.id,body);assert.deepEqual(JSON.parse(JSON.stringify(first)),replay);h=first.head;assert.equal(currentScene(h.save),'baggage');assert.throws(()=>db.checkpoint(owner,h.id,{x:188,y:80},'carriage',oldVersion),/STALE_POSITION/);assert.deepEqual(db.get(owner,h.id).position,h.position);db.db.close()})
test('remote scene actions, claims, and undiscovered locations are outside the current model contract',async()=>{const db=new Service(':memory:');const h=db.create(owner,randomUUID(),'en');await assert.rejects(()=>db.action(owner,h.id,{...intent(h,'supply','open-supply'),sceneId:'baggage'}),/OFF_SCENE_ENTITY/);const context=sceneContract(h.save,'cabinet');assert.equal(context.entities.some(e=>e.id==='radio'),false);const issues=validateProposal({kind:'dialogue',entityIds:['radio'],claims:[{entityId:'radio',state:'unpowered'}],text:'The radio waits.'},h.save,'cabinet');assert.ok(issues.includes('OFF_SCENE_ENTITY'));db.db.close()})
test('legacy completed carriage upgrades without resetting story or unlocking rescue',async()=>{const db=new Service(':memory:');const h=await repaired(db);h.mapVersion='carriage-narrow-1';h.save.facts.finished=true;h.save.map=h.save.map.filter(m=>m.id==='carriage');delete h.save.facts.rescue_sent;const version=h.version,blocks=structuredClone(h.save.blocks);db.write(owner,h);const migrated=db.get(owner,h.id);assert.equal(migrated.mapVersion,MAP_VERSION);assert.equal(currentScene(migrated.save),'carriage');assert.equal(migrated.save.map.length,4);assert.equal(migrated.save.facts.finished,true);assert.equal(migrated.save.facts.rescue_sent,false);assert.match(migrated.save.objective,/行李车/);assert.equal(migrated.version,version);assert.deepEqual(migrated.save.blocks,blocks);assert.equal((await db.action(owner,h.id,intent(migrated,'exit','go-baggage'))).accepted,true);db.db.close()})
