import test from 'node:test'
import assert from 'node:assert/strict'
import {inspectActorMapCandidate,ACTOR_PREVIEW_HEIGHT} from '../src/sprite-map-candidate'
import {inspectSpritePng,newSpriteSource,type SpriteDraft} from '../src/sprite-draft'
import {prepareSpritePixels} from '../src/sprite-preparation'
async function fixture(){const bytes=new Uint8Array(45);bytes.set([137,80,78,71,13,10,26,10]);const view=new DataView(bytes.buffer);view.setUint32(8,13);bytes.set([73,72,68,82],12);view.setUint32(16,72);view.setUint32(20,96);const png=await inspectSpritePng(bytes),rgba=new Uint8ClampedArray(72*96*4).fill(255);for(let y=0;y<96;y++)for(let x=0;x<72;x++)if(x%24>=7&&x%24<17&&y%24>=4&&y%24<20)rgba.set([30,70,100,255],(y*72+x)*4);const spec={columns:3,rows:4,cellWidth:24,cellHeight:24,foot:{x:12,y:20},kind:'actor' as const,backgroundMode:'pale-neutral' as const,neutralMin:200,chromaMax:20},prepared=prepareSpritePixels({width:72,height:96,rgba},spec);const draft:SpriteDraft={...newSpriteSource(png,'synthetic'),state:'candidate',spec,result:{png,frames:prepared.frames,metrics:prepared.metrics,algorithm:prepared.algorithm}};return {draft,pixels:prepared.raster}}
test('saved candidate maps all four rows and foot anchors with one fixed world scale',async()=>{const {draft,pixels}=await fixture();const result=await inspectActorMapCandidate(draft,draft.id,async()=>pixels);assert.equal(result.scale,ACTOR_PREVIEW_HEIGHT/16);assert.equal(result.frameBounds.length,12);assert.deepEqual(result.baselines,Array.from({length:4},()=>[20,20,20]));assert.deepEqual(result.centers,Array.from({length:4},()=>[12,12,12]));assert.equal(result.png.sha256,draft.result!.png.sha256)})
test('missing/wrong identity, equipment, failed state and broken frame metadata are refused',async()=>{const {draft,pixels}=await fixture();const reject=(d:SpriteDraft,id=d.id)=>assert.rejects(inspectActorMapCandidate(d,id,async()=>pixels));await reject(draft,'different');await reject({...draft,state:'failed'});await reject({...draft,spec:{...draft.spec!,kind:'states'}});const missing=structuredClone(draft);missing.result!.frames.pop();await reject(missing);const shifted=structuredClone(draft);shifted.result!.frames[1].offset.y++;await reject(shifted);const wrongRow=structuredClone(draft);wrongRow.result!.frames[3].row=3;await reject(wrongRow)})
test('opaque fake alpha, a clipped edge and empty direction cannot enter map preview',async()=>{const {draft,pixels}=await fixture();const opaque=structuredClone(pixels);for(let i=3;i<opaque.rgba.length;i+=4)opaque.rgba[i]=255;await assert.rejects(inspectActorMapCandidate(draft,draft.id,async()=>opaque));const clipped=structuredClone(pixels);clipped.rgba[(6*72)*4+3]=255;await assert.rejects(inspectActorMapCandidate(draft,draft.id,async()=>clipped));const empty=structuredClone(pixels);for(let y=72;y<96;y++)empty.rgba.fill(0,y*72*4,(y+1)*72*4);await assert.rejects(inspectActorMapCandidate(draft,draft.id,async()=>empty))})
test('source/result integrity and native pixel dimensions are checked before registration',async()=>{const {draft,pixels}=await fixture(),broken=structuredClone(draft);broken.result!.png.sha256='0'.repeat(64);await assert.rejects(inspectActorMapCandidate(broken,broken.id,async()=>pixels),/SPRITE_CORRUPT/);await assert.rejects(inspectActorMapCandidate(draft,draft.id,async()=>({...pixels,width:73})));const feet=structuredClone(pixels);for(let y=18;y<20;y++)for(let x=0;x<24;x++)feet.rgba[((y+72)*72+x)*4+3]=0;for(let x=0;x<24;x++)feet.rgba[(89*72+x)*4+3]=0;await assert.rejects(inspectActorMapCandidate(draft,draft.id,async()=>feet))})
