import {writeFileSync,readFileSync} from 'node:fs'
import {createHash} from 'node:crypto'
import {scenes,sceneIds,sceneObstacles,approachPoints,portalArrivals,seatSource} from '../src/scene-layout'
import {extraArt,actorArt,propsArt,artDirection,assetPath} from '../src/art-catalog'
import {visualStates} from '../src/visual-states'
import {entities,sceneEntities,actionTarget} from '../src/contract'
const crop=([x,y,w,h]:number[])=>({x,y,w,h})
const assets=[...sceneIds.map(id=>({id,path:assetPath(scenes[id].background)})),{id:'equipment',path:assetPath(extraArt.path),imageWidth:extraArt.width,imageHeight:extraArt.height,crops:Object.values(extraArt.crops).map(crop)},...Object.entries(actorArt.balanced).map(([id,a])=>({id,path:assetPath(a.path),imageWidth:a.width,imageHeight:a.height,requiresAlpha:true,crops:Array.from({length:a.rows},(_,r)=>Array.from({length:a.columns},(_,c)=>({x:c*a.width/a.columns,y:r*a.height/a.rows,w:a.width/a.columns,h:a.height/a.rows}))).flat()})),{id:'props',path:assetPath(propsArt.balanced.path),imageWidth:propsArt.balanced.width,imageHeight:propsArt.balanced.height,requiresAlpha:true,crops:Object.values(propsArt.balanced.crops).map(crop)},{id:'seat',path:'public/art/seat.png',imageWidth:seatSource.imageWidth,imageHeight:seatSource.imageHeight,requiresAlpha:true,crops:[{x:seatSource.x,y:seatSource.y,w:seatSource.w,h:seatSource.h}]}].map(a=>({...a,sha256:createHash('sha256').update(readFileSync(a.path)).digest('hex')}))
const manifest={version:1,artDirection,world:{width:384,height:576,step:4},actor:{width:9,height:15},assets,scenes:sceneIds.map(id=>({id,background:id,walkRegion:scenes[id].interior,spawn:scenes[id].spawn,obstacles:sceneObstacles(id),targets:sceneEntities(id).map(target=>({id:target,approach:approachPoints[target],states:entities[target].states,renderedStates:Object.keys(visualStates[target])}))})),portals:Object.entries(portalArrivals).map(([id,p])=>({id,from:entities[actionTarget[id]].scene,to:p.scene,arrival:p.position}))};writeFileSync('doc/world-manifest.json',JSON.stringify(manifest,null,2)+'\n')
writeFileSync('doc/art-production-manifest.json',JSON.stringify({version:1,artDirection,assets,actors:actorArt.balanced,props:propsArt.balanced,extraEquipment:extraArt,sceneContractSource:'src/scene-layout.ts',replacementPolicy:'candidate → mechanical checks → same-scene visual/motion review → admitted; retain current runtime on rejection'},null,2)+'\n')
console.log(`Exported actual runtime inventory: ${assets.length} assets, ${sceneIds.length} scenes; ${artDirection.id}`)
