import React,{useEffect,useRef,useState} from 'react'
import {BrowserArtDrafts,artDraftDatabaseName,draftSessionId,planArtDraft,runArtDraft,createArtProducer,decodeArtCandidate,inspectArtCandidate,ART_DRAFT_VERSION,type ArtDraft,type ArtLighting} from './art-draft'
import exampleRequest from '../doc/platform-art-candidates/20260911/environment-edit-01/request.json'
import exampleState from '../doc/platform-art-candidates/20260911/environment-edit-01/state.json'
import './art-creator.css'
export default function ArtCreator(){
 const repo=useRef<BrowserArtDrafts|null>(null),alive=useRef(true),[draft,setDraft]=useState<ArtDraft>(),[lighting,setLighting]=useState<ArtLighting>('cool'),[busy,setBusy]=useState(false),[loaded,setLoaded]=useState(false),[error,setError]=useState(''),[image,setImage]=useState(''),[clock,setClock]=useState(Date.now())
 const zh=navigator.language.startsWith('zh'),t=(a:string,b:string)=>zh?a:b
 useEffect(()=>{alive.current=true;repo.current=new BrowserArtDrafts(artDraftDatabaseName(location.href));void repo.current.get().then(d=>{if(alive.current){setDraft(d);if(d)setLighting(d.lighting);setLoaded(true)}}).catch(()=>setError(t('草稿无法读取，先恢复浏览器存储再重试。','Draft storage could not be read. Restore browser storage and retry.')));const tick=setInterval(()=>setClock(Date.now()),1000);return()=>{alive.current=false;clearInterval(tick);void repo.current?.close()}},[])
 useEffect(()=>{let url='',cancelled=false;setImage('');if(draft?.candidate)void decodeArtCandidate(draft.candidate).then(u=>{url=u;if(cancelled)URL.revokeObjectURL(u);else setImage(u)}).catch(()=>setError(t('候选图片无法解码，暂不能试走。','The candidate cannot be decoded. Map preview is unavailable.')));return()=>{cancelled=true;if(url)URL.revokeObjectURL(url)}},[draft?.candidate?.sha256])
 async function loadSample(){if(busy||!loaded)return;setBusy(true);setError('');try{if(!navigator.locks)throw Error('NO_LOCKS');await navigator.locks.request(artDraftDatabaseName(location.href),{ifAvailable:true},async lock=>{if(!lock)throw Error('OTHER_TAB');const current=await repo.current!.get();if(current&&(['prepared','generating'].includes(current.state)||(current.state==='failed'&&current.retryable)))throw Error('PENDING');const response=await fetch('./art/platform-north-cape-candidate.png',{credentials:'omit'});if(!response.ok)throw Error('ART_DOWNLOAD');const candidate=await inspectArtCandidate(new Uint8Array(await response.arrayBuffer()));if(candidate.sha256!==exampleState.asset.sha256)throw Error('ART_INVALID');const url=await decodeArtCandidate(candidate);URL.revokeObjectURL(url);const imported:ArtDraft={version:ART_DRAFT_VERSION,id:exampleRequest.requestId,lighting:'cool',source:'library',request:{...exampleRequest,mode:'edit'},taskId:exampleState.task.task_id,candidate,state:'candidate',retryable:false,nextAt:0};await repo.current!.put(imported);setDraft(imported);setLighting(imported.lighting)})}catch{setError(t('样本尚未准备好，请稍后重试。','The sample is not ready. Please retry.'))}finally{setBusy(false)}}
 async function generate(fresh:boolean){if(busy||!loaded)return;setBusy(true);setError('')
  try{if(!navigator.locks)throw Error('NO_LOCKS');await navigator.locks.request(artDraftDatabaseName(location.href),{ifAvailable:true},async lock=>{
   if(!lock)throw Error('OTHER_TAB')
   const store=repo.current!,current=await store.get()
   if(fresh){if(current?.error==='ORIGIN_NOT_ALLOWED')throw Error('ORIGIN_NOT_ALLOWED');if(current&&(['prepared','generating'].includes(current.state)||(current.state==='failed'&&current.retryable)))throw Error('PENDING');if(current&&current.nextAt>Date.now())throw Error('COOLDOWN');const next=planArtDraft(lighting,draftSessionId(location.href));await store.put(next);setDraft(next)}
   await runArtDraft(store,createArtProducer(),d=>{if(alive.current)setDraft(d)})
  })}catch(e){const code=e instanceof Error?e.message:'';setError(code==='OTHER_TAB'?t('另一窗口正在处理，请稍后返回。','Another tab is processing this draft. Return shortly.'):t('未能完成操作，已保存的任务会保留。刷新后继续。','The operation could not complete. Saved tasks are retained. Reload to continue.'))}finally{if(alive.current){setBusy(false);try{setDraft(await repo.current!.get())}catch{}}}
 }
 const pending=draft&&(['prepared','generating'].includes(draft.state)||(draft.state==='failed'&&draft.retryable)),cooldown=Math.max(0,Math.ceil(((draft?.nextAt??0)-clock)/1000))
 const originBlocked=draft?.error==='ORIGIN_NOT_ALLOWED'
 const status=busy?t('正在生成并检查图片…','Generating and checking the image…'):draft?.state==='candidate'?t('候选已保存 · 等待质量验收','Candidate saved · Quality review pending'):draft?.state==='failed'?t('这次任务尚未得到可用候选','This task has no usable candidate yet'):pending?t('有一项未完成任务，可以继续','An unfinished task can be resumed'):t('选择光照，制作一个背景变体','Choose lighting to create a background variation')
 return <main className="cl-creator"><header><p>{t('北岬站 · 场景制作','North Cape · Scene creation')}</p><h1>{t('制作背景变体','Create a background variation')}</h1><p>{t('保持已选俯视角度和布局，先生成，再到地图里试走。','Keep the selected overhead view and layout. Generate, then try it in the map.')}</p></header><section aria-label={t('制作设置','Creation settings')}><label htmlFor="art-lighting">{t('光照','Lighting')}</label><select id="art-lighting" value={lighting} disabled={busy||Boolean(pending)} onChange={e=>setLighting(e.target.value as ArtLighting)}><option value="cool">{t('清晨冷光 · 保持地面明亮','Cool dawn · Keep the ground readable')}</option><option value="warm">{t('暖灯倒影 · 保持地面明亮','Warm lamps · Keep the ground readable')}</option></select><button className="cl-primary" disabled={!loaded||busy||cooldown>0||originBlocked} onClick={()=>void generate(!pending)}>{pending?t('继续原任务','Resume task'):draft?t('生成另一个候选','Generate another candidate'):t('生成背景候选','Generate background candidate')}</button>{cooldown>0&&<p>{t('稍后可继续：','Available in ')}{cooldown}s</p>}<p role="status">{status}</p>{draft?.error&&<p>{originBlocked?t('当前网页来源未获媒体服务允许。需要在受支持的部署来源下继续；重新生成不会解决。','This page origin is not allowed by the media service. Continue from a supported deployment; regenerating will not fix it.'):t('任务原因：','Task result: ')+draft.error}</p>}{error&&<p role="alert">{error}</p>}<button disabled={!loaded||busy||Boolean(pending)} onClick={()=>void loadSample()}>{t('使用已生成的平台样本','Use the existing platform sample')}</button></section>{draft?.source==='library'&&<p>{t('当前为先前已生成的真实平台样本，本次没有调用生成服务。','This is an existing platform-generated sample. Loading it made no generation request.')}</p>}{image&&<section aria-label={t('背景候选','Background candidate')}><img src={image} alt={t('平台生成的北岬站背景候选','Platform-generated North Cape background candidate')} draggable={false}/><p>{t('生成成功不代表视角、比例和细节已达标；先试走检查。','Generation success does not establish correct perspective, proportions or detail. Inspect it in the map first.')}</p><a className="cl-creator__action" href={`./creator.html?scene_preview=north-cape&art_source=draft&draft=${encodeURIComponent(draft!.id)}`}>{t('在地图中试走','Try in the map')}</a></section>}{draft&&<details><summary>{t('制作记录','Creation record')}</summary><dl><dt>{t('请求','Request')}</dt><dd>{draft.id}</dd><dt>{t('任务','Task')}</dt><dd>{draft.taskId||t('等待服务确认','Awaiting service acknowledgement')}</dd>{draft.candidate&&<><dt>SHA-256</dt><dd>{draft.candidate.sha256}</dd></>}</dl></details>}<footer><a href="./creator.html?create_art=sprite">{t('准备人物与设备素材','Prepare character and equipment art')}</a><a href="./creator.html?scene_preview=north-cape">{t('返回基准地图','Back to baseline map')}</a><p>{t('草稿保存在当前浏览器。当前入口用于制作验证，尚未开放发布；不会改变正式游戏与已有旅程。','Drafts are saved in this browser. This creation preview cannot publish yet and does not change the live game or existing journeys.')}</p></footer></main>
}
