import type {GenerateImageMediaRequest} from './vendor/media/client'
/** v1 keeps projection/ownership fixed; business identity may vary without moving architecture. */
export const DOOR_LEAF_RECIPE='detached-shop-leaf-v2'
export const DOOR_LEAF_REFERENCE='https://images.aiwaves.tech/uploads/1789671719104-khcthvxndm.png'
export const DOOR_LEAF_ACCEPTANCE={canvas:{width:512,height:768},background:'magenta',postprocess:['matte-removal','automatic-alpha-bounds-and-anchor'],forbidden:['fixed jambs','lintel','sill','surrounding wall','second leaf','converging edges','oversized category emblem'],failure:'retain current admitted material; do not hand-crop architectural mistakes'} as const
const themes={
 watch:'An old American watch repair business: muted blue-green paint. Replace the large upper inset panel with dusty dark glass. On the glass, small faded gold WATCH REPAIR lettering, a small hanging OPEN card near the handle, subtle glimpse of distant clock-shop shelving. Realistic understated shop details; no giant clock face or category emblem.',
 photo:'An old American photo studio: muted reddish brown paint. Replace the large upper inset panel with dusty dark glass. On the glass, small faded cream PHOTO STUDIO lettering, two small old sepia portrait prints taped near a bottom corner and a small worn opening-hours card. Realistic understated shop details; no camera icon or category emblem.',
} as const
export function doorLeafGenerationRequest(trade:keyof typeof themes,requestId:string,sessionId:string,hinge:'left'|'right'='right'):GenerateImageMediaRequest&{requestId:string}{
 if(!(trade in themes))throw Error('DOOR_THEME_UNKNOWN')
 return {mode:'edit',sessionId,requestId,referenceUrls:[DOOR_LEAF_REFERENCE],size:{width:512,height:768},prompt:'STRUCTURE LOCK: Edit the reference MOVABLE LEAF IN PLACE. Keep its exact outer silhouette, single rectangular slab, pixel-art style, proportions, position and canvas. Keep the same door panel silhouette, but place the handle on the '+(hinge==='left'?'RIGHT':'LEFT')+' and the hinge pieces directly on the '+hinge.toUpperCase()+' slab edge, protruding into magenta. Lettering must read normally, never mirrored. This is a salvaged movable panel REMOVED from its building. NOTHING outside this existing silhouette may be added. No fixed frame around it, no architectural jambs, no lintel, no sill, no walls, no floor. Its wooden outer stiles move with this single leaf. Keep STRICT FRONT ELEVATION: parallel edges, no isometric view, no vanishing point. Change ONLY the surface design inside the existing slab: '+themes[trade]+' Keep the small solid lower kick panel and realistic wear. Thin stiles, understated reflections, detailed crisp medium pixel clusters. Uniform pure magenta #FF00FF outside existing silhouette; no shadow or glow. Do not enlarge signage to a poster. The engine owns the doorframe and solid-color top/edge thickness; do not paint those architectural pieces. One complete leaf only, no duplicates.'}
}
