import React,{useEffect,useRef,useState} from 'react'
import {BrowserLayeredDrafts,layeredDatabaseName,newLayeredSource,prepareLayeredDraft,type LayeredDraft} from './layered-draft'
import {fanPartsSpec,FAN_PARTS_SOURCE,type LayeredSpec} from './layered-device'
import {inspectSpritePng} from './sprite-draft'
import {decodeSpritePixels,encodeSpritePixels,spritePreviewUrl} from './sprite-browser-io'
import fanSample from '../doc/platform-art-candidates/20260912/tunnel-fan-parts-01/candidate.png'
import './art-creator.css'
import LayeredCloudPanel from './layered-cloud-panel'
const io={decode:decodeSpritePixels,encode:encodeSpritePixels}
export default function LayeredCreator(){
 const zh=navigator.language.startsWith('zh'),t=(a:string,b:string)=>zh?a:b,store=useRef<BrowserLayeredDrafts>(),mounted=useRef(true),working=useRef(false)
 const [ready,setReady]=useState(false),[busy,setBusy]=useState(false),[draft,setDraft]=useState<LayeredDraft>(),[history,setHistory]=useState<LayeredDraft[]>([]),[spec,setSpec]=useState<LayeredSpec>(structuredClone(fanPartsSpec)),[error,setError]=useState(''),[urls,setUrls]=useState<string[]>([])
 function apply(d?:LayeredDraft){setDraft(d);if(d)setSpec(structuredClone(d.spec))}
 useEffect(()=>{mounted.current=true;const repo=new BrowserLayeredDrafts(layeredDatabaseName(location.href));store.current=repo;void Promise.all([repo.get(),repo.list()]).then(([d,h])=>{if(mounted.current){apply(d);setHistory(h);setReady(true)}}).catch(()=>setError('LAYER_STORAGE_FAILED'));return()=>{mounted.current=false;void repo.close()}},[])
 useEffect(()=>{let disposed=false;const created:string[]=[];setUrls([]);void(async()=>{try{if(!draft)return;for(const png of [draft.source,...(draft.result?[draft.result.housing,draft.result.rotor]:[])]){const url=await spritePreviewUrl(png);if(disposed){URL.revokeObjectURL(url);return}created.push(url)}setUrls(created)}catch{if(!disposed)setError('LAYER_CORRUPT')}})();return()=>{disposed=true;created.forEach(url=>URL.revokeObjectURL(url))}},[draft?.id,draft?.revision])
 async function locked(work:()=>Promise<void>){if(!ready||busy||working.current)return;working.current=true;setBusy(true);setError('');try{if(!navigator.locks)throw Error('LAYER_LOCK_UNAVAILABLE');await navigator.locks.request(layeredDatabaseName(location.href),{ifAvailable:true},async lock=>{if(!lock)throw Error('LAYER_OTHER_TAB');await work()})}catch(e){if(mounted.current)setError(e instanceof Error?e.message:'LAYER_OPERATION_FAILED')}finally{working.current=false;if(mounted.current){setBusy(false);try{apply(await store.current!.get());setHistory(await store.current!.list())}catch{setError('LAYER_STORAGE_FAILED')}}}}
 async function importPng(bytes:Uint8Array,name:string,sample=false){const png=await inspectSpritePng(bytes);if(sample&&png.sha256!==FAN_PARTS_SOURCE)throw Error('LAYER_CORRUPT');const checked=await spritePreviewUrl(png);URL.revokeObjectURL(checked);const s=sample?structuredClone(fanPartsSpec):{...structuredClone(fanPartsSpec),housingFoot:{x:Math.floor(png.width/4),y:Math.floor(png.height*.76)},rotorCenter:{x:Math.floor(png.width/4),y:Math.floor(png.height/2)},housingCenter:{x:Math.floor(png.width/4),y:Math.floor(png.height*.55)},reviewedFanAperture:false};const d=newLayeredSource(png,name,s);await store.current!.save(d,await store.current!.get())}
 const changes=draft&&JSON.stringify(spec)!==JSON.stringify(draft.spec)
 function point(key:'housingFoot'|'rotorCenter'|'housingCenter',label:string){return <fieldset><legend>{label}</legend>{(['x','y'] as const).map(axis=><label key={axis}>{axis.toUpperCase()}<input aria-label={`${key}-${axis}`} type="number" step="1" value={Number.isFinite(spec[key][axis])?spec[key][axis]:''} disabled={busy} onChange={e=>setSpec({...spec,[key]:{...spec[key],[axis]:e.target.valueAsNumber}})}/></label>)}</fieldset>}
 const errors:Record<string,string>={LAYER_SPEC_INVALID:t('请检查参数：坐标须在各自半张原图内，缩放为0.01–0.5，一转400–10000毫秒。','Check settings: coordinates must fit each source half, scales 0.01–0.5 and period 400–10000 ms.'),LAYER_DRAFT_REPLACED:t('另一窗口已更新记录，请在最新记录上继续。','Another tab updated this record. Continue from the latest version.'),LAYER_OTHER_TAB:t('另一窗口正在处理，请稍后重试。','Another tab is processing. Please retry.'),SPRITE_PREPARATION_FRAME_DOES_NOT_FIT:t('对齐后超出画布，请调整机座接地点或叶轮轴心。','Alignment exceeds the canvas. Adjust the contact point or rotor center.')}
 return <main className="cl-creator cl-sprite"><header><a href="./creator.html?create_art=sprite">{t('返回人物与设备准备','Back to character and equipment preparation')}</a><h1>{t('固定机壳与旋转部件','Fixed housing and rotating part')}</h1><p>{t('左列机壳，右列叶轮。两列尺寸相同；原图保留，透明处理另存候选。','Housing in the left column, rotor in the right. Equal columns; retain the source and save cutouts as candidates.')}</p></header>
 <section><label htmlFor="layer-source">{t('导入两列 PNG（最多8 MiB）','Import two-column PNG (up to 8 MiB)')}</label><input id="layer-source" type="file" accept="image/png" disabled={!ready||busy} onChange={e=>{const file=e.target.files?.[0];e.target.value='';if(file)void locked(async()=>{if(file.size>8*1024*1024)throw Error('SPRITE_INVALID_PNG');await importPng(new Uint8Array(await file.arrayBuffer()),file.name)})}}/><button disabled={!ready||busy} onClick={()=>void locked(async()=>{const r=await fetch(fanSample,{credentials:'omit'});if(!r.ok)throw Error('LAYER_DOWNLOAD');await importPng(new Uint8Array(await r.arrayBuffer()),'platform-tunnel-fan-parts-01',true)})}>{t('载入平台通风机原图','Load platform fan source')}</button><p>{t('样本已生成，此操作不请求生图。上传图的内部孔洞不会自动去底；请在结果中检查。','The sample is already generated; loading makes no generation request. Uploaded images need transparent internal apertures; inspect the result.')}</p></section>
 {draft&&<><section><h2>{t('对齐与运行参数','Alignment and motion')}</h2><p>{t('坐标都以各自半张原图左上角为原点。机壳轴心是叶轮安装在机壳上的位置。尺寸仅影响地图等比显示，不重采样素材。','Coordinates start at the top-left of each source half. Housing center marks the rotor attachment. Scales affect map display without resampling the images.')}</p>
 {point('housingFoot',t('机壳接地点','Housing contact point'))}{point('rotorCenter',t('叶轮轴心','Rotor center'))}{point('housingCenter',t('机壳轴心','Housing attachment center'))}
 {([['housingScale',t('机壳显示比例','Housing display scale')],['rotorScale',t('叶轮显示比例','Rotor display scale')],['periodMs',t('一转时长（毫秒）','Rotation period (ms)')]] as const).map(([key,label])=><label key={key}>{label}<input id={`layer-${key}`} type="number" step={key==='periodMs'?100:.001} value={Number.isFinite(spec[key])?spec[key]:''} disabled={busy} onChange={e=>setSpec({...spec,[key]:e.target.valueAsNumber})}/></label>)}
 <fieldset><legend>{t('固定机座占地（世界单位）','Fixed base collision (world units)')}</legend>{(['width','depth','front'] as const).map((key,i)=><label key={key}>{[t('宽度','Width'),t('向后深度','Rear depth'),t('向前延伸','Front extension')][i]}<input id={`layer-body-${key}`} type="number" step="1" value={Number.isFinite(spec.body[key])?spec.body[key]:''} disabled={busy} onChange={e=>setSpec({...spec,body:{...spec.body,[key]:e.target.valueAsNumber}})}/></label>)}</fieldset>
 {draft.spec.reviewedFanAperture&&<p>{t('此原图使用已核对的轮毂孔去底范围；其他原图不会沿用这项处理。','This source uses its reviewed shaft-aperture mask; other sources never inherit it.')}</p>}
 <button className="cl-primary" disabled={!ready||busy} onClick={()=>void locked(async()=>{await prepareLayeredDraft(store.current!,draft,spec,io,d=>{if(mounted.current)setDraft(d)})})}>{busy?t('正在处理…','Processing…'):t('处理并保存分层候选','Process and save layered candidate')}</button>
 {changes&&<p role="status">{t('参数尚未保存。处理后生成新候选；下面的预览仍是上次保存的版本。','Settings are unsaved. Processing creates a new candidate; previews below show the saved version.')}</p>}
 </section><p role="status">{draft.state==='candidate'?t('分层候选已保存。','Layered candidate saved.'):draft.state==='processing'&&!busy?t('上次处理未完成，原图已保留，可重试。','The previous attempt did not finish. Source retained; retry processing.'):t('原图已保存在当前浏览器。','Source saved in this browser.')}</p>
 <section aria-label={t('分层素材预览','Layered art preview')}>{urls.map((url,i)=><figure key={url}><figcaption>{[t('保留的原图','Retained original'),t('固定机壳','Fixed housing'),t('旋转部件','Rotating part')][i]}</figcaption><div className="cl-sprite__preview cl-sprite__preview--dark"><img src={url} alt={[t('原图','Source'),t('机壳透明结果','Housing cutout'),t('叶轮透明结果','Rotor cutout')][i]} draggable={false}/></div>{i>0&&<a href={url} download={`layer-${draft.id}-${i===1?'housing':'rotor'}.png`}>{t('导出透明 PNG','Export transparent PNG')}</a>}</figure>)}{draft.state==='candidate'&&<a className="cl-creator__action" href={`./creator.html?scene_preview=north-cape&layered_draft=${encodeURIComponent(draft.id)}`}>{t('在地图里检查分层设备','Inspect layered device in the map')}</a>}
 {draft.review&&<p>{t('此保存版本已记录地图画面确认；在线发布状态见下方。','Map visual confirmation is recorded for this saved version; see publication status below.')}</p>}</section></>}
 {(error||draft?.error)&&<p role="alert">{errors[error||draft?.error||'']??t('操作未完成，原图和已有候选保留。请检查图片与参数后重试。','Operation did not complete. Source and previous candidates remain; check the image and settings, then retry.')}<small>{error||draft?.error}</small></p>}
 {!!history.length&&<section><label htmlFor="layer-history">{t('已保存分层记录','Saved layered records')}</label><select id="layer-history" disabled={busy} value={draft?.id??''} onChange={e=>{const id=e.target.value;void locked(async()=>{const d=await store.current!.get(id);if(!d)throw Error('LAYER_CORRUPT');await store.current!.save(d,await store.current!.get())})}}>{history.map(d=><option key={d.id} value={d.id}>{d.sourceName} · {d.result?t('候选','Candidate'):t('原图/未完成','Source/unfinished')} · {new Date(d.createdAt).toLocaleTimeString()}</option>)}</select></section>}
 <>{ready&&store.current&&<LayeredCloudPanel repo={store.current} draft={draft} busy={busy} locked={locked}/>}</><footer><p>{t('当前支持固定机壳与一个旋转部件。保存在当前浏览器，地图检查不创建旅程或替换正式游戏素材。','Supports a fixed housing and one rotating part. Saved in this browser; map review does not create a journey or replace live assets.')}</p></footer></main>
}
