import React,{useState} from 'react'
import {creatorCloudTransport} from './creator-cloud'
import {LayeredCloudArchive} from './layered-cloud'
import {inspectLayeredDraft,type LayeredDraft,type BrowserLayeredDrafts} from './layered-draft'
import {decodeSpritePixels,encodeSpritePixels} from './sprite-browser-io'
import {layerReleasePath,type LayerRecord,type PublishedLayer} from './layered-archive-contract'
import {GAME_ID} from './game-id'
const io={decode:decodeSpritePixels,encode:encodeSpritePixels}
export default function LayeredCloudPanel({repo,draft,busy,locked}:{repo:BrowserLayeredDrafts;draft?:LayeredDraft;busy:boolean;locked:(work:()=>Promise<void>)=>Promise<void>}){
 const zh=navigator.language.startsWith('zh'),t=(a:string,b:string)=>zh?a:b
 const [cloud]=useState(()=>new LayeredCloudArchive(creatorCloudTransport(window.alteruLocalStorage,async(name,work)=>await navigator.locks.request(name,work))))
 const [records,setRecords]=useState<LayerRecord[]>(),[releases,setReleases]=useState<Record<string,PublishedLayer>>({}),[message,setMessage]=useState(''),[error,setError]=useState('')
 async function refresh(){const records=await cloud.list(),entries=await Promise.all(records.map(async r=>[r.manifest.id,await cloud.publication(r.manifest.id)]as const));setRecords(records);setReleases(Object.fromEntries(entries.filter(([_,r])=>r!==null)) as Record<string,PublishedLayer>)}
 async function operate(action:'save'|'publish'|'list'|'restore'|'cancel',record?:LayerRecord){await locked(async()=>{setError('');setMessage(t('正在处理在线素材…','Working on online art…'));try{
  if(action==='list'){await refresh();setMessage('');return}
  if(action==='cancel'){await cloud.cancel(record!);await refresh();setMessage(t('已清除未完成上传，本地记录保留。','Incomplete upload removed; local records retained.'));return}
  const current=await repo.get();if(current?.id!==draft?.id||current?.revision!==draft?.revision)throw Error('LAYER_DRAFT_REPLACED')
  if(action==='restore'){const restored=await cloud.restore(record!);await inspectLayeredDraft(restored,restored.id,io);const existing=await repo.get(restored.id);if(existing){const verified=await inspectLayeredDraft(existing,existing.id,io),incoming=await inspectLayeredDraft(restored,restored.id,io);if(verified.signature!==incoming.signature)throw Error('LAYER_ARCHIVE_CONFLICT');restored.revision=existing.revision+1;if(!restored.review&&existing.review)restored.review=existing.review}await repo.save(restored,current);setMessage(t('原图、两层素材、参数与已保存检查已取回。','Original, both layers, settings and saved review restored.'));return}
  if(!current)throw Error('LAYER_NOT_READY');await inspectLayeredDraft(current,current.id,io)
  if(action==='publish')await cloud.publish(current);else await cloud.save(current,(done,total)=>setMessage(t(`正在上传 ${Math.round(done/total*100)}%`,`Uploading ${Math.round(done/total*100)}%`)))
  await refresh();setMessage(action==='publish'?t('通风机版本已公开发布，原图仍为私有。新旅程可采用此版本。','Fan version published; its original remains private. New journeys can use this version.'):t('原图、两层素材、参数与当前检查已在线保存。','Original, both layers, settings and current review saved online.'))
 }catch(e){const code=e instanceof Error?e.message:'LAYER_OPERATION_FAILED';setMessage('');setError(code==='LAYER_ARCHIVE_LIMIT'?t('已有6份在线记录。可清除未完成上传；完成版本保留。','Six records are stored. Remove incomplete uploads; completed records are retained.'):code==='NOT_FOUND'||code==='RUNTIME_VERSION_MISMATCH'?t('当前部署尚未支持分层在线素材，本地记录保留。','This deployment does not support layered archives yet. Local records remain.'):t('在线操作未完成，本地记录保留。重试会继续同一候选；素材改变时需另存新候选。','Online operation did not finish. Local records remain. Retry resumes the same candidate; changed art needs a new candidate.')+' '+code)}})}
 if(location.hostname.endsWith('.github.io'))return <section><h2>{t('在线分层设备','Online layered devices')}</h2><p>{t('静态镜像不能保存在线素材，请使用主站制作页。','Use the main-site creator for online storage; this is a static mirror.')}</p><a href={`https://game.aiwaves.tech/${GAME_ID}/creator.html?create_art=layers`}>{t('打开主站制作页','Open main-site creator')}</a></section>
 return <section aria-label={t('在线分层设备','Online layered devices')}><h2>{t('在线分层设备','Online layered devices')}</h2><p>{t('最多6份，每份原图与两层结果合计不超过24MiB。仍使用本浏览器制作身份，尚未绑定平台账户。','Up to six records, each with at most 24MiB of source and cutouts. Access uses this browser’s creation identity, not a platform account yet.')}</p>
 <button disabled={busy||draft?.state!=='candidate'} onClick={()=>void operate('save')}>{t('在线保存当前分层设备','Save layered device online')}</button><button disabled={busy} onClick={()=>void operate('list')}>{t('查看在线分层设备','View online layered devices')}</button>
 <p>{t('发布后用作隧道通风机。请确认是带独立叶轮的通风设备，轴心、尺寸与固定占地已通过地图检查；新版本不替换已有旅程。','Publication assigns this art to the tunnel fan. Confirm a ventilation device with a separate rotor and reviewed pivot, scale and fixed footprint. Existing journeys keep their versions.')}</p><button disabled={busy||!draft?.review||draft.state!=='candidate'} onClick={()=>void operate('publish')}>{t('公开发布通风机版本','Publish fan version publicly')}</button>
 {message&&<p role="status">{message}</p>}{error&&<p role="alert">{error}</p>}{records?.length===0&&<p>{t('还没有在线分层素材。','No online layered art yet.')}</p>}
 {records?.map((r,i)=><div key={r.manifest.id}><p>{i+1} · {r.manifest.sourceName} · {r.state==='uploading'?t('上传未完成','Upload incomplete'):releases[r.manifest.id]?t('已发布','Published'):t('已保存','Saved')}</p>{r.state==='ready'?<button disabled={busy} onClick={()=>void operate('restore',r)}>{t('取回此分层设备及原图','Restore layered device and original')}</button>:<button disabled={busy} onClick={()=>void operate('cancel',r)}>{t('清除未完成上传','Remove incomplete upload')}</button>}{releases[r.manifest.id]&&(import.meta.env.MODE==='cloud-preflight'?<a href={`./?story=original&fan_release=${encodeURIComponent(releases[r.manifest.id].id)}`}>{t('用此通风机进入独立旅程','Enter a separate journey with this fan')}</a>:<a href={layerReleasePath(releases[r.manifest.id].id)}>{t('查看固定发布版本','View the fixed release')}</a>)}</div>)}</section>
}
