import React,{useEffect,useRef,useState} from 'react'
import {Assets} from 'pixi.js'
import type {RpgPlayer} from '@rpgjs/server'
import {BrowserLayeredDrafts,layeredDatabaseName,inspectLayeredDraft,saveLayerReview,type LayeredDraft} from './layered-draft'
import {layeredSheets,layerBlocks,layerPose,LAYER_CHECKS} from './layered-device'
import {decodeSpritePixels,encodeSpritePixels,spritePreviewUrl} from './sprite-browser-io'
import {originalTrainRoom} from './original-train-spatial-plan'
const io={decode:decodeSpritePixels,encode:encodeSpritePixels}
const placement=(scene:string)=>scene===originalTrainRoom('river-valley')?{x:280,y:420}:{x:110,y:160}
export function useLayeredMapTrial(id:string|null,props:{scene:string;ready:boolean;position:{x:number;y:number};rendered:{x:number;y:number}|null;walk:(p:{x:number;y:number})=>void}){
 const zh=navigator.language.startsWith('zh'),t=(a:string,b:string)=>zh?a:b
 const candidate=useRef<{draft:LayeredDraft;signature:string}>(),events=useRef(new Map<string,RpgPlayer>()),urls=useRef<string[]>([]),mounted=useRef(true),elapsed=useRef(0),runningRef=useRef(false)
 const [running,setRunning]=useState(false),[checks,setChecks]=useState<string[]>([]),[saved,setSaved]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState('')
 const add=(check:string)=>setChecks(old=>old.includes(check)?old:[...old,check])
 function apply(scene:string){const c=candidate.current;if(!c)return;for(const part of ['housing','rotor']){const e=events.current.get(scene+':'+part);if(!e)continue;const graphic='layer-'+c.draft.id+'-'+part,pose=part==='housing'?'stand':runningRef.current?layerPose(elapsed.current,c.draft.spec.periodMs):'stopped';const changed=e.graphics()[0]!==graphic;if(changed)e.setGraphic(graphic);e.animationFixed=true;if(changed||e.animationName()!==pose){e.animationName.set(pose);e.syncChanges()}}}
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;events.current.clear();for(const url of urls.current){void Assets.unload(url).catch(()=>{});URL.revokeObjectURL(url)}urls.current=[]}},[])
 async function load(){if(!id)return [];const repo=new BrowserLayeredDrafts(layeredDatabaseName(location.href));try{const d=await repo.get(id);if(!d)throw Error('LAYER_MISSING');const c=await inspectLayeredDraft(d,id,io);if(!mounted.current)return[];candidate.current=c;const images=[];for(const png of [d.result!.housing,d.result!.rotor]){const url=await spritePreviewUrl(png);if(!mounted.current){URL.revokeObjectURL(url);return[]}urls.current.push(url);const texture=await Assets.load({src:url,parser:'loadTextures'});if(texture?.width!==png.width||texture?.height!==png.height)throw Error('LAYER_TEXTURE_NOT_READY');images.push(url)}if(!mounted.current)return[];return layeredSheets('layer-'+id,images[0],images[1],d.result!.housing.width,d.result!.housing.height,d.spec)}finally{await repo.close()}}
 function mapEvents(scene:string){if(!candidate.current)return[];const at=placement(scene);return ['housing','rotor'].map((part,i)=>({id:'layer-'+id+'-'+part+'-'+scene,x:at.x,y:at.y-1+i*.01,event:{onInit(this:RpgPlayer){this.setHitbox(1,1);this.through=true;events.current.set(scene+':'+part,this);apply(scene)}}}))}
 function blocks(p:{x:number;y:number},scene:string){return Boolean(candidate.current&&layerBlocks(candidate.current.draft.spec,placement(scene),p))}
 useEffect(()=>{if(!id||!props.ready||!candidate.current)return;let raf=0,last=performance.now(),observedMs=0;const step=(now:number)=>{const dt=now-last;last=now;if(!document.hidden&&dt>=0&&dt<=250){if(runningRef.current){elapsed.current+=dt;observedMs+=dt;}apply(props.scene);if(props.scene===originalTrainRoom('dead-station')&&events.current.has(props.scene+':rotor')){if(!runningRef.current)add('stopped');else if(observedMs>=candidate.current!.draft.spec.periodMs)add('running')}}raf=requestAnimationFrame(step)};raf=requestAnimationFrame(step);return()=>cancelAnimationFrame(raf)},[id,props.ready,props.scene,running])
 useEffect(()=>{const c=candidate.current;if(!id||!c||!props.ready||props.scene!==originalTrainRoom('dead-station')||!props.rendered||Math.hypot(props.position.x-props.rendered.x,props.position.y-props.rendered.y)>1.5)return;const at=placement(props.scene);if(Math.hypot(props.position.x-(at.x-4.5),props.position.y-(at.y+c.draft.spec.body.front+2))<3)add('front');if(Math.hypot(props.position.x-(at.x-4.5),props.position.y-(at.y-c.draft.spec.body.depth-20))<3)add('back')},[id,props.ready,props.scene,props.position,props.rendered])
 function recordWalk(p:{x:number;y:number},scene:string,accepted:boolean){if(!id||!candidate.current||scene!==originalTrainRoom('dead-station'))return;const at=placement(scene);if(p.x===at.x-4.5&&p.y===at.y-12&&!accepted&&blocks(p,scene))add('collision')}
 async function save(){if(!candidate.current||saving||!LAYER_CHECKS.every(c=>checks.includes(c)))return;setSaving(true);setError('');try{await navigator.locks.request(layeredDatabaseName(location.href),async()=>{const repo=new BrowserLayeredDrafts(layeredDatabaseName(location.href));try{const c=candidate.current!,d=await saveLayerReview(repo,c.draft,checks,c.signature,io);candidate.current={...c,draft:d};setSaved(true)}finally{await repo.close()}})}catch{setError(t('候选或参数可能已变化，检查记录未保存。请返回准备页核对。','Candidate or settings may have changed. Review was not saved; check the preparation page.'))}finally{setSaving(false)}}
 const at=placement(props.scene),c=candidate.current
 const panel=id?<section className="cl-background-review cl-layer-review" aria-label={t('分层设备检查','Layered device checks')}>
 <a href="./creator.html?create_art=layers">{t('返回分层设备准备','Back to layered preparation')}</a>
 <p>{t('机壳固定，叶轮独立转动。此候选尚未发布。','Housing stays fixed while the rotor turns. This candidate is not published.')}</p>
 <div>{[false,true].map(value=><button key={String(value)} aria-pressed={running===value} disabled={!props.ready} onClick={()=>{runningRef.current=value;elapsed.current=0;setRunning(value);apply(props.scene)}}>{value?t('运行叶轮','Run rotor'):t('停止叶轮','Stop rotor')}</button>)}</div>
 <div><button disabled={!props.ready||!c} onClick={()=>props.walk({x:at.x-4.5,y:at.y+(c?.draft.spec.body.front??3)+2})}>{t('走到机座前','Walk in front of base')}</button><button disabled={!props.ready||!c} onClick={()=>props.walk({x:at.x-4.5,y:at.y-(c?.draft.spec.body.depth??12)-20})}>{t('走到机座后','Walk behind base')}</button><button disabled={!props.ready} onClick={()=>props.walk({x:at.x-4.5,y:at.y-12})}>{t('检查机座阻挡','Check base collision')}</button></div>
 <details><summary>{t('分层地图检查','Layered map review')} {checks.length}/5</summary><p>{t('在北岬观察停止与完整一转，走到前后并检查机座阻挡，再确认轴心、遮挡、透明边缘与比例。','At North Cape, observe stopped and a full rotation, walk in front and behind, and check base collision. Then confirm the pivot, occlusion, alpha edges and scale.')}</p><p>{LAYER_CHECKS.filter(c=>!checks.includes(c)).map((c)=>({stopped:t('停止','Stopped'),running:t('完整一转','Full rotation'),front:t('机座前','Front'),back:t('机座后','Behind'),collision:t('阻挡','Collision')}[c])).join(' · ')}</p><button disabled={!props.ready||saving||saved||checks.length!==5} onClick={()=>void save()}>{saved?t('分层地图检查已保存','Layered map review saved'):t('确认分层画面并保存检查','Confirm layered visuals and save review')}</button></details>{error&&<p role="alert">{error}</p>}
 </section>:null
 return {load,mapEvents,blocks,recordWalk,panel,apply}
}
