import {originalEntry} from './original-release'
import {JournalImagePanel} from './journal-image-ui'
import {journalImageAvailable} from './journal-image-release'
import {rendererFailure,rendererNeedsPageReload} from './renderer-transition'
import {activeRelay,relaySummary,relayMessage} from './relay-content'
import {createBrowserSceneReadiness,ScenePreparationError} from './scene-readiness'
import {prepareSceneAction} from './prepare-scene-action'
import {NARRATION_POLICY,narrationMode} from './narration-policy'
import {ReceptionActions} from './reception-ui'
import './game-id'
import {getGameApiBase} from './game-id'
import {isBrowserEdition,isCloudEdition,isMirrorEdition} from './runtime-mode'
import React, { useEffect, useLayoutEffect, useRef, useState } from 'react'
import { createRoot } from 'react-dom/client'
import {attendantName,attendantReply} from './attendant'
import { cartridge, linResponse, tr, type Locale } from './story'
import { entities, nearest, nextAction, actionLabel, states, currentScene, sceneEntities, SPAWN, type EntityId, type Position } from './contract'
import { enroll, recover, sendAction, api, readLocal, writeLocal, hasPending, isUiDemo, type Head } from './client-session'
import { getSpace, onPosition, onDestination } from './space-bridge'
import { scenes,sceneIds,approachPoints } from './scene-layout'
import {WorldArt,ExtraArt} from './world-art'
import { visualStates } from './visual-states'
import { PropArt } from './prop-art'
import {objectiveCopy,actionFeedback} from './ui-copy'
import {isArtDemo,isBalancedArt} from './art-variant'
import {PowerChoice,radioDescription,radioStatus} from './power-choice'
import {RadioContact,PeopleMet} from './contacts-ui'
import {dialoguePages} from './dialogue-pages'
import {ChapterResult} from './chapter-result'
import './style.css'

function Icon({name}:{name:string}){const paths:Record<string,string>={chevron:'m7 10 5 5 5-5',back:'m14 6-6 6 6 6',route:'M5 5h14v14H5V5Zm0 7h14M12 5v14',menu:'M5 7h14M5 12h14M5 17h14',bag:'M7 8V6a5 5 0 0 1 10 0v2M4 8h16l1 13H3L4 8Z',log:'M5 3h14v18H5V3Zm4 5h6M9 12h6M9 16h4',close:'m6 6 12 12M6 18 18 6',sound:'M3 9h4l5-5v16l-5-5H3V9Zm13-2a7 7 0 0 1 0 10m3-13a11 11 0 0 1 0 16',arrow:'M4 12h15m-6-6 6 6-6 6',check:'m5 12 4 4L19 6',move:'M12 3v18M3 12h18m-12-6 3-3 3 3m-9 3-3 3 3 3m3 3 3 3 3-3m3-9 3 3-3 3'};return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={paths[name]??paths.arrow}/></svg>}
type ActionDraft={headId:string;version:number;target:EntityId;free:boolean;action?:string;text:string;mode:'local'|'live';position:Position}
function App(){
 const [readiness]=useState(createBrowserSceneReadiness),[sceneRetry,setSceneRetry]=useState(0),[mapReload,setMapReload]=useState(false)
 const [assetIssue,setAssetIssue]=useState<ActionDraft|null>(null),assetIssueRef=useRef(assetIssue);assetIssueRef.current=assetIssue
 const [locale,setLocale]=useState<Locale>(()=>readLocal('locale',navigator.language.startsWith('zh')?'zh':'en'))
 const t=(zh:string,en:string)=>tr(locale,zh,en)
 const [head,setHead]=useState<Head|null>(null),[position,setPosition]=useState<Position>(SPAWN),[panel,setPanel]=useState<EntityId|'bag'|'log'|'route'|'settings'|'menu'|'objective'|'people'|'chapter'|'promise'|null>(null)
 const [switching,setSwitching]=useState(true),[mapError,setMapError]=useState(false)
 const switchingRef=useRef(true);switchingRef.current=switching
 const mapFrame=useRef<HTMLDivElement>(null)
 const [toastRecorded,setToastRecorded]=useState(false),[toastArchived,setToastArchived]=useState(false),[toastFocused,setToastFocused]=useState(false)
 const [destination,setDestination]=useState<Position|null>(null)
 const [dialog,setDialog]=useState<EntityId|null>(null),[composer,setComposer]=useState(false),[toast,setToast]=useState(''),[pageIndex,setPageIndex]=useState(0)
 const [versionIssue,setVersionIssue]=useState(false)
 const versionMessage=()=>t('游戏版本正在更新。请刷新页面后继续，进度与待确认操作会保留。','The game version has changed. Refresh to continue; progress and pending actions are preserved.')
 function versionError(e:unknown){const yes=e instanceof Error&&['RUNTIME_VERSION_MISMATCH','JOURNEY_VERSION_UNSUPPORTED','BROWSER_SAVE_VERSION_UNSUPPORTED'].includes(e.message);setVersionIssue(yes);return yes}
 const [result,setResult]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[ready,setReady]=useState(false),[input,setInput]=useState(''),[mode,setMode]=useState<'local'|'live'>(()=>narrationMode(readLocal(NARRATION_POLICY.modeKey,'local'),isBrowserEdition))
 const [muted,setMuted]=useState(true),[fallback,setFallback]=useState(false),[fallbackReason,setFallbackReason]=useState(''),[restartConfirm,setRestartConfirm]=useState(false)
 const headRef=useRef(head),panelRef=useRef<typeof panel>(panel),dialogRef=useRef(dialog),interactRef=useRef<(id:EntityId)=>void>(()=>{}),advanceRef=useRef(()=>{}),busyRef=useRef(busy),posRef=useRef(position),audio=useRef<AudioContext|null>(null),joystick=useRef<HTMLDivElement>(null),[stick,setStick]=useState({x:0,y:0})
 headRef.current=head;panelRef.current=panel;dialogRef.current=dialog;busyRef.current=busy;posRef.current=position
 const s=head?.save,scene=s?currentScene(s):'carriage',target=nearest(position,scene)
 function updateCamera(){const frame=mapFrame.current;if(!frame)return;const viewport=frame.parentElement!;const scale=frame.clientWidth/384;const immersive=matchMedia('(max-width:699px),(max-height:500px)').matches;const y=immersive?Math.max(Math.min(0,viewport.clientHeight-frame.clientHeight),Math.min(0,viewport.clientHeight*.52-(posRef.current.y+15)*scale)):0;frame.style.setProperty('--camera-y',`${y}px`)}
 useLayoutEffect(updateCamera,[position.y,scene])
 useLayoutEffect(()=>{const frame=mapFrame.current;if(!frame)return;const observer=new ResizeObserver(updateCamera);observer.observe(frame);observer.observe(frame.parentElement!);return()=>observer.disconnect()},[])
 function sound(kind:string){if(muted)return;try{audio.current??=new AudioContext();void audio.current.resume();const a=audio.current;const o=a.createOscillator(),g=a.createGain();o.type=kind==='open-cabinet'?'triangle':'sine';o.frequency.value=kind==='repair'?660:kind==='open-cabinet'?170:420;g.gain.setValueAtTime(0.035,a.currentTime);g.gain.exponentialRampToValueAtTime(0.0001,a.currentTime+0.15);o.connect(g).connect(a.destination);o.start();o.stop(a.currentTime+0.16)}catch{}}
 function receive(h:Head){if(!headRef.current||h.id!==headRef.current.id||currentScene(h.save)!==currentScene(headRef.current.save)){setSwitching(true);switchingRef.current=true;getSpace()?.pause(true);setDestination(null);setDialog(null);setToast('')}headRef.current=h;setHead(h)}
 function describe(id:EntityId,h=headRef.current){if(!h)return '';const request=activeRelay(h.save);if(request&&(request.plan.source===id||request.plan.recipient===id)&&['offered','accepted','delivered'].includes(request.phase))return relaySummary(h.save,locale)![1]+'\n'+relayMessage(request.plan,locale);const f=h.save.facts;if(id==='zhou-yu')return attendantReply({...h.save,locale});if(id==='callpoint')return t(f.journey_complete?'联络器亮着。许岚已经登记你的安全抵达，可以继续交谈或回顾旅程。':'联络器的电源灯稳定亮着，听筒里传来许岚熟悉的声音。你已经抵达接应点，可以向她报平安。',f.journey_complete?'The call point is lit. Xu Lan has recorded your safe arrival. You can talk or revisit your journey.':'The call point is powered. Xu Lan’s familiar voice comes from the handset. You have reached reception and can report your safe arrival.');if(id==='radio')return radioDescription(h.save,locale);if(id==='panel'&&f.guidance_released)return t('临时引导已撤收，照明保持常亮。后端步道已经开放。','Temporary guidance is released. The lights stay on, and the rear walkway is open.');if(id==='lin'&&f.introduced&&(f.power_chosen||f.rescue_sent))return linResponse(h.save,locale);if(id==='panel'&&f.beacon_set)return t('引导灯正在照亮连接门，接应已经看到了信号。','The door guide light is on; rescuers have seen the signal.');if(id==='panel'&&f.power_radio)return t('电路完好，功率留给电台；客厢只保留应急照明。','The circuit is intact. Power is routed to the radio; the carriage has emergency light.');if(id==='record')return t('夜间救援用 3 频道；1 频道为无人值守的调车频道。','Use channel 3 for night emergencies; yard channel 1 is unattended.');if(id==='supply')return t('柜门开着，中层电池已经取走。','The cabinet is open. Its battery shelf is empty.');return id==='cabinet'?t(f.fuse_taken?'柜门开着，保险丝的凹槽已经空了。':f.cabinet_open?'打开的柜子里，放着一枚备用保险丝。':'灰色的检修柜没有上锁。门把手就在你面前。',f.fuse_taken?'The cabinet is open. The fuse slot is empty.':f.cabinet_open?'A spare fuse sits inside the open cabinet.':'The grey service cabinet is unlocked. Its handle is within reach.'):
 id==='panel'?t(f.repaired?'指示灯稳定地亮着。电路已经恢复。':'配电箱上的红灯暗着，保险丝槽里是一截烧黑的部件。',f.repaired?'The indicator glows steadily. The circuit is restored.':'The indicator is dark. A burnt fuse sits in the circuit panel.'):
 id==='lin'?t(f.introduced?'林站在一旁，穿着灰色工作服。他愿意帮你把电路弄清楚。':'穿灰色工作服的人站在配电箱旁，灰白短发，正朝你看过来。',f.introduced?'Lin stands nearby, wearing his grey work jacket, ready to help.':'A person in grey work clothes stands by the panel, short grey hair, looking your way.'):
 t(f.repaired?'门锁已经松开，暖光从出口透进来。':'出口锁着。旁边的指示灯没有亮。',f.repaired?'The latch is released. Warm light spills through the exit.':'The exit is locked. Its indicator is dark.')}
 function open(id:typeof panel){if(busyRef.current||assetIssueRef.current)return;getSpace()?.move(0,0);setPanel(id)}
 async function openFullStory(){const h=headRef.current;if(!h||busyRef.current||hasPending())return;setBusy(true);getSpace()?.pause(true);try{await api('/sessions/'+h.id+'/position',{position:posRef.current,sceneId:currentScene(h.save),expected_version:h.version});location.assign('./?story=original')}catch{setBusy(false);announce(t('暂时未能保存位置，请再试一次。','Could not save your position. Please try again.'))}}
 async function switchArt(){const h=headRef.current;if(!h||busyRef.current||switchingRef.current)return;busyRef.current=true;setBusy(true);getSpace()?.pause(true);try{await api('/sessions/'+h.id+'/position',{position:posRef.current,sceneId:currentScene(h.save),expected_version:h.version});const url=new URL(location.href);url.searchParams.set('art',isBalancedArt?'baseline':'balanced');location.assign(url.href)}catch{announce(t('暂时未能保存位置，请再试一次。','Could not save your position. Please try again.'));busyRef.current=false;setBusy(false);getSpace()?.pause(false)}}
 async function init(restart=false){setBusy(true);setError('');setVersionIssue(false);try{const h=await enroll(locale,restart);const r=await recover();const next=r?.head??h;receive(next);setPosition(next.position);if(r?.text){setResult(r.text);setPageIndex(0);if(['send-signal','meet-dispatch'].includes(r.actionId))setDialog('radio');if(r.actionId==='meet-attendant')setDialog('zhou-yu')}}catch(e){setError(versionError(e)?versionMessage():isCloudEdition?t('暂时无法连接云端旅程。请稍后重试，已有进度不会改为本地存档。','Cloud journey is unavailable. Retry later; progress will not switch to local storage.'):isBrowserEdition?t('无法打开浏览器存档。请检查 Safari 网站存储是否可用，再重试。','Could not open browser storage. Check Safari website storage and retry.'):t('没有连接到本地旅程服务。请重试。','Could not reach the local journey service. Please retry.'))}finally{setBusy(false)}}
 useEffect(()=>{void init();let dead=false;const boot=async()=>{try{await import('./space');if(!dead&&getSpace())setReady(true)}catch(e){console.error(e);setError(t('地图没有加载完成。刷新后重试。','The map could not load. Refresh to retry.'))}};void boot();const onReady=()=>setReady(true);window.addEventListener('space-ready',onReady);const unsub=onPosition(p=>{posRef.current=p;setPosition({...p})});const unsubDestination=onDestination(setDestination);return()=>{dead=true;unsub();unsubDestination();window.removeEventListener('space-ready',onReady)}},[])
 useEffect(()=>{if(!ready||!head)return;let live=true;setSwitching(true);setMapError(false);setMapReload(false);getSpace()?.pause(true);void(async()=>{try{await readiness.prepare(scene,true);if(!live)return;await getSpace()!.restore(head.position,scene);if(live){readiness.activate(scene);setPosition(getSpace()!.position());setSwitching(false)}}catch(error){if(live){console.warn('[scene-resource]',scene,readiness.status(scene).reason??rendererFailure(error));setMapReload(rendererNeedsPageReload(rendererFailure(error)));setMapError(true)}}})();return()=>{live=false}},[ready,head?.id,scene,sceneRetry])
 useEffect(()=>{getSpace()?.pause(Boolean(panel)||Boolean(dialog)||busy||switching||Boolean(error)||Boolean(assetIssue))},[panel,dialog,busy,switching,error,ready,assetIssue])
 useEffect(()=>{const timer=setInterval(()=>{if(headRef.current&&!busyRef.current&&!switchingRef.current)void api('/sessions/'+headRef.current.id+'/position',{position:posRef.current,sceneId:currentScene(headRef.current.save),expected_version:headRef.current.version}).catch(()=>{})},2000);return()=>clearInterval(timer)},[])
 useEffect(()=>{const saveOnHide=()=>{if(document.visibilityState!=='hidden')return;getSpace()?.move(0,0);const h=headRef.current;if(h&&!busyRef.current&&!switchingRef.current)void api('/sessions/'+h.id+'/position',{position:posRef.current,sceneId:currentScene(h.save),expected_version:h.version}).catch(()=>{})};document.addEventListener('visibilitychange',saveOnHide);return()=>document.removeEventListener('visibilitychange',saveOnHide)},[])
 useEffect(()=>{function key(e:KeyboardEvent){if(assetIssueRef.current){if(e.key==='Escape'&&!busyRef.current){e.preventDefault();setAssetIssue(null)}return}if(e.key==='Escape'&&!e.isComposing&&!busyRef.current&&!(e.target as HTMLElement)?.matches('select')){e.preventDefault();setPanel(null);setDialog(null);setComposer(false);return}if((e.target as HTMLElement)?.matches('input,textarea,select'))return;if((e.target as HTMLElement)?.closest('button')&&['Enter',' '].includes(e.key))return;if(['e','E','Enter',' '].includes(e.key)&&!e.repeat&&!busyRef.current&&!switchingRef.current){e.preventDefault();if(dialogRef.current)advanceRef.current();else if(!panelRef.current){const n=nearest(posRef.current,headRef.current?currentScene(headRef.current.save):'carriage');if(n)interactRef.current(n)}}if(e.key==='Escape'&&!busyRef.current){setPanel(null);setDialog(null);setComposer(false)}}window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[])
 useEffect(()=>{const selector=assetIssue?'.cl-asset-issue':error?'.cl-error':mapError?'.cl-loading':panel?'.cl-sheet':dialog?'.cl-dialog':null;if(!selector)return;const region=document.querySelector<HTMLElement>(selector);if(!region)return;const previous=document.activeElement as HTMLElement;const enabled=()=>Array.from(region.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled),select:not(:disabled),[tabindex="0"]')).filter(e=>e.offsetParent!==null);enabled()[0]?.focus();const trap=(e:KeyboardEvent)=>{if(e.key!=='Tab')return;const items=enabled();if(!items.length)return;const i=items.indexOf(document.activeElement as HTMLElement);if(e.shiftKey&&(i<=0)){e.preventDefault();items.at(-1)!.focus()}else if(!e.shiftKey&&(i===items.length-1||i<0)){e.preventDefault();items[0].focus()}};window.addEventListener('keydown',trap);return()=>{window.removeEventListener('keydown',trap);if(previous?.isConnected)previous.focus()}},[panel,dialog,Boolean(error),Boolean(assetIssue),mapError])
 function announce(text:string,recorded=false){setToastArchived(false);setToastRecorded(recorded);setToast(text)}
 useEffect(()=>{if(!toast||dialog||panel||toastFocused)return;const timer=setTimeout(()=>{if(toastRecorded&&!toastArchived)setToastArchived(true);else setToast('')},toastArchived?1600:2600);return()=>clearTimeout(timer)},[toast,toastRecorded,toastArchived,dialog,panel,toastFocused])
 function showDialogue(id:EntityId,text:string){setDialog(id);setResult(text);setPageIndex(0);setComposer(false)}
 async function act(id:EntityId,free=false,actionOverride?:string,retryDraft?:ActionDraft){const current=headRef.current;if(!current||busyRef.current||assetIssueRef.current&&!retryDraft)return;const draft=retryDraft??{headId:current.id,version:current.version,target:id,free,action:free?undefined:actionOverride??nextAction(current.save,id),text:input,mode,position:{...posRef.current}};if(draft.headId!==current.id||draft.version!==current.version){setAssetIssue(null);announce(t('进度已变化，请在当前场景重新选择行动。','Progress has changed. Choose your action again in the current scene.'));return}busyRef.current=true;setBusy(true);getSpace()?.pause(true);setError('');setFallback(false);try{await prepareSceneAction(readiness,current.save,id,draft.action,Boolean(retryDraft));setAssetIssue(null);const r=await sendAction(current,{target:id,position:draft.position,type:free?'free-input':'action',...(free?{text:draft.text,mode:draft.mode}:{action:draft.action})});receive(r.head);if(r.kind==='recovered'){setDialog(null);setInput('');announce(t('已恢复最新进度，请根据当前场景继续。','Latest progress restored. Continue from the current scene.'));return}setInput('');setFallback(Boolean(r.trace?.fallback));setFallbackReason(r.trace?.reason??'');if(currentScene(r.head.save)!==currentScene(current.save)){announce(actionFeedback(r.actionId,locale)??r.text,r.accepted)}else if(free||['set-beacon','release-guidance'].includes(r.actionId)||['lin','zhou-yu','record','radio','cabinet','callpoint'].includes(id)||!r.accepted){showDialogue(id,r.text);const feedback=r.accepted&&actionFeedback(r.actionId,locale);if(feedback)announce(feedback,true)}else announce(actionFeedback(r.actionId,locale)??r.text,r.accepted);if(r.accepted)sound(r.actionId)}catch(e){if(e instanceof ScenePreparationError){console.warn('[scene-resource]',e.scene,e.reason);setAssetIssue(draft);}else setError(versionError(e)?versionMessage():t('结果还没有确认。请恢复这次操作，不要重复提交。','The outcome is not confirmed. Recover this action before submitting again.'))}finally{busyRef.current=false;setBusy(false)}}
 function interact(id:EntityId){if(!headRef.current||assetIssueRef.current||switchingRef.current||busyRef.current||dialogRef.current||panelRef.current||hasPending())return;const perform=()=>{const h=headRef.current!;const f=h.save.facts;if(id==='zhou-yu'&&['offered','accepted','delivered'].includes(activeRelay(h.save)?.phase??'')||id==='cabinet'||id==='radio'||id==='callpoint'||id==='lin'&&f.introduced||id==='panel'&&f.repaired&&!(f.signal_acknowledged&&!f.rescue_sent)||id==='supply'&&f.battery_taken||id==='record'&&f.record_read)showDialogue(id,describe(id));else void act(id)};const entity=entities[id];if(Math.hypot(posRef.current.x-entity.x,posRef.current.y-entity.y)<50)perform();else if(!getSpace()?.walkTo(approachPoints[id],perform))announce(t('这里走不过去，沿过道再靠近一些。','Follow the aisle to get closer.'))}
 interactRef.current=interact
 const choosingPower=dialog==='radio'&&Boolean(s?.facts.battery_installed)&&!s?.facts.power_chosen&&!s?.facts.signal_acknowledged&&!s?.facts.rescue_sent&&!composer
 const pages=choosingPower?['']:dialoguePages(result,locale)
 function advance(){if(composer)return;if(pageIndex<pages.length-1)setPageIndex(pageIndex+1);else setDialog(null)}
 advanceRef.current=advance
 async function reconcile(){if(busyRef.current)return;busyRef.current=true;setBusy(true);try{const r=await recover();if(r){receive(r.head);if(r.kind==='recovered')setDialog(null);if(r.text){setResult(r.text);setPageIndex(0);if(['send-signal','meet-dispatch'].includes(r.actionId))setDialog('radio');if(r.actionId==='meet-attendant')setDialog('zhou-yu');announce(actionFeedback(r.actionId,locale)??r.text,Boolean(r.accepted))}}setError('');setVersionIssue(false)}catch(e){setError(versionError(e)?versionMessage():t('暂时还无法确认，请稍后再恢复。','Still unable to confirm. Please recover again shortly.'))}finally{setBusy(false)}}
 function moveStick(e:React.PointerEvent){if(e.type==='pointerdown'){e.currentTarget.setPointerCapture(e.pointerId);sound('tap')}if(!e.currentTarget.hasPointerCapture(e.pointerId))return;const rect=e.currentTarget.getBoundingClientRect();let x=e.clientX-rect.left-rect.width/2,y=e.clientY-rect.top-rect.height/2;const d=Math.hypot(x,y);if(d>28){x=x/d*28;y=y/d*28}setStick({x,y});getSpace()?.move(x/28,y/28)}
 function stopStick(){setStick({x:0,y:0});getSpace()?.move(0,0)}
 const availableLabel=(id:EntityId)=>['lin','zhou-yu'].includes(id)?t('交谈','Talk'):['cabinet','radio','callpoint'].includes(id)?t('查看','Examine'):id==='panel'?t(s?.facts.signal_acknowledged&&!s?.facts.rescue_sent?'设置引导灯':s?.facts.repaired?'查看':'安装',s?.facts.signal_acknowledged&&!s?.facts.rescue_sent?'Set guide light':s?.facts.repaired?'Examine':'Install'):id==='supply'?t(s?.facts.battery_taken?'查看':s?.facts.supply_open?'取出':'打开',s?.facts.battery_taken?'Examine':s?.facts.supply_open?'Collect':'Open'):id==='record'?t('阅读','Read'):t('通行','Go through')
 const objective=objectiveCopy(s,locale)
 const detail=dialog==='cabinet'||dialog==='radio'
 const name=(id:EntityId)=>id==='zhou-yu'&&s?.facts.attendant_introduced?attendantName(locale):id==='lin'&&s?.facts.introduced?t('林','Lin'):entities[id].label[locale==='zh'?0:1]
 return <main className={"cl-app"+(dialog?" cl-app--dialog":"")+(detail?" cl-app--detail":"")+(isArtDemo?" cl-app--art-demo":"")} data-art-variant={isBalancedArt?'balanced':'baseline'}>
  <header className="cl-header"><div><span className="cl-eyebrow">{scenes[scene].label[locale==='zh'?0:1]}{isArtDemo&&(isBalancedArt?t(' · B 俯视',' · B art'):t(' · A 原版',' · A art'))}</span><h1>{t('留一盏灯','A light left on')}</h1></div><nav aria-label={t('旅程导航','Journey navigation')}>{isArtDemo&&<button className="cl-icon cl-art-demo" aria-label={isBalancedArt?t('切换原版','Show original'):t('切换 B','Show B')} disabled={busy||switching||Boolean(dialog)||Boolean(panel)} onClick={()=>void switchArt()}><span>{isBalancedArt?t('换原版','To A'):t('换 B','To B')}</span></button>}<button className="cl-icon" aria-label={t('随身物品','Inventory')} disabled={busy||switching||Boolean(dialog)||Boolean(assetIssue)} onClick={()=>open('bag')}><Icon name="bag"/>{s?.inventory.some(i=>i.count>0)&&<i className="cl-notice"/>}</button><button className="cl-icon" aria-label={t('旅程菜单','Journey menu')} disabled={busy||switching||Boolean(dialog)||Boolean(assetIssue)} onClick={()=>open('menu')}><Icon name="menu"/></button></nav></header>
  <button className="cl-goal" aria-label={t('查看当前目标','View current objective')} aria-expanded={panel==='objective'||panel==='chapter'} disabled={busy||switching||Boolean(dialog)||Boolean(assetIssue)} onClick={()=>open(s?.facts.journey_complete?'chapter':'objective')}><span className="cl-goal__copy">{objective[0]}</span><Icon name="chevron"/></button>
  <section data-lighting={scene==='carriage'&&s?.facts.power_radio&&!s?.facts.guidance_released?'emergency':s?.facts.repaired?'full':'dim'} className={'cl-world '+(s?.facts.repaired?'cl-world--lit':'')+(scene==='carriage'&&s?.facts.power_radio&&!s?.facts.guidance_released?' cl-world--emergency':'')} aria-label={t('可探索的车厢地图','Explorable carriage map')}>
   <div ref={mapFrame} className="cl-map-frame" data-scene={scene} onDoubleClick={e=>e.preventDefault()} onClick={e=>{if((e.target as HTMLElement).closest('button')||dialog||panel||busy||switching||assetIssue)return;const r=e.currentTarget.getBoundingClientRect();setToast('');if(!getSpace()?.walkTo({x:(e.clientX-r.left)/r.width*384-4.5,y:(e.clientY-r.top)/r.height*576-15}))announce(t('这里走不过去，请点一下过道。','That path is blocked. Try the aisle.'))}}>
    {readiness.background(scene)&&<img className="cl-backdrop" src={readiness.background(scene)} alt="" draggable={false}/>}
    {s&&<WorldArt scene={scene} save={s}/>}
    {scene==='carriage'&&s?.facts.beacon_set&&!s?.facts.guidance_released&&<div className="cl-guide-light" data-guide-light="on" role="img" aria-label={t('连接门引导灯已开启','Connecting-door guide light is on')}/>}
    {destination&&<div className="cl-destination" aria-hidden="true" style={{left:(destination.x+4.5)/384*100+'%',top:(destination.y+15)/576*100+'%'}}><svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="9"/><circle cx="12" cy="12" r="1.5" fill="currentColor" stroke="none"/></svg></div>}
    <div id="rpg"/>
    {s&&sceneEntities(scene).map(id=><button key={id} aria-label={name(id)} data-entity={id} data-state={states(s)[id]} className={'cl-hotspot cl-hotspot--'+id+(target===id?' cl-hotspot--near':'')} style={{left:entities[id].x/384*100+'%',top:(entities[id].y-(['lin','zhou-yu'].includes(id)?16:['exit','forward'].includes(id)?0:['back','cabBack'].includes(id)?-14:id==='radio'?44:20))/576*100+'%'}} onClick={()=>interact(id)}><span>{name(id)}</span><i/></button>)}
    {(!ready||!head||switching)&&<div className="cl-loading"><div className="cl-loading__content">{mapError?(mapReload?t('地图没有完成加载。重新载入页面后恢复同一旅程。','The map did not finish loading. Reload the page to recover this journey.'):t('场景还未准备好。旅程进度已保留，请重试加载。','The scene is not ready. Your progress is preserved. Retry loading.')):error||t('沿着灯光前行…','Following the lights…')}{mapError&&<button onClick={()=>mapReload?location.reload():setSceneRetry(n=>n+1)}>{mapReload?t('重新载入地图并恢复','Reload map and recover'):t('重试加载场景','Retry scene loading')}</button>}{error&&<button onClick={()=>versionIssue?location.reload():void init()}>{versionIssue?t('刷新并继续','Refresh and continue'):t('重试','Retry')}</button>}</div></div>}
   </div>
   {toast&&!dialog&&!panel&&<div className={'cl-toast'+(toastRecorded?' cl-toast--recorded':'')} role="status" onFocus={()=>setToastFocused(true)} onBlur={()=>setToastFocused(false)}><Icon name={toastRecorded?'check':'route'}/><span>{toastArchived?t('已记入旅途记录','Saved to your journal'):toast}</span>{toastRecorded&&<button aria-label={t('查看这次记录','Read this journal entry')} onClick={()=>open('log')}><Icon name="log"/></button>}</div>}
   {dialog&&!assetIssue&&<section className={"cl-dialog"+(detail?" cl-dialog--detail":"")} role="dialog" aria-modal="true" aria-label={detail?t("物件特写","Object close-up"):t("车厢对白","Carriage dialogue")}><header><strong>{dialog==='lin'?t('灰衣修理工','Mechanic in grey'):name(dialog)}</strong><button className="cl-icon" aria-label={t('返回地图','Back to map')} disabled={busy} onClick={()=>{setDialog(null);setComposer(false)}}><Icon name="close"/></button></header>{detail&&s&&!composer&&<div className={'cl-detail-art cl-detail-art--'+dialog} data-detail={dialog} data-detail-state={states(s)[dialog!]}><span className="cl-detail-kicker">{t('近处观察','A closer look')}</span>{dialog==='cabinet'?<PropArt state={visualStates.cabinet[states(s).cabinet]}/>:<ExtraArt state={visualStates.radio[states(s).radio]}/>}<span className="cl-detail-state">{dialog==='cabinet'?t(s.facts.fuse_taken?'保险丝已取走':s.facts.cabinet_open?'备用保险丝 · 1 枚':'柜门关闭',s.facts.fuse_taken?'Fuse collected':s.facts.cabinet_open?'Spare fuse · 1':'Cabinet closed'):radioStatus(s,locale)}</span></div>}{!choosingPower&&<p className="cl-prose" aria-live="polite" tabIndex={0}>{pages[pageIndex]}</p>}{fallback&&<p className="cl-help">{fallbackReason==='rate-limit'?t('在线对话暂时繁忙，已使用预设回应；稍后可再试。','Online conversation is busy. An authored reply is shown; try again shortly.'):t('在线回答暂不可用，已使用预设回应。','The online reply is unavailable. An authored reply is shown.')}</p>}
   {detail&&s&&!composer&&((dialog==='cabinet'&&!s.facts.fuse_taken)||(dialog==='radio'&&!s.facts.battery_installed))&&<button className="cl-detail-action" disabled={busy||Boolean(error)} onClick={()=>void act(dialog!)}>{busy?t('处理中…','Working…'):actionLabel(nextAction(s,dialog!),locale)}<Icon name="arrow"/></button>}
   {dialog==='radio'&&s&&!composer&&<PowerChoice save={s} locale={locale} disabled={busy||Boolean(error)} onChoose={a=>void act('radio',false,a)}/>}
   {s&&!composer&&pageIndex===pages.length-1&&<ReceptionActions save={s} target={dialog} locale={locale} disabled={busy||Boolean(error)} onAction={a=>void act(dialog!,false,a)}/>}
   {dialog==='radio'&&s&&!composer&&<RadioContact save={s} locale={locale} disabled={busy||Boolean(error)} onAction={a=>void act('radio',false,a)}/>}
   {dialog==='radio'&&s?.facts.signal_acknowledged&&!composer&&<p className="cl-power-lock">{s.facts.power_chosen?t('回执已确认 · 供电路线已锁定','Acknowledged · Power route locked'):t('旧旅程已完成 · 原进度保留','Earlier journey complete · Progress preserved')}</p>}
   {dialog==='radio'&&s?.facts.battery_installed&&s.facts.power_chosen&&!s.facts.signal_acknowledged&&!s.facts.rescue_sent&&!composer&&<div className="cl-channels" aria-label={t('电台频道','Radio channels')}><button disabled={busy||Boolean(error)} onClick={()=>void act('radio',false,'call-yard')}>{t('1 频道 · 呼叫','Channel 1 · Call')}</button><button disabled={busy||Boolean(error)} onClick={()=>void act('radio',false,'send-signal')}>{t('3 频道 · 呼叫','Channel 3 · Call')}</button></div>}
   {composer?<form onSubmit={e=>{e.preventDefault();void act(dialog,true)}}><label htmlFor="cl-free">{t('说点什么，或尝试其他行动','Say something or try another action')}</label><div className="cl-composer"><input id="cl-free" value={input} maxLength={500} onChange={e=>setInput(e.target.value)} autoFocus disabled={busy}/><button aria-label={t('发送想法','Send idea')} disabled={busy||!input.trim()||Boolean(error)}><Icon name="arrow"/></button></div></form>:<footer><button onClick={()=>setComposer(true)}>{t('说点什么','Say something')}</button><button className="cl-next" aria-label={pageIndex<pages.length-1?t('继续','Continue'):t('返回地图','Back to map')} onClick={advance}>{pages.length>1&&<small className="cl-page-count">{pageIndex+1}/{pages.length}</small>}{pageIndex<pages.length-1?t('继续','Continue'):t('返回地图','Back to map')}<Icon name="arrow"/></button></footer>}
   {s?.facts.rescue_sent&&['radio','panel','callpoint'].includes(dialog)&&!composer&&<button className="cl-chapter-entry" onClick={()=>{setDialog(null);open('chapter')}}>{s?.facts.journey_complete?t('回顾旅程结局','Review journey ending'):t('查看本章结果','View chapter result')}<Icon name="arrow"/></button>}
   </section>}
  </section>
  <footer className="cl-controls"><div className="cl-joystick" ref={joystick} onPointerDown={moveStick} onPointerMove={moveStick} onPointerUp={stopStick} onPointerCancel={stopStick} onLostPointerCapture={stopStick} role="group" aria-label={t('移动摇杆','Movement joystick')}><span className="cl-joystick__knob" style={{transform:`translate(${stick.x}px,${stick.y}px)`}}><Icon name="move"/></span></div><p className="cl-controls__hint">{t('点地面行走','Click the floor to walk')}<small>{t('方向键 / WASD · E 互动','Arrows / WASD · E to interact')}</small></p><button className="cl-interact" disabled={!target||!ready||switching||busy||Boolean(panel)||Boolean(dialog)||Boolean(error)||Boolean(assetIssue)} onPointerDown={()=>target&&interact(target)}>{busy?t('处理中…','Working…'):target&&s?availableLabel(target):t('走近物件','Move closer')}<Icon name="arrow"/></button></footer>
  {panel&&<div className="cl-scrim"><section className={"cl-sheet"+(panel==='chapter'?" cl-sheet--chapter":"")} role="dialog" aria-modal="true" aria-label={t('旅途面板','Journey panel')}><header>{['route','log','settings','people','chapter','promise'].includes(panel)&&<button className="cl-icon" aria-label={t('返回菜单','Back to menu')} onClick={()=>open('menu')}><Icon name="back"/></button>}<h2>{panel==='chapter'?(s?.facts.journey_complete?t('旅程完成','Journey complete'):t('本章完成','Chapter complete')):panel==='promise'?t('一路上的约定','Promises on the way'):panel==='people'?t('认识的人','People met'):panel==='menu'?t('旅程菜单','Journey menu'):panel==='objective'?t('当前目标','Current objective'):panel==='bag'?t('随身物品','Your belongings'):panel==='log'?t('旅途记录','Journey notes'):panel==='route'?t('旅程路线','Journey route'):t('这段旅程','Your journey')}</h2><button className="cl-icon" aria-label={t('返回地图','Back to map')} disabled={busy} onClick={()=>open(null)}><Icon name="close"/></button></header><div className="cl-sheet__scroll" tabIndex={0}>
   {panel==='menu'?<><div className="cl-menu-links">{isCloudEdition&&<button disabled={busy||hasPending()} onClick={()=>void openFullStory()}><Icon name="route"/><span>{t('完整单人旅程','Full single-player journey')}</span><Icon name="arrow"/></button>}{s?.facts.rescue_sent&&<button aria-label={t('本章结果','Chapter result')} onClick={()=>open('chapter')}><Icon name="check"/><span>{t('本章结果','Chapter result')}<small>{t('回顾选择与留下的变化','Revisit your choice and its consequences')}</small></span><Icon name="arrow"/></button>}<button aria-label={t('旅程路线','Journey route')} onClick={()=>open('route')}><Icon name="route"/><span>{t('旅程路线','Journey route')}<small>{t('查看走过的车厢','See the places you have visited')}</small></span><Icon name="arrow"/></button><button aria-label={t('旅途记录','Journal')} onClick={()=>open('log')}><Icon name="log"/><span>{t('旅途记录','Journal')}<small>{t('重读线索与发生的事','Revisit clues and events')}</small></span><Icon name="arrow"/></button>{s&&activeRelay(s)&&<button aria-label={t('一路上的约定','Promises on the way')} onClick={()=>open('promise')}><Icon name="log"/><span>{t('一路上的约定','Promises on the way')}<small>{relaySummary(s,locale)?.[0]}</small></span><Icon name="arrow"/></button>}<button aria-label={t('认识的人','People met')} onClick={()=>open('people')}><Icon name="log"/><span>{t('认识的人','People met')}<small>{t('记下相遇与联络','Remember meetings and contacts')}</small></span><Icon name="arrow"/></button><button aria-label={t('设置','Settings')} onClick={()=>open('settings')}><Icon name="menu"/><span>{t('设置','Settings')}<small>{t('语言、声音与新旅程','Language, sound and a new journey')}</small></span><Icon name="arrow"/></button></div>{isUiDemo&&<p className="cl-help">{t('这是独立的演示旅程，不影响原旅程进度。','This demo has its own progress and does not affect your original journey.')}</p>}</>:panel==='objective'?<><p className="cl-objective-title">{objective[0]}</p><p>{objective[1]}</p><button className="cl-primary" onClick={()=>open(null)}>{t('继续探索','Keep exploring')}</button></>:panel==='bag'?<>{s?.inventory.filter(i=>i.count>0).length?s.inventory.filter(i=>i.count>0).map(i=><article className="cl-item" key={i.id}>{i.id==='battery'?<ExtraArt state="battery"/>:<PropArt state="fuse"/>}<div><h3>{i.label} ×{i.count}</h3><p>{i.detail}</p></div></article>):<p>{t('随身袋里还没有物品。','Your bag is empty.')}</p>}<div className="cl-stats">{s&&cartridge(locale).statDefinitions.map(d=><p key={d.id}>{d.label}<b>{s.stats[d.id]}/{d.max}</b></p>)}</div></>:
   panel==='promise'?s&&activeRelay(s)&&<><p className="cl-objective-title">{relaySummary(s,locale)?.[0]}</p><p>{relaySummary(s,locale)?.[1]}</p><blockquote className="cl-promise-message">{relayMessage(activeRelay(s)!.plan,locale)}</blockquote><p className="cl-help">{t('这是一项可选的约定，不影响主线进度。','This is an optional promise and does not gate the main journey.')}</p></>:panel==='chapter'?s&&<ChapterResult save={s} locale={locale}>{isCloudEdition&&journalImageAvailable(import.meta.env.MODE)&&s.facts.journey_complete&&<JournalImagePanel key={head!.id} journeyId={head!.id} locale={locale}/>}</ChapterResult>:panel==='people'?s&&<PeopleMet save={s} locale={locale}/>:panel==='route'?<><ol className="cl-route">{sceneIds.map(id=>{const visited=s?.map.find(m=>m.id===id)?.visited;return <li key={id} aria-current={scene===id?'location':undefined}><span>{visited?scenes[id].label[locale==='zh'?0:1]:t('尚未抵达','Not yet visited')}</span><small>{scene===id?t('所在位置','You are here'):visited?t('已到访','Visited'):t('沿连接门前行','Follow connecting doors')}</small></li>})}</ol><p className="cl-help">{t('走到连接门旁互动，即可前往相邻区域。','Walk to a connecting door to enter the adjacent area.')}</p></>:
   panel==='log'?s?.blocks.filter(b=>b.kind!=='image'&&b.kind!=='choices').map((b,i)=><p className="cl-entry" key={b.id+'-'+i}>{b.text}</p>):<><label className="cl-setting">{t('自由对话','Free conversation')}<select value={mode} onChange={e=>{const m=e.target.value as typeof mode;setMode(m);writeLocal(NARRATION_POLICY.modeKey,m)}}><option value="local">{t('预设回应','Authored responses')}</option>{!isBrowserEdition&&<option value="live">{t('在线对话','Online conversation')}</option>}</select></label><p className="cl-help">{isCloudEdition?t('云端旅程 · 操作由服务保存。','Cloud journey · Actions are saved by the service.'):isBrowserEdition?t('手机测试版 · 进度只保存在此浏览器。自由对话使用预设回应，在线 AI 扩写未开启。','Mobile test edition · Progress stays in this browser. Conversation uses authored responses; online AI is off.'):t('模型扩展使用现有 AlterU 叙事服务，旅程保存在本机。','Model expansion uses the existing AlterU story service. This journey is saved locally.')}</p>{!isBrowserEdition&&<p className="cl-help">{t('选择在线对话后，本次输入、当前场景和与当前人物最近最多4个回合会发送到 AlterU 叙事服务。不会发送整份旅程或其他人物的对话。按钮行动仍直接执行规则，可随时切回预设回应。','Online conversation sends your current input, current scene and up to four recent turns with this speaker to the AlterU story service. It does not send the full journey or other conversations. Buttons still use game rules; you can switch back at any time.')}</p>}{isCloudEdition&&<a className="cl-setting" href="https://yinxinghuan.github.io/rpgjs-story-lab/?story_runtime=legacy">{t('打开手机测试版旧旅程','Open the previous mobile journey')}</a>}<button className="cl-setting" onClick={()=>setMuted(!muted)}>{t('声音','Sound')}<span>{muted?t('关闭','Off'):t('开启','On')}</span></button><label className="cl-setting">Language<select value={locale} onChange={e=>{const l=e.target.value as Locale;setLocale(l);writeLocal('locale',l)}}><option value="zh">中文</option><option value="en">English</option></select></label><button className="cl-secondary" onClick={()=>setRestartConfirm(!restartConfirm)}>{t('开始新旅程','Start a new journey')}</button>{restartConfirm&&<div className="cl-confirm"><p>{isCloudEdition?t('开始新的云端旅程？当前旅程仍保留在服务中。','Start a new cloud journey? Your current journey remains in the service.'):isBrowserEdition?t('重新从车厢出发？将开始新存档，不再自动续玩当前旅程。','Start a new save? The current journey will no longer resume automatically.'):t('重新从车厢出发？旧旅程仍保存在本地服务。','Start again? The old journey remains in the local service.')}</p><button className="cl-primary" onClick={()=>{setRestartConfirm(false);setDialog(null);open(null);void init(true)}}>{t('确认新旅程','Confirm new journey')}</button></div>}</>}
   </div>{panel==='chapter'&&s?.facts.rescue_sent&&<footer className="cl-chapter-footer"><button className="cl-primary" onClick={()=>open(null)}>{t('继续探索','Keep exploring')}</button><div className="cl-chapter__links"><button onClick={()=>open('log')}>{t('旅途记录','Journal')}</button><button onClick={()=>open('people')}>{t('认识的人','People met')}</button></div></footer>}</section></div>}
  {assetIssue&&<aside className="cl-error cl-asset-issue" role="alertdialog" aria-modal="true" aria-label={t('下一场景暂不可用','Next scene unavailable')}><p>{t('下一场景还未准备好。你仍在原处，这次行动尚未提交。','The next scene is not ready. You remain here; this action has not been submitted.')}</p><button disabled={busy} onClick={()=>void act(assetIssue.target,assetIssue.free,assetIssue.action,assetIssue)}>{busy?t('正在准备…','Preparing…'):t('重试原行动','Retry original action')}</button><button disabled={busy} onClick={()=>setAssetIssue(null)}>{t('留在这里','Stay here')}</button></aside>}
  {error&&head&&<aside className="cl-error" role="alert"><p>{error}</p><button disabled={busy} onClick={()=>versionIssue?location.reload():void reconcile()}>{versionIssue?t('刷新并继续','Refresh and continue'):t('恢复这次操作','Recover this action')}</button></aside>}
 </main>
}
function MirrorEntry(){const locale:Locale=navigator.language.startsWith('zh')?'zh':'en';const t=(zh:string,en:string)=>tr(locale,zh,en);return <main className="cl-app" style={{justifyContent:'center'}}><section className="cl-sheet"><h1>{t('留一盏灯','A light left on')}</h1><p>{t('云端旅程在主站继续。以前在此浏览器的手机测试进度，也可以单独打开。','Continue your cloud journey on the main site, or open the previous mobile save in this browser.')}</p><button className="cl-primary" onClick={()=>location.assign('https://game.aiwaves.tech'+getGameApiBase()+'/')}>{t('前往云端旅程','Continue on the main site')}</button><button className="cl-secondary" onClick={()=>{const url=new URL(location.href);url.searchParams.set('story_runtime','legacy');location.assign(url.href)}}>{t('打开旧手机测试进度','Open the previous mobile save')}</button></section></main>}
const root=createRoot(document.getElementById('root')!)
function OriginalBoot({failed=false}:{failed?:boolean}){const zh=navigator.language.startsWith('zh');return <main className="cl-app" style={{justifyContent:'center'}}><section className="cl-sheet" role={failed?'alert':'status'}><p>{failed?(zh?'旅程页面暂时未能下载。重新载入后继续，已有进度会保留。':'The journey page could not download. Reload to continue; existing progress is preserved.'):(zh?'正在载入旅程…':'Loading your journey…')}</p>{failed&&<button className="cl-primary" onClick={()=>location.reload()}>{zh?'重新载入旅程':'Reload journey'}</button>}</section></main>}
if(originalEntry(import.meta.env.MODE,location.hostname,location.search)){root.render(<OriginalBoot/>);void import('./original-game').then(({default:Game})=>root.render(<Game/>),()=>root.render(<OriginalBoot failed/>))}else if(import.meta.env.MODE==='cloud-preflight'&&new URLSearchParams(location.search).get('create_art')==='north-cape'){void import('./art-creator').then(({default:Creator})=>root.render(<Creator/>))}else if(import.meta.env.MODE==='cloud-preflight'&&new URLSearchParams(location.search).get('scene_preview')==='north-cape'){void import('./original-scene-preview').then(({default:Preview})=>root.render(<Preview/>))}else root.render(isMirrorEdition?<MirrorEntry/>:<App/>)
