import JourneyLoading from './journey-loading'
import OriginalSceneSilhouette from './original-scene-silhouette'
import {ProgressiveSceneReadiness} from './progressive-scene-readiness'
import MovementJoystick from './movement-joystick'
import {BrakeDetail} from './original-brake-detail'
import {brakeArt,originalBrakeSheet} from './original-brake-art'
import {originalBrakeState} from './original-equipment-state'
import {fanArt,originalFanSheets,originalFanState} from './original-fan-art'
import {inspectOriginalDirectory,type OriginalJourneyEntry} from './original-session-client'
import {rendererNeedsPageReload} from './renderer-transition'
import {originalWorldWalkable,originalWorldSafePosition} from './original-world-space'
import {originalFanResources,originalBoundFanSheets,originalEquipmentResource,originalEquipmentHasArt,originalEquipmentAnimation,originalStarterSheet,originalEquipmentSlots} from './original-equipment-art'
import {Assets} from 'pixi.js'
import {inspectSpritePng} from './sprite-draft'
import {decodeSpritePixels} from './sprite-browser-io'
import {verifyPublishedActorPixels,verifyPublishedHeroPixels} from './sprite-map-candidate'
import {verifyPublishedDevicePixels} from './device-map-candidate'
import type {RpgPlayer} from '@rpgjs/server'
import {originalActorResource,originalActorDirection,originalCharacterHasArt,originalFixedStandingArt,originalFixedStandingSheet,originalStandingSheet,originalCharacterArtSlots,originalCharacterArtAnimation} from './original-character-art'
import React,{useEffect,useLayoutEffect,useRef,useState} from 'react'
import {createRpgRenderer,type RpgRendererRuntime,type RendererPoint} from './rpg-renderer'
import {originalHeroSheet} from './original-hero-sheet'
import {originalPublishedHero} from './original-asset-releases'
import {originalBoundHero} from './original-bound-hero'
import {findGridPath} from './grid-path'
import {originalTrainChapterSpatialPlan} from './original-train-spatial-plan'
import {ScenePreparationError,loadBrowserSceneResource,type SceneResourceManifest} from './scene-readiness'
import {originalSessionHttp} from './original-session-http'
import {originalGameEntities,originalReadingBlocks,originalGameObjective,originalActionDestinations} from './original-game-projection'
import {originalPlaceLabel} from './original-place-presentation'
import {originalBoundSceneResources,originalBackgroundVersion,originalEnvironmentVersion,originalRendererMapIds,originalActorRelease,originalStarterRelease} from './original-asset-releases'
import type {OriginalHead} from '../server/original-train-runtime'
import OriginalIllustrationPanel from './original-illustration-panel'
import './original-game.css'
declare const __ORIGINAL_STORY_PREVIEW__:SceneResourceManifest|null
const world=originalTrainChapterSpatialPlan()
type Entity=ReturnType<typeof originalGameEntities>[number]
type Panel='nearby'|'log'|'bag'|'people'|'ending'|'action'|'journeys'|'pictures'|null
/** One authority and renderer for the released single-player story. */
export default function OriginalGame(){
 const [connection]=useState(()=>originalSessionHttp(window.alteruLocalStorage,async(name,work)=>{if(!navigator.locks)throw Error('CLOUD_LOCKS_UNAVAILABLE');return navigator.locks.request(name,work)},undefined,undefined,async plan=>{await loaderFor(plan).prepare(plan.destinationScene,true)},new URLSearchParams(location.search).get('background_release')??undefined,new URLSearchParams(location.search).get('device_release')??undefined,new URLSearchParams(location.search).get('actor_release')??undefined,new URLSearchParams(location.search).get('fan_release')??undefined,new URLSearchParams(location.search).get('hero_release')??undefined))
 const loaders=useRef(new Map<string,ProgressiveSceneReadiness>())
 function loaderFor(h:Pick<OriginalHead,'assets'>){const id=originalEnvironmentVersion(h.assets);let loader=loaders.current.get(id);if(!loader){loader=new ProgressiveSceneReadiness(originalBoundSceneResources(__ORIGINAL_STORY_PREVIEW__!,h.assets),loadBrowserSceneResource,()=>{if(mounted.current)setArtRevision(n=>n+1)});loaders.current.set(id,loader)}return loader}
 const [head,setHead]=useState<OriginalHead|null>(null),headRef=useRef(head);headRef.current=head
 const [position,setPosition]=useState<RendererPoint>({x:192,y:430}),pos=useRef(position);pos.current=position
 const [,setArtRevision]=useState(0),[loadingStage,setLoadingStage]=useState<'connecting'|'map'|'people'>('connecting')
 const [destination,setDestination]=useState<RendererPoint|null>(null),[ready,setReady]=useState(false),[busy,setBusy]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[input,setInput]=useState(''),[panel,setPanel]=useState<Panel>(null),[selected,setSelected]=useState<string|null>(null)
 const [backup,setBackup]=useState<{url:string;name:string;version:number}|null>(null)
 useEffect(()=>()=>{if(backup)URL.revokeObjectURL(backup.url)},[backup])
 const [journeys,setJourneys]=useState<OriginalJourneyEntry[]>([]),[journeyError,setJourneyError]=useState('')
 const [talk,setTalk]=useState(false),[onlineTalk,setOnlineTalk]=useState(false),[onlineAvailable,setOnlineAvailable]=useState(false),[onlineActionAvailable,setOnlineActionAvailable]=useState(false)
 const [illustrationsAvailable,setIllustrationsAvailable]=useState(false)
 const heroBlob=useRef(''),heroKey=useRef('')
 async function prepareHero(h:OriginalHead){
  const {id:version,resource}=originalBoundHero(h.assets)
  if(heroBlob.current){if(heroKey.current!==version)throw new ScenePreparationError('characters','HERO_VERSION_CHANGED');return}
  const abort=new AbortController(),timer=setTimeout(()=>abort.abort(),30000);let blob=''
  try{blob=(await loadBrowserSceneResource(resource,abort.signal))!;const release=originalPublishedHero(h.assets);if(release){const png=await inspectSpritePng(new Uint8Array(await (await fetch(blob,{signal:abort.signal})).arrayBuffer()));await verifyPublishedHeroPixels(release,png,decodeSpritePixels)}const texture=await Assets.load({src:blob,parser:'loadTextures'});if(texture?.width!==resource.width||texture?.height!==resource.height)throw Error('RESOURCE_DECODE');if(!mounted.current){void Assets.unload(blob).catch(()=>{});URL.revokeObjectURL(blob);return}heroBlob.current=blob;heroKey.current=version}
  catch{if(blob)URL.revokeObjectURL(blob);throw new ScenePreparationError('characters','HERO_ART_UNAVAILABLE')}finally{clearTimeout(timer);abort.abort()}
 }
 const brakeBlob=useRef('')
 const fanBlobs=useRef(new Map<string,string>()),fanElapsed=useRef(0)
 const equipmentBlob=useRef(''),equipmentKey=useRef(''),equipmentEvents=useRef(new Map<string,{event:RpgPlayer;layer:string}>())
 function projectEquipment(){const h=headRef.current;if(!h)return;for(const {event,layer} of equipmentEvents.current.values()){const animation=originalEquipmentAnimation(h.save,layer,fanElapsed.current,h.assets);if(event.animationName()!==animation){event.animationName.set(animation);event.syncChanges()}}}
 async function prepareEquipment(h:OriginalHead){
  if(originalEquipmentHasArt('brakes',h.assets)&&!brakeBlob.current){
   const abort=new AbortController(),timer=setTimeout(()=>abort.abort(),30000);let blob=''
   try{blob=(await loadBrowserSceneResource(brakeArt.resource,abort.signal))!;const texture=await Assets.load({src:blob,parser:'loadTextures'});if(texture?.width!==912||texture?.height!==640)throw Error('RESOURCE_DECODE');brakeBlob.current=blob}catch{if(blob)URL.revokeObjectURL(blob);throw new ScenePreparationError('equipment','BRAKE_ART_UNAVAILABLE')}finally{clearTimeout(timer);abort.abort()}
  }

  if(originalEquipmentHasArt('tunnel-fan',h.assets))for(const [part,resource]of originalFanResources(h.assets)){
   if(fanBlobs.current.has(part))continue
   const abort=new AbortController(),timer=setTimeout(()=>abort.abort(),30000);let blob=''
   try{blob=(await loadBrowserSceneResource(resource,abort.signal))!;const texture=await Assets.load({src:blob,parser:'loadTextures'});if(texture?.width!==resource.width||texture?.height!==resource.height)throw Error('RESOURCE_DECODE');fanBlobs.current.set(part,blob)}catch{if(blob)URL.revokeObjectURL(blob);throw new ScenePreparationError('equipment','FAN_ART_UNAVAILABLE')}finally{clearTimeout(timer);abort.abort()}
  }
  const resource=originalEquipmentResource(h.assets),key=originalStarterRelease(h.assets)?.id??'baseline'
  if(equipmentBlob.current){if(equipmentKey.current!==key)throw new ScenePreparationError('equipment','EQUIPMENT_VERSION_CHANGED');return}
  const abort=new AbortController(),timer=setTimeout(()=>abort.abort(),30000);let blob=''
  try{blob=(await loadBrowserSceneResource(resource,abort.signal))!
   const release=originalStarterRelease(h.assets);if(release){const png=await inspectSpritePng(new Uint8Array(await (await fetch(blob,{signal:abort.signal})).arrayBuffer()));await verifyPublishedDevicePixels(release,png,decodeSpritePixels)}
   const texture=await Assets.load({src:blob,parser:'loadTextures'});if(texture?.width!==resource.width||texture?.height!==resource.height)throw Error('RESOURCE_DECODE');equipmentBlob.current=blob;equipmentKey.current=key
  }catch{if(blob)URL.revokeObjectURL(blob);throw new ScenePreparationError('equipment','EQUIPMENT_ART_UNAVAILABLE')}finally{clearTimeout(timer);abort.abort()}
 }

 const fixedActorBlobs=useRef(new Map<string,string>())
 const actorBlob=useRef(''),actorKey=useRef(''),actorEvents=useRef(new Map<string,{event:RpgPlayer;characterId:string;position:RendererPoint}>())
 function projectActors(){const h=headRef.current;if(!h)return;for(const {event,characterId,position} of actorEvents.current.values()){const animation=originalCharacterArtAnimation(h.save,characterId,h.assets),direction=originalActorDirection({x:position.x,y:position.y+1},{x:pos.current.x+4.5,y:pos.current.y+15});if(event.animationName()!==animation||event.direction()!==direction){event.animationName.set(animation);event.direction.set(direction);event.syncChanges()}}}
 async function prepareActors(h:OriginalHead){
  for(const a of originalFixedStandingArt(h.assets)){
   if(fixedActorBlobs.current.has(a.graphic))continue
   const abort=new AbortController(),timer=setTimeout(()=>abort.abort(),30000);let blob=''
   try{blob=(await loadBrowserSceneResource(a.resource,abort.signal))!;const texture=await Assets.load({src:blob,parser:'loadTextures'});if(texture?.width!==a.resource.width||texture?.height!==a.resource.height)throw Error('RESOURCE_DECODE');fixedActorBlobs.current.set(a.graphic,blob)}catch{if(blob)URL.revokeObjectURL(blob);throw new ScenePreparationError('characters','CHARACTER_ART_UNAVAILABLE')}finally{clearTimeout(timer);abort.abort()}
  }
  const release=originalActorRelease(h.assets),key=release?.id??'baseline',resource=originalActorResource(h.assets)
  if(actorBlob.current){if(actorKey.current!==key)throw new ScenePreparationError('characters','ACTOR_VERSION_CHANGED');return}
  const abort=new AbortController(),timer=setTimeout(()=>abort.abort(),30000);let blob=''
  try{blob=(await loadBrowserSceneResource(resource,abort.signal))!
   if(release){const png=await inspectSpritePng(new Uint8Array(await (await fetch(blob,{signal:abort.signal})).arrayBuffer()));await verifyPublishedActorPixels(release,png,decodeSpritePixels)}
   const texture=await Assets.load({src:blob,parser:'loadTextures'});if(texture?.width!==resource.width||texture?.height!==resource.height)throw Error('RESOURCE_DECODE');actorBlob.current=blob;actorKey.current=key
  }catch{if(blob)URL.revokeObjectURL(blob);throw new ScenePreparationError('characters','CHARACTER_ART_UNAVAILABLE')}finally{clearTimeout(timer);abort.abort()}
 }

 const runtime=useRef<RpgRendererRuntime|null>(null),frame=useRef<HTMLDivElement>(null),hud=useRef<HTMLElement>(null),footer=useRef<HTMLElement>(null),busyRef=useRef(true),mounted=useRef(true)
 const activeLoader=head?loaders.current.get(originalEnvironmentVersion(head.assets)):undefined,background=head?activeLoader?.background(head.sceneId)??'':'',backgroundState=head?activeLoader?.backgroundState(head.sceneId):undefined
 const scene=head?.sceneId,locale=head?.save.locale??(navigator.language.startsWith('zh')?'zh':'en'),t=(zh:string,en:string)=>locale==='zh'?zh:en
 const versionMismatch=error==='RUNTIME_VERSION_MISMATCH'
 const reloadRequired=versionMismatch||rendererNeedsPageReload(error)||error==='SESSION_SELECTION_CHANGED'
 const errorRef=useRef(error);errorRef.current=error
 const entities=head?originalGameEntities(head):[],entity=entities.find(e=>e.id===selected),save=head?.save
 const setWorking=(v:boolean)=>{busyRef.current=v;setBusy(v)}
 function camera(){const f=frame.current;if(!f)return;const box=f.parentElement!,scale=f.clientWidth/384,top=hud.current?.offsetHeight??100,bottom=footer.current?.offsetHeight??90,space=Math.max(120,box.clientHeight-top-bottom);box.parentElement?.style.setProperty('--og-hud-height',top+'px');f.style.setProperty('--camera-y',Math.min(top,Math.max(box.clientHeight-bottom-f.clientHeight,top+space*.55-(pos.current.y+15)*scale))+'px');f.style.setProperty('--camera-x',Math.min(0,Math.max(box.clientWidth-f.clientWidth,box.clientWidth/2-(pos.current.x+4.5)*scale))+'px')}
 useLayoutEffect(camera,[position.x,position.y,scene,head?.version])
 useEffect(()=>{const o=new ResizeObserver(camera);for(const el of [frame.current,frame.current?.parentElement,hud.current,footer.current])if(el)o.observe(el);return()=>o.disconnect()},[])
 async function restore(next:OriginalHead){
  runtime.current?.pause(true);if(runtime.current?.renderedScene()!==next.sceneId)setReady(false);headRef.current=next;setHead(next)
  setLoadingStage('map');const loader=loaderFor(next);await loader.prepare(next.sceneId,true);setLoadingStage('people');await Promise.all([prepareHero(next),prepareActors(next),prepareEquipment(next)]);if(!mounted.current)return
  if(!runtime.current)await new Promise<void>((resolve,reject)=>{try{createRpgRenderer({host:document.getElementById('rpg')!,width:384,height:576,sceneIds:world.scenes.map(s=>s.id),mapIds:originalRendererMapIds(next.assets),initialScene:next.sceneId,initialPosition:next.position,heroGraphic:'hero',spritesheets:[originalHeroSheet(heroBlob.current,next.assets),...(brakeBlob.current?[originalBrakeSheet(brakeBlob.current)]:[]),originalStandingSheet(actorBlob.current,next.assets),...originalFixedStandingArt(next.assets).map(a=>originalFixedStandingSheet(fixedActorBlobs.current.get(a.graphic)!,a)),originalStarterSheet(equipmentBlob.current,next.assets),...(originalEquipmentHasArt('tunnel-fan',next.assets)?originalBoundFanSheets(fanBlobs.current.get('housing')!,fanBlobs.current.get('rotor')!,next.assets):[])],mapEvents:s=>[...originalCharacterArtSlots(s,next.assets).map(slot=>({id:slot.id,x:slot.x,y:slot.y,event:{onInit(this:RpgPlayer){this.setHitbox(1,1);this.through=true;this.animationFixed=true;this.setGraphic(slot.graphic);this.animationName.set(originalCharacterArtAnimation(headRef.current!.save,slot.characterId,headRef.current!.assets));actorEvents.current.set(slot.id,{event:this,characterId:slot.characterId,position:{x:slot.x,y:slot.y}});this.syncChanges()}}})),...originalEquipmentSlots(s,next.assets).map(slot=>({id:slot.id,x:slot.x,y:slot.y,event:{onInit(this:RpgPlayer){this.setHitbox(1,1);this.through=true;this.animationFixed=true;this.setGraphic(slot.graphic);this.animationName.set(originalEquipmentAnimation(headRef.current!.save,slot.layer,fanElapsed.current,headRef.current!.assets));equipmentEvents.current.set(slot.id,{event:this,layer:slot.layer});this.syncChanges()}}}))],walkable:(p,s)=>originalWorldWalkable({...headRef.current!,sceneId:s},p),safePosition:(p,s)=>originalWorldSafePosition({...headRef.current!,sceneId:s},p),findPath:(a,b,s)=>findGridPath(a,b,p=>originalWorldWalkable({...headRef.current!,sceneId:s},p)),onPosition:p=>{pos.current=p;setPosition(p);projectActors()},onDestination:setDestination,onReady:r=>{runtime.current=r;resolve()}})}catch(e){reject(e)}})
  await runtime.current!.restore(next.position,next.sceneId);projectActors();projectEquipment();if(!mounted.current)return
  loader.activate(next.sceneId);setPosition(runtime.current!.position());setReady(true)
 }
 async function prepareBackup(){
  const h=headRef.current;if(!h||busyRef.current)return;setWorking(true);setJourneyError('');setBackup(null)
  try{if(connection.client.hasPending())throw Error('PENDING_ACTION');const value=await connection.api('/sessions/'+h.id+'/backup'),p=value?.payload,j=p?.tables?.journeys?.[0];if(p?.format!=='original-train-backup-v1'||p.journeyId!==h.id||j?.id!==h.id||typeof value.sha256!=='string')throw Error('INVALID_ORIGINAL_BACKUP');const version=JSON.parse(j.data).version,url=URL.createObjectURL(new Blob([JSON.stringify(value)],{type:'application/json'}));if(!mounted.current){URL.revokeObjectURL(url);return}setBackup({url,name:'last-train-'+h.id+'-v'+version+'.json',version})}
  catch(e){if(e instanceof Error&&e.message==='RUNTIME_VERSION_MISMATCH')setError(e.message);else setJourneyError(e instanceof Error&&e.message==='PENDING_ACTION'?t('请先恢复待确认操作，再下载备份。','Recover the pending action before preparing a backup.'):e instanceof Error&&e.message==='BACKUP_TOO_LARGE'?t('旅程超过单份备份大小限制。服务器进度仍然保留。','This journey exceeds the backup size limit. Server progress is retained.'):t('备份暂未准备好，请重试。服务器进度未改动。','The backup is not ready. Retry; server progress is unchanged.'))}finally{setWorking(false)}
 }
 async function showJourneys(){setPanel('journeys');setWorking(true);setJourneyError('');try{setJourneys(inspectOriginalDirectory(await connection.api('/sessions')))}catch(e){if(e instanceof Error&&e.message==='RUNTIME_VERSION_MISMATCH')setError(e.message);else setJourneyError(t('旅程列表暂时无法加载，请重试。','Journey list could not load. Please retry.'))}finally{setWorking(false)}}
 async function chooseJourney(id?:string,carriage=false){
  setWorking(true);setJourneyError('');runtime.current?.pause(true)
  try{
   if(connection.client.hasPending())throw Error('PENDING_ACTION')
   const h=headRef.current
   if(h&&runtime.current)await connection.api('/sessions/'+h.id+'/position',{position:pos.current,sceneId:h.sceneId,expected_version:h.version})
   if(carriage){location.assign('./?story=carriage');return}
   if(id)await connection.client.selectSession(id);else await connection.client.enroll(locale,true)
   // Reload reconstructs the renderer with the chosen journey's immutable art/map bindings.
   location.reload()
  }catch(e){if(e instanceof Error&&e.message==='RUNTIME_VERSION_MISMATCH')setError(e.message);else setJourneyError(e instanceof Error&&e.message==='PENDING_ACTION'?t('有操作尚未确认，请先返回旅程恢复。','An action is unconfirmed. Return to the journey and recover first.'):t('切换未完成。请重试，已有旅程不会被覆盖。','Switching did not finish. Retry; existing journeys are not overwritten.'));setWorking(false)}
 }
 async function init(){setLoadingStage('connecting');setWorking(true);setError('');runtime.current?.pause(true);try{const health=await connection.api('/health');setIllustrationsAvailable(health.illustrationsAvailable===true);setOnlineAvailable(health.liveDialogueAvailable===true);setOnlineActionAvailable(health.liveModelAvailable===true);if(!health.liveDialogueAvailable&&!health.liveModelAvailable)setOnlineTalk(false);const h=await connection.client.enroll(locale);const recovered=await connection.client.recover();const next=recovered?.head??h;await restore(next);setPanel(next.version===0?'log':next.save.finale.status==='complete'?'ending':null)}catch(e){setError(e instanceof Error?e.message:'NETWORK_ERROR')}finally{setWorking(false)}}
 useEffect(()=>{mounted.current=true;void init();return()=>{mounted.current=false;runtime.current?.destroy();if(heroBlob.current){void Assets.unload(heroBlob.current).catch(()=>{});URL.revokeObjectURL(heroBlob.current)}equipmentEvents.current.clear();if(brakeBlob.current){void Assets.unload(brakeBlob.current).catch(()=>{});URL.revokeObjectURL(brakeBlob.current)}for(const blob of fanBlobs.current.values()){void Assets.unload(blob).catch(()=>{});URL.revokeObjectURL(blob)}fanBlobs.current.clear();if(equipmentBlob.current){void Assets.unload(equipmentBlob.current).catch(()=>{});URL.revokeObjectURL(equipmentBlob.current)}actorEvents.current.clear();for(const blob of fixedActorBlobs.current.values()){void Assets.unload(blob).catch(()=>{});URL.revokeObjectURL(blob)}fixedActorBlobs.current.clear();if(actorBlob.current){void Assets.unload(actorBlob.current).catch(()=>{});URL.revokeObjectURL(actorBlob.current)}for(const loader of loaders.current.values())loader.dispose()}},[])
 useEffect(()=>{runtime.current?.pause(busy||!ready||Boolean(panel)||Boolean(error))},[busy,ready,panel,error])
 useEffect(()=>{
  if(!ready||busy||panel||error||head?.sceneId!==fanArt.scene||originalFanState(head.save)!=='running'||!originalEquipmentHasArt('tunnel-fan',head.assets))return
  let raf=0,last=performance.now();const tick=(now:number)=>{const dt=now-last;last=now;if(!document.hidden&&dt>=0&&dt<=250){fanElapsed.current+=dt;projectEquipment()}raf=requestAnimationFrame(tick)};raf=requestAnimationFrame(tick);return()=>cancelAnimationFrame(raf)
 },[ready,busy,panel,error,head?.sceneId,head?.save.facts['tunnel-cargo-policy']])
 useEffect(()=>{const checkpoint=()=>{const h=headRef.current;if(h&&runtime.current&&!busyRef.current&&!errorRef.current&&runtime.current.renderedScene()===h.sceneId)void connection.api('/sessions/'+h.id+'/position',{position:pos.current,sceneId:h.sceneId,expected_version:h.version}).catch(e=>{if(mounted.current&&e instanceof Error&&e.message==='RUNTIME_VERSION_MISMATCH')setError(e.message)})};const timer=setInterval(checkpoint,2000);const hide=()=>{if(document.hidden){runtime.current?.move(0,0);checkpoint()}};document.addEventListener('visibilitychange',hide);return()=>{clearInterval(timer);document.removeEventListener('visibilitychange',hide)}},[])
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key==='Escape'&&!busyRef.current)setPanel(null)};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[])
 useEffect(()=>{if(!panel&&!error)return;const box=document.querySelector<HTMLElement>(error?'.og-error':'.og-sheet'),previous=document.activeElement as HTMLElement;const items=()=>Array.from(box?.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled),a[href]')??[]);items()[0]?.focus();const trap=(e:KeyboardEvent)=>{if(e.key!=='Tab')return;const all=items(),i=all.indexOf(document.activeElement as HTMLElement);if(!all.length)return;if(e.shiftKey&&i<=0){e.preventDefault();all.at(-1)!.focus()}else if(!e.shiftKey&&(i===all.length-1||i<0)){e.preventDefault();all[0].focus()}};window.addEventListener('keydown',trap);return()=>{window.removeEventListener('keydown',trap);previous?.focus()}},[panel,error])
 useLayoutEffect(()=>{const scroll=document.querySelector<HTMLElement>('.og-scroll');if(scroll&&panel==='log')scroll.scrollTop=scroll.scrollHeight;else if(scroll&&panel==='pictures')scroll.scrollTop=0},[panel,head?.version])
 function open(e:Entity){if(busyRef.current||!ready||error)return;setNotice(t('正在走近…','Walking closer…'));const h=headRef.current!;const arrive=()=>{if(headRef.current?.version!==h.version)return;setSelected(e.id);setTalk(Boolean(e.person));setInput('');setNotice('');setPanel('action')};if(Math.hypot(pos.current.x-e.approach.x,pos.current.y-e.approach.y)<8)arrive();else if(!runtime.current?.walkTo(e.approach,arrive))setNotice(t('这里暂时无法到达。','This point cannot be reached.'))}
 async function submit(choice?:{id:string;label:string}){const h=headRef.current,e=entity;if(!h||!e||busyRef.current||!ready||error)return;setWorking(true);setError('');runtime.current?.pause(true);try{
  for(const scene of !choice&&(talk||onlineTalk)?[]:originalActionDestinations(h,e.id,choice?{action:choice.id}:{text:input}))await loaderFor(h).prepare(scene,true)
  const body={target:e.id,position:pos.current,...(choice?{type:'action',action:choice.id}:{type:talk?'dialogue':'free-input',text:input,...(onlineTalk?{mode:'live'}:{})})};const r=await (!choice&&!talk&&onlineTalk?connection.client.sendPrepared(h,body):connection.client.send(h,body));if(r.rejectionCode==='ORIGINAL_MODEL_TEST_BUDGET_EXHAUSTED'){setOnlineTalk(false);setOnlineAvailable(false);setOnlineActionAvailable(false)}await restore(r.head);setPanel(r.accepted===false?'action':'log');if(r.accepted!==false)setInput('');setNotice(r.accepted===false?(r.rejectionCode==='ORIGINAL_MODEL_TEST_BUDGET_EXHAUSTED'?t('本次在线测试额度已用完，可以继续使用预设交谈和行动。','This online trial budget is used up. Preset conversation and actions remain available.'):r.rejectionCode==='ORIGINAL_BRAKE_ALREADY_REPAIRED'?t('新软管已经安装，不能再按旧裂管重复检查或更换。','The new hose is installed. The old fault cannot be inspected or replaced again.'):r.rejectionCode==='ORIGINAL_DIALOGUE_REJECTED'?t('这次回应未通过核对，进度保持不变。可以换个说法。','That reply did not pass validation. Progress is unchanged. Try another phrasing.'):r.rejectionCode==='ORIGINAL_DIALOGUE_UNSUPPORTED'?t('这句话暂时没能理解。可以询问目标，或换个说法。','That was not understood. Ask about the goal or try another phrasing.'):t('这项行动当前未能执行。','This action could not be performed.')):t('进度已保存','Progress saved'))
 }catch(err){setError(err instanceof Error?err.message:'NETWORK_ERROR')}finally{setWorking(false)}}
 async function finish(){const h=headRef.current;if(!h||busyRef.current||!ready||error)return;setWorking(true);setError('');try{const r=await connection.client.sendEnding(h);await restore(r.head);setPanel('ending')}catch(e){setError(e instanceof Error?e.message:'NETWORK_ERROR')}finally{setWorking(false)}}
 function ground(e:React.MouseEvent){if(busyRef.current||!ready||panel||error)return;const r=frame.current!.getBoundingClientRect();setNotice('');runtime.current?.walkTo({x:(e.clientX-r.left)*384/r.width-4.5,y:(e.clientY-r.top)*576/r.height-15})}
 const latest=save?originalReadingBlocks(save).at(-1):undefined
 return <main className="og-game" data-scene={scene??''} data-player-x={position.x.toFixed(2)} data-player-y={position.y.toFixed(2)} data-ready={ready} data-scenery={backgroundState} data-version={head?.version??-1} data-background-version={head?originalBackgroundVersion(head.assets):undefined} data-device-version={originalStarterRelease(head?.assets)?.id??'baseline'} data-actor-version={originalActorRelease(head?.assets)?.id??'baseline'}>
  <section className="og-world" aria-label={t('原作地图','Original map')}><div ref={frame} className="og-map" onClick={ground}>
   {head&&<OriginalSceneSilhouette head={head}/>}
   {background&&<img key={background} className="og-background" src={background} alt="" draggable={false}/>}<div id="rpg"/>
   {ready&&entities.map((e,i)=><button className={"og-marker"+(originalCharacterHasArt(e.person?.id,head?.assets)?" og-person":originalEquipmentHasArt(e.id,head?.assets)?" og-equipment":"")} data-entity={e.id} key={e.id} aria-label={e.person?.name??e.actions[0]?.label??e.label} style={{left:e.position.x/384*100+'%',top:e.position.y/576*100+'%'}} onClick={ev=>{ev.stopPropagation();open(e)}} disabled={busy||Boolean(error)}>{!originalCharacterHasArt(e.person?.id,head?.assets)&&!originalEquipmentHasArt(e.id,head?.assets)&&<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="8"/><path d="M12 7v10M7 12h10"/></svg>}<span>{e.person?.name??String(i+1)}</span></button>)}
   {destination&&<svg className="og-destination" viewBox="0 0 24 24" style={{left:(destination.x+4.5)/384*100+'%',top:(destination.y+15)/576*100+'%'}}><circle cx="12" cy="12" r="9"/></svg>}
  </div></section>
  <header className="og-hud" ref={hud}><small>{t('驶向黎明 · 单人旅程','Last Train to Dawn · Single player')}</small><h1>{head?originalPlaceLabel(head.sceneId,head.save):t('正在连接旅程','Connecting journey')}</h1><div className="og-stats">{save&&Object.entries(save.stats).map(([id,value])=><span key={id}>{({fuel:t('燃料','Fuel'),condition:t('车况','Condition'),morale:t('人心','Morale')} as Record<string,string>)[id]??id} <b>{value}</b></span>)}</div></header>
  <footer className="og-footer" ref={footer}><MovementJoystick disabled={!ready||busy||Boolean(panel)||Boolean(error)} destination={destination} locale={locale} onMove={(x,y)=>{if(!busyRef.current&&!errorRef.current)runtime.current?.move(x,y)}}/><p>{notice||(head?originalGameObjective(head):t('正在读取进度…','Reading progress…'))}</p><nav>{(['log','bag','people'] as const).map((p,i)=><button key={p} disabled={!head||busy||Boolean(error)} onClick={()=>setPanel(p)}>{[t('记录','Journal'),t('行囊','Inventory'),t('人物','People')][i]}</button>)}<button disabled={!ready||busy||Boolean(error)} onClick={()=>setPanel('nearby')}>{t('附近','Nearby')}</button></nav>{save?.finale.status==='ready'&&<button className="og-primary" onClick={()=>void finish()} disabled={busy||!ready||Boolean(error)}>{t('展开结局','Continue to the ending')}</button>}{save?.finale.status==='complete'&&<button disabled={Boolean(error)} onClick={()=>setPanel('ending')}>{t('查看结局','View ending')}</button>}</footer>
  {(!ready||busy)&&!error&&<JourneyLoading locale={locale} compact={ready} detail={ready?t('正在确认这次行动…','Confirming this action…'):loadingStage==='connecting'?t('正在连接你的旅程…','Connecting to your journey…'):loadingStage==='map'?t('正在准备前方的通路…','Preparing the path ahead…'):t('正在迎接旅途中的人…','Preparing your traveling companions…')}/>}
  {ready&&!busy&&backgroundState!=='ready'&&!error&&<aside className="og-scenery-status" role="status"><span>{backgroundState==='failed'?t('景物暂未载入，可继续探索','Scenery unavailable. Exploration remains open.'):t('景物正在浮现，可先探索','Scenery is coming into view. You can explore.')}</span>{backgroundState==='failed'&&<button onClick={()=>{if(head&&activeLoader)void activeLoader.prepareBackground(head.sceneId,true).catch(()=>{})}}>{t('重试景物','Retry scenery')}</button>}</aside>}
  {panel&&save&&!error&&<div className="og-scrim"><section className="og-sheet" role="dialog" aria-modal="true" aria-label={t('旅程面板','Journey panel')}><header><h2>{panel==='action'?(entity?.person?.name??entity?.label??t('附近物件','Nearby object')):({pictures:t("旅途画页","Journey illustrations"),journeys:t('已保存的旅程','Saved journeys'),nearby:t('附近可前往的位置','Places to approach'),log:t('旅程记录','Journey journal'),bag:t('行囊','Inventory'),people:t('认识的人','People met'),ending:t('旅程结局','Journey ending')} as Record<string,string>)[panel]}</h2><button onClick={()=>setPanel(null)} disabled={busy} aria-label={t('关闭面板','Close panel')}><svg viewBox="0 0 24 24"><path d="m6 6 12 12M6 18 18 6"/></svg></button></header><div className="og-scroll">
   {panel==='nearby'&&entities.map(e=><button className="og-choice" key={e.id} onClick={()=>{setPanel(null);runtime.current?.pause(false);open(e)}}>{e.person?.name??e.actions[0]?.label??e.label}</button>)}
   {panel==='action'&&entity&&<>{notice&&<p role="status">{notice}</p>}{entity.id==='brakes'&&brakeBlob.current&&<BrakeDetail image={brakeBlob.current} state={originalBrakeState(save)} locale={locale}/>}<p>{entity.person?.detail??(entity.actions.length?t('请选择当前可做的行动。','Choose an available action.'):t('可以关闭面板，继续旅程。','Close the panel to continue your journey.'))}</p>{entity.actions.map(a=><button className="og-choice" key={a.id} disabled={busy} onClick={()=>void submit(a)}>{a.label}</button>)}{entity.person&&<div><button type="button" disabled={busy} aria-pressed={talk} onClick={()=>setTalk(true)}>{t('交谈','Talk')}</button><button type="button" disabled={busy} aria-pressed={!talk} onClick={()=>setTalk(false)}>{t('输入行动','Enter action')}</button></div>}{(entity.person||entity.actions.length>0)&&(talk?onlineAvailable:onlineActionAvailable)&&<button type="button" className="og-choice" disabled={busy} aria-pressed={onlineTalk} onClick={()=>setOnlineTalk(!onlineTalk)}>{onlineTalk?(talk?t('在线交谈已开启 · 点击关闭','Online conversation on · Turn off'):t('在线理解已开启 · 点击关闭','Online understanding on · Turn off')):(talk?t('开启在线交谈','Turn on online conversation'):t('开启在线行动理解','Turn on online action understanding'))}</button>}{(entity.person||entity.actions.length>0)&&onlineTalk&&<p>{talk?t('发送本次输入、当前人物与最近交谈到平台模型；行动结果仍由游戏规则决定。','Send this input, the current character and recent conversation to the platform model; game rules still determine action outcomes.'):t('发送这次输入和当前可做的行动到平台模型。目标场景准备好后再执行。','Send this input and the available actions to the platform model. Execute after the destination is ready.')}</p>}{(entity.person||entity.actions.length>0)&&<form onSubmit={e=>{e.preventDefault();void submit()}}><label htmlFor="og-input">{!talk&&onlineTalk?t('用自己的话描述这次行动','Describe this action in your own words'):talk&&onlineTalk?t('和眼前的人物交谈','Talk to the character here'):talk?t('说说你的担心，询问目标或回忆刚才的话','Share a concern, ask about the goal, or recall your last words'):t('输入行动（当前支持目录中的完整句）','Enter an action (currently supports listed full phrases)')}</label><input id="og-input" value={input} maxLength={500} onChange={e=>setInput(e.target.value)} disabled={busy}/><button disabled={busy||!input.trim()} type="submit">{talk?t('说话','Say'):t('执行','Act')}</button></form>}</>}
   {panel==='log'&&<><button className="og-choice" disabled={busy} onClick={()=>void showJourneys()}>{t('查看与继续旧旅程','View and continue saved journeys')}</button>{originalReadingBlocks(save).map(b=><p key={b.id} data-kind={b.kind} data-latest={b.id===latest?.id?'true':undefined}>{b.speaker&&<strong>{b.speaker} · </strong>}{b.text}</p>)}{illustrationsAvailable&&<button className="og-choice" onClick={()=>setPanel("pictures")}>{t("查看旅途画页","View journey illustrations")}</button>}</>}
   {panel==="pictures"&&head&&illustrationsAvailable&&<OriginalIllustrationPanel key={head.id} head={head} api={connection.api} onReadJournal={()=>setPanel("log")}/>}
   {panel==='journeys'&&<><button className="og-choice" disabled={busy} onClick={()=>void chooseJourney(undefined,true)}>{t('继续之前的车厢旅程','Continue the earlier carriage journey')}</button><p>{t('进度自动保存在服务器。另开旅程会保留旧旅程；当前使用本浏览器的游戏身份，清除浏览器数据后尚不能靠平台账号找回。','Progress is saved on the server. Starting again keeps previous journeys. Access currently uses this browser’s game identity; platform account recovery after clearing browser data is not available yet.')}</p>{journeyError&&<p role="alert">{journeyError}</p>}<button className="og-choice" disabled={busy} onClick={()=>void prepareBackup()}>{t('准备旅程备份','Prepare journey backup')}</button>{backup&&<p><a className="og-choice" href={backup.url} download={backup.name}>{t('下载备份','Download backup')} · {t('进展','Progress')} {backup.version}</a></p>}<p>{t('备份包含剧情与自由输入，不含登录凭据。请自行妥善保存；目前恢复需要协助，不能直接导入游戏。','The backup contains story and typed inputs, without login credentials. Keep it private. Recovery currently requires assistance; direct game import is unavailable.')}</p><button className="og-choice" disabled={busy} onClick={()=>void showJourneys()}>{t('刷新旅程列表','Refresh journey list')}</button>{journeys.map(j=><button className="og-choice" key={j.id} disabled={busy||j.id===head?.id} onClick={()=>void chooseJourney(j.id)}>{j.id===head?.id?t('当前旅程 · ','Current journey · '):t('继续旅程 · ','Continue journey · ')}{originalPlaceLabel(j.scene,{locale,location:save.map.find(m=>m.id===world.scenes.find(s=>s.id===j.scene)?.storyLocationId)?.label??t('未知位置','Unknown place')})} · {t('进展','Progress')} {j.version} · {new Date(j.updated).toLocaleString(locale==='zh'?'zh-CN':'en-US')}</button>)}<button className="og-choice" disabled={busy||journeys.length>=100} onClick={()=>void chooseJourney()}>{t('保留旧旅程，重新出发','Keep old journeys and start again')}</button>{journeys.length>=100&&<p>{t('已达到100份旅程上限，仍可继续已有旅程。','The 100-journey limit is reached; existing journeys remain playable.')}</p>}</>}
   {panel==='bag'&&<>{save.inventory.length?save.inventory.map(i=><article key={i.id}><h3>{i.label} × {i.count}</h3><p>{i.lore}</p></article>):<p>{t('行囊暂时为空。','Your inventory is empty.')}</p>}</>}
   {panel==='people'&&save.characters.map(c=><article key={c.id}><h3>{c.name}{save.partyMemberIds.includes(c.id)?t(' · 同行',' · Traveling'):''}</h3><p>{c.detail}</p>{save.relationships.filter(r=>r.characterId===c.id).map((r,i)=><p key={i}>{r.source} {r.delta>0?'+':''}{r.delta}</p>)}</article>)}
   {panel==='ending'&&save.finale.ending&&<><h3>{save.finale.ending.title}</h3><p>{save.finale.ending.thesis}</p>{save.finale.ending.finaleScenes.map((s,i)=><p key={i}>{s}</p>)}<h3>{t('承担的代价','Costs accepted')}</h3>{save.finale.ending.irreversibleCosts.map((s,i)=><p key={i}>{s}</p>)}{save.finale.ending.characterEpilogues.map(e=><article key={e.characterId}><h3>{save.characters.find(c=>c.id===e.characterId)?.name}</h3><p>{e.text}</p></article>)}{save.finale.ending.regionalEpilogues.map(e=><article key={e.regionId}><h3>{save.map.find(m=>m.id===e.regionId)?.label}</h3><p>{e.text}</p></article>)}</>}
  </div></section></div>}
  {error&&<aside className="og-error" role="alertdialog" aria-modal="true" aria-label={t('恢复旅程','Recover journey')}><p>{versionMismatch?t('游戏已更新，当前页面与服务版本不一致。请重新载入以恢复原旅程和待确认操作。','The game was updated and this page no longer matches the service. Reload to recover your journey and pending actions.'):error==='SESSION_SELECTION_CHANGED'?t('已在另一窗口切换旅程，请重新载入以继续当前选择。','Another tab selected a different journey. Reload to continue the current selection.'):reloadRequired?t('地图没有完成加载。重新载入页面后，将恢复同一旅程和已保存的操作。','The map did not finish loading. Reload the page to recover this journey and saved actions.'):(error.startsWith('BACKGROUND_')||error.startsWith('DEVICE_')||error.startsWith('ACTOR_')||error.startsWith('LAYER_'))?t('这个素材版本尚不可用。可以返回默认旅程，原进度不会被覆盖。','This art version is unavailable. Return to the default journey without overwriting progress.'):error.startsWith('SCENE_NOT_READY:')?t('场景素材暂时无法加载。已保存的进度会保留，恢复后继续。','Scene assets could not load. Saved progress is preserved; recover to continue.'):t('操作尚未确认，进度与待确认请求会保留。','The operation is not confirmed. Progress and pending requests are preserved.')}</p><small>{error}</small><button disabled={busy} onClick={()=>{if(reloadRequired)location.reload();else void init()}}>{versionMismatch?t('重新载入游戏并恢复','Reload game and recover'):reloadRequired?t('重新载入地图并恢复','Reload map and recover'):t('重新连接并恢复','Reconnect and recover')}</button>{(new URLSearchParams(location.search).has('background_release')||new URLSearchParams(location.search).has('device_release')||new URLSearchParams(location.search).has('actor_release')||new URLSearchParams(location.search).has('fan_release'))&&<a href="./?story=original">{t('返回默认旅程','Return to the default journey')}</a>}</aside>}
 </main>
}
