import React,{useEffect,useRef,useState} from 'react'
import {BrowserSpriteDrafts,spriteDatabaseName,newSpriteSource,inspectSpritePng,runSpriteDraft,type SpriteDraft,type SpritePng} from './sprite-draft'
import {decodeSpritePixels,encodeSpritePixels,spritePreviewUrl} from './sprite-browser-io'
import {prepareSpritesOffThread} from './sprite-preparation-client'
import type {SpritePreparationSpec} from './sprite-preparation'
import actorSample from '../doc/platform-art-candidates/20260911/actor-edit-02/candidate.png'
import propSample from '../doc/platform-art-candidates/20260911/props-edit-01/candidate.png'
import './art-creator.css'
// A fixture is injected only by the separate QA build; the production entry supplies none.
export default function SpriteCreator({fixture,locale}:{fixture?:()=>Promise<SpritePng>;locale?:'zh'|'en'}={}) {
 const zh=locale?locale==='zh':navigator.language.startsWith('zh'),t=(a:string,b:string)=>zh?a:b
 const repo=useRef<BrowserSpriteDrafts>(),mounted=useRef(true),cancel=useRef<AbortController>()
 const [draft,setDraft]=useState<SpriteDraft>(),[history,setHistory]=useState<SpriteDraft[]>([]),[ready,setReady]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const [kind,setKind]=useState<'actor'|'states'>('actor'),[mode,setMode]=useState<'pale-neutral'|'alpha'>('pale-neutral'),[neutral,setNeutral]=useState(200),[footY,setFootY]=useState(300),[anchors,setAnchors]=useState('')
 const [show,setShow]=useState<'source'|'result'>('source'),[background,setBackground]=useState<'dark'|'light'>('dark'),[url,setUrl]=useState(''),[download,setDownload]=useState('')
 function apply(d:SpriteDraft|undefined){setDraft(d);if(d){const k=d.spec?.kind??d.sourceKind??'actor';setKind(k);setMode(d.spec?.backgroundMode??'pale-neutral');setNeutral(d.spec?.neutralMin??200);setFootY(d.spec?.foot.y??Math.floor(d.source.height/(k==='actor'?4:1)*.85));setAnchors(d.spec?.sourceAnchors?.map(a=>`${a.x},${a.y}`).join('; ')??'')}}
 useEffect(()=>{mounted.current=true;const store=new BrowserSpriteDrafts(spriteDatabaseName(location.href));repo.current=store;void Promise.all([store.get(),store.list()]).then(([d,h])=>{if(mounted.current){apply(d);setShow(d?.result?'result':'source');setHistory(h);setReady(true)}}).catch(()=>setError('SPRITE_STORAGE_FAILED'));return()=>{mounted.current=false;cancel.current?.abort();void store.close()}},[])
 useEffect(()=>{let cancelled=false;const urls:string[]=[];setUrl('');setDownload('');const selected=show==='result'&&draft?.result?draft.result.png:draft?.source;if(selected)void spritePreviewUrl(selected).then(u=>{urls.push(u);if(cancelled)URL.revokeObjectURL(u);else setUrl(u)}).catch(()=>setError('SPRITE_DECODE'));if(draft?.result)void spritePreviewUrl(draft.result.png).then(u=>{urls.push(u);if(cancelled)URL.revokeObjectURL(u);else setDownload(u)}).catch(()=>setError('SPRITE_DECODE'));return()=>{cancelled=true;urls.forEach(u=>URL.revokeObjectURL(u))}},[draft?.id,draft?.revision,show])
 async function locked(work:()=>Promise<void>) {
  if(busy||!ready)return;setBusy(true);setError('')
  try{if(!navigator.locks)throw Error('SPRITE_LOCK_UNAVAILABLE');await navigator.locks.request(spriteDatabaseName(location.href),{ifAvailable:true},async lock=>{if(!lock)throw Error('SPRITE_OTHER_TAB');await work()})}
  catch(e){if(mounted.current)setError(e instanceof Error&&e.message.startsWith('SPRITE_')?e.message:'SPRITE_PREPARATION_FAILED')}
  finally{if(mounted.current){setBusy(false);try{const d=await repo.current!.get();apply(d);setHistory(await repo.current!.list())}catch{setError('SPRITE_STORAGE_FAILED')}}}
 }
 async function importSource(load:()=>Promise<SpritePng>,name:string,nextKind:'actor'|'states') {
  await locked(async()=>{const source=await load(),checkedUrl=await spritePreviewUrl(source);URL.revokeObjectURL(checkedUrl);const old=await repo.current!.get(),next=newSpriteSource(source,name,nextKind);await repo.current!.save(next,old);setDraft(next);setKind(nextKind);setFootY(Math.floor(source.height/(nextKind==='actor'?4:1)*.85));setAnchors('');setShow('source')})
 }
 async function loadSample(which:'actor'|'states') {
  const path=which==='actor'?actorSample:propSample
  await importSource(async()=>{const response=await fetch(path,{credentials:'omit'});if(!response.ok)throw Error('SPRITE_DOWNLOAD');const bytes=new Uint8Array(await response.arrayBuffer());const png=await inspectSpritePng(bytes),expected=which==='actor'?'dfcb31ee903944b733814a7d64d579847122247db11030317958e46debd9f9f4':'fdcbd8562b9c9d2b3669922553b2c25f1af213fbbd9e3a109daa30603e71fa0e';if(png.sha256!==expected)throw Error('SPRITE_CORRUPT');return png},which==='actor'?'platform-actor-edit-02':'platform-props-edit-01',which)
 }
 async function process() {
  if(!draft)return
  await locked(async()=>{const rows=kind==='actor'?4:1,w=draft.source.width/3,h=draft.source.height/rows
   const sourceAnchors=kind==='states'?anchors.split(';').map(pair=>{const bits=pair.trim().split(',');return {x:bits.length===2&&bits[0].trim()?Number(bits[0]):NaN,y:bits.length===2&&bits[1].trim()?Number(bits[1]):NaN}}):undefined
   if(sourceAnchors&&(sourceAnchors.length!==3||sourceAnchors.some(a=>!Number.isInteger(a.x)||!Number.isInteger(a.y))))throw Error('SPRITE_STATE_ANCHORS_REQUIRED')
   const spec:SpritePreparationSpec={columns:3,rows,cellWidth:w,cellHeight:h,foot:{x:Math.floor(w/2),y:footY},kind,backgroundMode:mode,neutralMin:neutral,chromaMax:20,sourceAnchors}
   cancel.current=new AbortController()
   const next=await runSpriteDraft(repo.current!,draft,spec,{decode:decodeSpritePixels,encode:encodeSpritePixels,process:prepareSpritesOffThread},cancel.current.signal,d=>{if(mounted.current)setDraft(d)})
   if(mounted.current){setDraft(next);setShow(next.result?'result':'source')}
  })
 }
 const errors:Record<string,string>={SPRITE_STATE_ANCHORS_REQUIRED:t('请填写三个柜体落地点，例如 160,440; 160,440; 160,440。','Enter three cabinet contact points, e.g. 160,440; 160,440; 160,440.'),SPRITE_PREPARATION_FRAME_DOES_NOT_FIT:t('移动后超出帧边界。请调整目标落地高度或柜体接地点。','The aligned frame does not fit. Adjust target height or cabinet contact points.'),SPRITE_PREPARATION_ABORTED:t('已取消。原图和已有候选保留，可重新处理。','Cancelled. Original and previous candidates are kept. You can process again.'),SPRITE_OTHER_TAB:t('另一窗口正在处理，请稍后再试。','Another tab is processing. Please retry shortly.'),SPRITE_DRAFT_REPLACED:t('草稿已在另一窗口更新，请基于最新记录继续。','Another tab updated the draft. Continue from the latest record.'),SPRITE_STORAGE_FAILED:t('草稿未能保存。请检查浏览器存储后重试。','The draft could not be saved. Check browser storage and retry.'),SPRITE_PREPARATION_EMPTY_FRAME:t('有一帧没有可保留主体，请检查图集类型和背景阈值。','A frame has no retained subject. Check the sheet type and matte threshold.'),SPRITE_PREPARATION_CLIPPED_FRAME:t('主体触及帧边界，可能被截断或仍有背景残留，请检查原图。','A subject touches its frame edge. Inspect the source for clipping or remaining matte.')}
 const issue=error||draft?.error
 const errorNotice=issue&&<p role="alert">{errors[issue]??t('这次操作未完成，请检查图片或参数后重试。','The operation did not complete. Check the image or settings and retry.')} <small>{issue}</small></p>
 return <main className="cl-creator cl-sprite"><header><a href="./creator.html">{t('返回背景制作','Back to background creation')}</a><h1>{t('准备人物与设备素材','Prepare character and equipment art')}</h1><p>{t('原图始终保留。每次处理另存一个候选，检查后再决定是否采用。','Keep the original. Each processing run saves a separate candidate for review.')}</p></header>
 <section aria-label={t('原图来源','Source image')}><label htmlFor="sprite-file">{t('选择 PNG 图集（最多 8 MiB）','Choose a PNG sheet (up to 8 MiB)')}</label><input id="sprite-file" type="file" accept="image/png" disabled={!ready||busy} onChange={e=>{const file=e.target.files?.[0];e.target.value='';if(file)void importSource(async()=>{if(file.size>8*1024*1024)throw Error('SPRITE_INVALID_PNG');return inspectSpritePng(new Uint8Array(await file.arrayBuffer()))},file.name,'actor')}}/><button disabled={!ready||busy} onClick={()=>void loadSample('actor')}>{t('载入平台人物样本','Load platform character sample')}</button><button disabled={!ready||busy} onClick={()=>void loadSample('states')}>{t('载入平台设备样本','Load platform equipment sample')}</button>{fixture&&<button disabled={!ready||busy} onClick={()=>void importSource(fixture,'synthetic-test-only','actor')}>Load synthetic QA source</button>}</section>
 {draft&&<><section aria-label={t('处理参数','Preparation settings')}><p>{draft.sourceName} · {draft.source.width} × {draft.source.height}</p><label htmlFor="sprite-kind">{t('图集类型','Sheet type')}</label><select id="sprite-kind" value={kind} disabled={busy} onChange={e=>{const k=e.target.value as typeof kind;setKind(k);setFootY(Math.floor(draft.source.height/(k==='actor'?4:1)*.85))}}><option value="actor">{t('人物 · 3 列 × 4 个方向','Character · 3 columns × 4 directions')}</option><option value="states">{t('设备 · 3 列 × 1 行状态','Equipment · 3 columns × 1 row of states')}</option></select>
 <label htmlFor="sprite-mode">{t('背景处理','Background handling')}</label><select id="sprite-mode" value={mode} disabled={busy} onChange={e=>setMode(e.target.value as typeof mode)}><option value="pale-neutral">{t('去除浅色背景','Remove pale neutral matte')}</option><option value="alpha">{t('保持已有透明，只对齐','Keep existing alpha; align only')}</option></select>
 {mode==='pale-neutral'&&<><label htmlFor="sprite-neutral">{t('背景最低亮度（180–255）','Minimum matte brightness (180–255)')}</label><input id="sprite-neutral" type="number" min={180} max={255} value={neutral} disabled={busy} onChange={e=>setNeutral(e.target.valueAsNumber)}/></>}
 <label htmlFor="sprite-foot">{t('目标落地高度（帧内像素）','Target contact height (pixels within frame)')}</label><input id="sprite-foot" type="number" min={1} value={footY} disabled={busy} onChange={e=>setFootY(e.target.valueAsNumber)}/>
 {kind==='states'&&<><label htmlFor="sprite-anchors">{t('三个柜体接地点（各帧 x,y；用英文分号分隔）','Three cabinet contact points (local x,y; separated by semicolons)')}</label><input id="sprite-anchors" value={anchors} disabled={busy} placeholder="160,440; 160,440; 160,440" onChange={e=>setAnchors(e.target.value)}/><p>{t('使用柜体的落地点，不使用打开后的门角。','Use the cabinet contact point, not the open door corner.')}</p></>}
 <button className="cl-primary" disabled={busy||!ready} onClick={()=>void process()}>{busy?t('正在处理…','Processing…'):t('处理并保存新候选','Process and save new candidate')}</button>{busy&&<button onClick={()=>cancel.current?.abort()}>{t('取消处理','Cancel processing')}</button>}
 </section><p role="status">{draft.state==='candidate'?t('候选已保存，尚未准入游戏。','Candidate saved; not admitted to the game.'):draft.state==='processing'&&!busy?t('上次处理未完成。原图已保留，可以重新处理。','The previous run did not finish. The source is saved; you can process again.'):t('先检查原图与参数。','Inspect the source and settings first.')}</p>
 {errorNotice}<section aria-label={t('素材预览','Art preview')}><label htmlFor="sprite-view">{t('查看版本','View version')}</label><select id="sprite-view" value={show} onChange={e=>setShow(e.target.value as typeof show)}><option value="source">{t('原图','Original')}</option><option value="result" disabled={!draft.result}>{t('处理结果','Processed candidate')}</option></select><label htmlFor="sprite-bg">{t('检查底色','Review background')}</label><select id="sprite-bg" value={background} onChange={e=>setBackground(e.target.value as typeof background)}><option value="dark">{t('深色','Dark')}</option><option value="light">{t('浅色','Light')}</option></select>{url&&<div className={`cl-sprite__preview cl-sprite__preview--${background}`}><img src={url} alt={show==='result'?t('处理后的候选图集','Processed candidate sheet'):t('未经处理的原图集','Original unprocessed sheet')} draggable={false}/></div>}{draft.result&&draft.spec?.kind==='actor'&&<a className="cl-creator__action" href={`./creator.html?scene_preview=north-cape&actor_draft=${encodeURIComponent(draft.id)}`}>{t('在地图里试走这个人物','Try this actor in the map')}</a>}{draft.result&&draft.spec?.kind==='states'&&<a className="cl-creator__action" href={`./creator.html?scene_preview=north-cape&device_draft=${encodeURIComponent(draft.id)}`}>{t('在地图里检查这个设备','Inspect this device in the map')}</a>}{download&&<a download={`sprite-${draft.id}.png`} href={download}>{t('导出候选 PNG','Export candidate PNG')}</a>}</section></>}

 {!draft&&errorNotice}
 {!!history.length&&<section><label htmlFor="sprite-history">{t('已保存记录','Saved records')}</label><select id="sprite-history" value={draft?.id??''} disabled={busy} onChange={e=>{const id=e.target.value;void locked(async()=>{const selected=await repo.current!.get(id);if(!selected)throw Error('SPRITE_CORRUPT');const current=await repo.current!.get();await repo.current!.save(selected,current);setShow(selected.result?'result':'source')})}}>{history.map(d=><option key={d.id} value={d.id}>{d.sourceName} · {d.result?t('候选','candidate'):t('原图/未完成','source/unfinished')} · {new Date(d.createdAt).toLocaleTimeString()}</option>)}</select></section>}
 {draft&&<details><summary>{t('素材记录','Art record')}</summary><dl><dt>{t('记录 ID','Record ID')}</dt><dd>{draft.id}</dd><dt>{t('原图摘要','Source SHA-256')}</dt><dd>{draft.source.sha256}</dd>{draft.result&&<><dt>{t('候选摘要','Candidate SHA-256')}</dt><dd>{draft.result.png.sha256}</dd><dt>{t('处理版本','Algorithm')}</dt><dd>{draft.result.algorithm}</dd></>}</dl></details>}
 <footer><p>{t('保存在当前浏览器。透明边缘、四方向和动作仍需实际检查；本页不会发布或替换游戏资产。','Saved in this browser. Alpha edges, directions and animation still need review. This page cannot publish or replace game assets.')}</p></footer></main>
}
