import React,{useEffect,useRef,useState} from 'react'
import {draftSessionId} from './art-draft'
import {BrowserSpriteGenerations,spriteGenerationDatabase,planSpriteGeneration,runSpriteGeneration,createSpriteProducer,pendingSpriteGeneration,type SpriteGeneration,type SpriteProducer} from './sprite-generation'
import {SPRITE_RECIPES,DEFAULT_SPRITE_RECIPE,spriteRecipeAvailable,spriteGenerationRequest,type SpriteRecipe} from './sprite-generation-recipe'
export default function SpriteGenerationPanel({ready,busy,locked,adopt,locale,producer}:{ready:boolean;busy:boolean;locked:(work:()=>Promise<void>)=>Promise<void>;adopt:(d:SpriteGeneration)=>Promise<void>;locale:'zh'|'en';producer?:SpriteProducer}){
 const zh=locale==='zh',t=(a:string,b:string)=>zh?a:b,repo=useRef<BrowserSpriteGenerations>(),alive=useRef(true)
 const [loaded,setLoaded]=useState(false),[draft,setDraft]=useState<SpriteGeneration>(),[history,setHistory]=useState<SpriteGeneration[]>([]),[recipe,setRecipe]=useState<SpriteRecipe>(DEFAULT_SPRITE_RECIPE),[clock,setClock]=useState(Date.now()),[error,setError]=useState(''),[adopted,setAdopted]=useState('')
 const label=(r:SpriteRecipe)=>r==='ada-walk-v1'?t('阿达 · 四向行走图集','Ada · Four-direction walk sheet'):r==='starter-broken-v1'?t('启动机 · 修复前','Starter · Before repair'):t('启动机 · 修复后','Starter · After repair')
 async function refresh(){const d=await repo.current!.get(),h=await repo.current!.list();if(alive.current){setDraft(d);setHistory(h);if(d)setRecipe(pendingSpriteGeneration(d)||spriteRecipeAvailable(d.recipe)?d.recipe:DEFAULT_SPRITE_RECIPE)}}
 useEffect(()=>{alive.current=true;repo.current=new BrowserSpriteGenerations(spriteGenerationDatabase(location.href));void refresh().then(()=>{if(alive.current)setLoaded(true)}).catch(()=>setError('SPRITE_STORAGE_FAILED'));const timer=setInterval(()=>setClock(Date.now()),1000);return()=>{alive.current=false;clearInterval(timer);void repo.current?.close()}},[])
 async function generate(){await locked(async()=>{setError('');try{const store=repo.current!,current=await store.get();if(current?.error==='ORIGIN_NOT_ALLOWED')throw Error('ORIGIN_NOT_ALLOWED');if((current?.nextAt??0)>Date.now())throw Error('COOLDOWN');if(!pendingSpriteGeneration(current)){const next=planSpriteGeneration(recipe,draftSessionId(location.href));await store.put(next);setDraft(next)}await runSpriteGeneration(store,producer??createSpriteProducer(),d=>{if(alive.current)setDraft(d)})}catch(e){if(alive.current)setError(e instanceof Error?e.message:'SPRITE_GENERATION_UNAVAILABLE')}finally{await refresh()}})}
 const pending=pendingSpriteGeneration(draft),cooldown=Math.max(0,Math.ceil(((draft?.nextAt??0)-clock)/1000)),issue=error||draft?.error,origin=issue==='ORIGIN_NOT_ALLOWED'
 return <section aria-label={t('在线生成素材','Generate art online')}><h2>{t('通过平台生成素材','Generate art through AlterU')}</h2><p>{t('沿用已选俯视风格。生成后先导入原图，再处理和检查；不会自动替换游戏人物或设备。','Keep the selected overhead style. Import the generated source, then process and review it before changing game art.')}</p>
 <p>{t('四向行走图集的侧向步态尚未通过，暂不发起新的行走图集生成。已有任务仍可恢复，原图和检查记录保留。可继续使用游戏现有人物。','Sideways gait has not passed review, so new walking-sheet generation is unavailable. Existing tasks can resume; sources and reviews are retained. You can keep the game’s existing characters.')}</p><a href="./creator.html?create_art=assembly">{t('使用已有素材继续制作','Continue with existing art')}</a>
 <label htmlFor="sprite-recipe">{t('要制作的素材','Art to create')}</label><select id="sprite-recipe" value={recipe} disabled={!loaded||busy||pending} onChange={e=>setRecipe(e.target.value as SpriteRecipe)}>{SPRITE_RECIPES.map(r=><option key={r} value={r} disabled={!spriteRecipeAvailable(r)}>{label(r)}{!spriteRecipeAvailable(r)?t(' · 步态未通过',' · Gait not approved'):''}</option>)}</select>
 <button className="cl-primary" disabled={!ready||!loaded||busy||cooldown>0||origin||!pending&&!spriteRecipeAvailable(recipe)} onClick={()=>void generate()}>{busy?t('正在操作…','Working…'):pending?t('继续同一生成任务','Resume the same task'):t('生成新原图候选','Generate a new source candidate')}</button>
 {cooldown>0&&<p>{t('可继续时间：','Available in ')}{cooldown}s</p>}
 <p role="status">{draft?.state==='ready'?t('原图已生成并保存在此浏览器，可在下方导入。','Source saved in this browser. Import it below when ready.'):draft?.state==='generating'?t('生成任务已保存。离开后可回来继续同一任务。','Task saved. Return to resume this task if you leave.'):pending?t('上次任务尚未完成，请继续原任务。','The previous task is unfinished. Resume it before starting another.'):t('一次生成一个候选。返回成功不等于动作、透明和比例合格。','Generate one candidate at a time. Success does not establish correct animation, alpha or scale.')}</p>
 {issue&&<p role="alert">{origin?t('此网页来源尚未获媒体服务允许。请在受支持的部署来源继续；重复生成无法解决。','The media service does not allow this page origin. Continue from a supported deployment; repeating generation will not fix it.'):t('未取得可用原图。已保存的任务保留，可按提示继续。','No usable source yet. The saved task is retained for recovery.')}<small>{issue}</small></p>}
 {draft&&<details><summary>{t('生成记录','Generation record')}</summary><dl><dt>{t('请求','Request')}</dt><dd>{draft.id}</dd><dt>{t('任务','Task')}</dt><dd>{draft.taskId??t('等待服务确认','Awaiting service acknowledgement')}</dd><dt>{t('固定配方','Fixed recipe')}</dt><dd>{draft.recipe}</dd></dl><p>{spriteGenerationRequest(draft.recipe,draft.id,draft.sessionId).prompt}</p></details>}
 {history.filter(d=>d.state==='ready').map(d=><div key={d.id}><p>{label(d.recipe)} · {new Date(d.createdAt).toLocaleString()}</p><button disabled={busy||!ready} onClick={()=>void locked(async()=>{const saved=await repo.current!.get(d.id);if(!saved)throw Error('SPRITE_GENERATION_INVALID');await adopt(saved);setAdopted(saved.id)})}>{t('导入这张原图','Import this source')}</button></div>)}
 {adopted&&<p role="status">{t('已导入原图。请在下方处理；设备单帧先加入“修复前 / 修复后”组合。','Source imported. Process it below; combine individual equipment frames as before / after states first.')}</p>}
 </section>
}
