import type {GenerateImageMediaRequest} from './vendor/media/client'
/** Versioned recipes are immutable: archived provenance reconstructs the exact request. */
export const SPRITE_RECIPES=['ada-walk-v1','starter-broken-v1','starter-repaired-v1'] as const
export type SpriteRecipe=typeof SPRITE_RECIPES[number]
export type SpriteGenerationSource={version:1;recipe:SpriteRecipe;requestId:string;sessionId:string;taskId:string}
const uuid=/^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$/i
export function assertSpriteGenerationSource(v:any):asserts v is SpriteGenerationSource{
 if(!v||Object.keys(v).sort().join(',')!=='recipe,requestId,sessionId,taskId,version'||v.version!==1||!SPRITE_RECIPES.includes(v.recipe)||!uuid.test(v.requestId)||!uuid.test(v.sessionId)||typeof v.taskId!=='string'||!/^[A-Za-z0-9_-]{1,160}$/.test(v.taskId))throw Error('SPRITE_GENERATION_INVALID')
}
export function spriteGenerationRequest(recipe:SpriteRecipe,requestId:string,sessionId:string):GenerateImageMediaRequest & {requestId:string}{
 if(!SPRITE_RECIPES.includes(recipe)||!uuid.test(requestId)||!uuid.test(sessionId))throw Error('SPRITE_GENERATION_INVALID')
 const actor=recipe==='ada-walk-v1'
 const reference=actor?'https://raw.githubusercontent.com/yinxinghuan/rpgjs-story-lab/5f3bb85f9cdab4b8fb21aea64825ca56fbf6bcca/public/art/overhead/hero-gait-v2.png':'https://raw.githubusercontent.com/yinxinghuan/rpgjs-story-lab/42370d251a093697a343776c4df387ad266d4a90/public/art/references/starter-open-source-v1.png'
 const prompt=actor?
  'Edit this sprite sheet in place. SUBJECT A is Ada, one young adult female railway apprentice: short dark-brown hair, muted navy work coat, off-white collar, dark teal work trousers, brown boots, a small tool pouch with an enclosed brass work lamp clipped to it. Preserve the reference body proportions, strong overhead orthographic view, visible head and shoulder tops, foreshortened face and crisp pixel-painted detail. Keep a 3-column by 4-row sheet. Rows face DOWN toward viewer, LEFT with nose pointing left, RIGHT with nose pointing right, UP away with no face visible. The middle column stands still. In EVERY row the outer columns are opposite walking strides: the leg leading in column 1 trails in column 3. Especially in the back row, do not repeat the same leading leg. Keep pouch and lamp on the same anatomical side in every frame; do not mirror the whole figure to fake the opposite step. Preserve margins and equal cell size; all twelve figures fit fully inside their cells. Output 960x1280. Real transparent alpha outside figures if available; otherwise a uniform pure white matte. No painted checkerboard, floor, shadows, grid, labels or text.':
  'Edit this exact diesel starter contactor, preserving the 320x640 canvas, object position, orthographic overhead angle, top plane, silhouette, open left cover, brass bolts, dark metal and crisp pixel-painted detail. Keep the exposed copper-wound coil, two upright terminals, mounts and wire routes. '+(recipe==='starter-repaired-v1'?'Reconnect the broken lower switching contact with one small clean flat copper shunt strip horizontally below the coil, between its existing lower studs. Keep the copper winding exposed.':'Keep the lower switching contact visibly broken and darkened; no copper bridge between its lower studs. Preserve the existing exposed copper-wound coil.')+' One complete object only. Do not add a fuse, ceramic cartridge, casing, indicator, lamp, sparks or glow. Do not change the cover, feet, scale or placement. Real transparent alpha if available; otherwise uniform pure white matte. No painted checkerboard, scene, shadow, panels or text.'
 return {sessionId,requestId,mode:'edit',referenceUrls:[reference],prompt,size:actor?{width:960,height:1280}:{width:320,height:640}}
}
