import React,{useEffect,useRef,useState} from 'react'
import {BrowserSpriteDrafts,spriteDatabaseName,newSpriteSource,inspectSpritePng,runSpriteDraft,type SpriteDraft,type SpritePng,type SpriteCompositionInput} from './sprite-draft'
import {decodeSpritePixels,encodeSpritePixels,spritePreviewUrl} from './sprite-browser-io'
import {prepareSpritesOffThread} from './sprite-preparation-client'
import type {SpritePreparationSpec} from './sprite-preparation'
import adaSample from '../doc/platform-art-candidates/20260911/actor-edit-03/candidate.png'
import actorSample from '../doc/platform-art-candidates/20260911/actor-edit-02/candidate.png'
import propSample from '../doc/platform-art-candidates/20260911/props-edit-01/candidate.png'
import starterBeforeSample from '../doc/platform-art-candidates/20260911/starter-edit-02/candidate.png'
import starterAfterSample from '../doc/platform-art-candidates/20260911/starter-repair-03/candidate.png'
import {composeRepairFrames} from './sprite-composition'
import {savedSpriteSources,resolveSavedSpriteSource} from './sprite-source-library'
import SpriteCloudPanel from './sprite-cloud-panel'
import SpriteGenerationPanel from './sprite-generation-panel'
import {adoptSpriteGeneration,type SpriteProducer} from './sprite-generation'
import './art-creator.css'
// A fixture is injected only by the separate QA build; the production entry supplies none.
export default function SpriteCreator({fixture,locale,generationProducer}:{generationProducer?:SpriteProducer;fixture?:()=>Promise<SpritePng>;locale?:'zh'|'en'}={}) {
 const zh=locale?locale==='zh':navigator.language.startsWith('zh'),t=(a:string,b:string)=>zh?a:b
 const repo=useRef<BrowserSpriteDrafts>(),mounted=useRef(true),cancel=useRef<AbortController>()
 const [draft,setDraft]=useState<SpriteDraft>(),[history,setHistory]=useState<SpriteDraft[]>([]),[ready,setReady]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const savedSources=savedSpriteSources(history)
 const [stateSet,setStateSet]=useState<'cabinet'|'repair'>('cabinet'),[parts,setParts]=useState<Array<SpriteCompositionInput|undefined>>([undefined,undefined])
 const [kind,setKind]=useState<'actor'|'states'>('actor'),[mode,setMode]=useState<'pale-neutral'|'alpha'>('pale-neutral'),[neutral,setNeutral]=useState(200),[footY,setFootY]=useState(300),[anchors,setAnchors]=useState('')
 const [show,setShow]=useState<'source'|'result'>('source'),[background,setBackground]=useState<'dark'|'light'>('dark'),[url,setUrl]=useState(''),[download,setDownload]=useState('')
 function apply(d:SpriteDraft|undefined){setDraft(d);if(d){const k=d.spec?.kind??d.sourceKind??'actor';setKind(k);setStateSet(d.deviceStateSet==='repair'?'repair':'cabinet');setMode(d.spec?.backgroundMode??'pale-neutral');setNeutral(d.spec?.neutralMin??200);setFootY(d.spec?.foot.y??Math.floor(d.source.height/(k==='actor'?4:1)*.85));setAnchors(d.spec?.sourceAnchors?.map(a=>`${a.x},${a.y}`).join('; ')??'')}}
 useEffect(()=>{mounted.current=true;const store=new BrowserSpriteDrafts(spriteDatabaseName(location.href));repo.current=store;void Promise.all([store.get(),store.list()]).then(([d,h])=>{if(mounted.current){apply(d);setShow(d?.result?'result':'source');setHistory(h);setReady(true)}}).catch(()=>setError('SPRITE_STORAGE_FAILED'));return()=>{mounted.current=false;cancel.current?.abort();void store.close()}},[])
 useEffect(()=>{let cancelled=false;const urls:string[]=[];setUrl('');setDownload('');const selected=show==='result'&&draft?.result?draft.result.png:draft?.source;if(selected)void spritePreviewUrl(selected).then(u=>{urls.push(u);if(cancelled)URL.revokeObjectURL(u);else setUrl(u)}).catch(()=>setError('SPRITE_DECODE'));if(draft?.result)void spritePreviewUrl(draft.result.png).then(u=>{urls.push(u);if(cancelled)URL.revokeObjectURL(u);else setDownload(u)}).catch(()=>setError('SPRITE_DECODE'));return()=>{cancelled=true;urls.forEach(u=>URL.revokeObjectURL(u))}},[draft?.id,draft?.revision,show])
 async function locked(work:()=>Promise<void>) {
  if(busy||!ready)return;setBusy(true);setError('')
  try{if(!navigator.locks)throw Error('SPRITE_LOCK_UNAVAILABLE');await navigator.locks.request(spriteDatabaseName(location.href),{ifAvailable:true},async lock=>{if(!lock)throw Error('SPRITE_OTHER_TAB');await work()})}
  catch(e){if(mounted.current)setError(e instanceof Error&&e.message.startsWith('SPRITE_')?e.message:'SPRITE_PREPARATION_FAILED')}
  finally{if(mounted.current){setBusy(false);try{const d=await repo.current!.get();apply(d);setHistory(await repo.current!.list())}catch{setError('SPRITE_STORAGE_FAILED')}}}
 }
 async function importSource(load:()=>Promise<SpritePng>,name:string,nextKind:'actor'|'states') {
  await locked(async()=>{const source=await load(),checkedUrl=await spritePreviewUrl(source);URL.revokeObjectURL(checkedUrl);const old=await repo.current!.get(),next=newSpriteSource(source,name,nextKind);await repo.current!.save(next,old);setDraft(next);setKind(nextKind);setFootY(Math.floor(source.height/(nextKind==='actor'?4:1)*.85));setAnchors('');setShow('source')})
 }
 async function loadSample(which:'actor'|'states'|'ada') {
  const path=which==='ada'?adaSample:which==='actor'?actorSample:propSample
  await importSource(async()=>{const response=await fetch(path,{credentials:'omit'});if(!response.ok)throw Error('SPRITE_DOWNLOAD');const bytes=new Uint8Array(await response.arrayBuffer());const png=await inspectSpritePng(bytes),expected=which==='ada'?'43ba101c2bc5903ae6df9efef0067c1a753c44df2079285a74e7d3a3fb6144dd':which==='actor'?'dfcb31ee903944b733814a7d64d579847122247db11030317958e46debd9f9f4':'fdcbd8562b9c9d2b3669922553b2c25f1af213fbbd9e3a109daa30603e71fa0e';if(png.sha256!==expected)throw Error('SPRITE_CORRUPT');return png},which==='ada'?'platform-ada-edit-03':which==='actor'?'platform-actor-edit-02':'platform-props-edit-01',which==='states'?'states':'actor')
 }
 async function assemble(inputs:SpriteCompositionInput[],sample=false){
  const pixels=[]
  for(const i of inputs)pixels.push({raster:await decodeSpritePixels(i.source),columns:i.columns,column:i.column})
  const source=await encodeSpritePixels(composeRepairFrames(pixels)),next=newSpriteSource(source,sample?'platform-starter-repair-composite':'repair-state-composite','states')
  next.deviceStateSet='repair';next.composition={version:1,inputs:structuredClone(inputs)}
  if(sample)next.spec={columns:2,rows:1,cellWidth:320,cellHeight:640,foot:{x:160,y:544},kind:'states',backgroundMode:'pale-neutral',neutralMin:200,chromaMax:20,sourceAnchors:[{x:173,y:463},{x:173,y:468}]}
  await repo.current!.save(next,await repo.current!.get());setShow('source');setParts([undefined,undefined])
 }
 async function loadStarter(){await locked(async()=>{
  const inputs:SpriteCompositionInput[]=[]
  for(const [path,name,sha256,columns,column] of [[starterBeforeSample,'starter-edit-02','8eb32bb26a859cf20c1647bddb0896c3f8821b53f5aff1e6a71641b1adcde8da',3,1],[starterAfterSample,'starter-repair-03','2a55ef71cf18431a9eff62336a265f11d4c4af2e93fc12c77ff0749b4bcd71b2',1,0]] as const){
   const r=await fetch(path,{credentials:'omit'});if(!r.ok)throw Error('SPRITE_DOWNLOAD');const source=await inspectSpritePng(new Uint8Array(await r.arrayBuffer()));if(source.sha256!==sha256)throw Error('SPRITE_CORRUPT');inputs.push({source,sourceName:name,columns,column})
  }
  await assemble(inputs,true)
 })}
 async function choosePart(index:number,file:File){await locked(async()=>{if(file.size>8*1024*1024)throw Error('SPRITE_INVALID_PNG');const source=await inspectSpritePng(new Uint8Array(await file.arrayBuffer())),url=await spritePreviewUrl(source);URL.revokeObjectURL(url);setParts(old=>old.map((p,i)=>i===index?{source,sourceName:file.name.slice(0,100),columns:1,column:0}:p))})}
 async function process() {
  if(!draft)return
  await locked(async()=>{const rows=kind==='actor'?4:1,columns=kind==='states'&&stateSet==='repair'?2:3,w=draft.source.width/columns,h=draft.source.height/rows
   const sourceAnchors=kind==='states'?anchors.split(';').map(pair=>{const bits=pair.trim().split(',');return {x:bits.length===2&&bits[0].trim()?Number(bits[0]):NaN,y:bits.length===2&&bits[1].trim()?Number(bits[1]):NaN}}):undefined
   if(sourceAnchors&&(sourceAnchors.length!==columns||sourceAnchors.some(a=>!Number.isInteger(a.x)||!Number.isInteger(a.y))))throw Error('SPRITE_STATE_ANCHORS_REQUIRED')
   const spec:SpritePreparationSpec={columns,rows,cellWidth:w,cellHeight:h,foot:{x:Math.floor(w/2),y:footY},kind,backgroundMode:mode,neutralMin:neutral,chromaMax:20,sourceAnchors}
   cancel.current=new AbortController()
   const next=await runSpriteDraft(repo.current!,{...draft,deviceStateSet:kind==='states'&&stateSet==='repair'?'repair':undefined},spec,{decode:decodeSpritePixels,encode:encodeSpritePixels,process:prepareSpritesOffThread},cancel.current.signal,d=>{if(mounted.current)setDraft(d)})
   if(mounted.current){setDraft(next);setShow(next.result?'result':'source')}
  })
 }
 const errors:Record<string,string>={SPRITE_COMPOSITION_SIZE_MISMATCH:t('选出的两帧尺寸不同。请使用相同尺寸的素材；不会自动拉伸。','The selected frames differ in size. Use equal-sized frames; no automatic stretching.'),SPRITE_COMPOSITION_GRID:t('请检查每张图的总列数和选用列，图宽必须能被列数整除。','Check the column count and selection. Image width must divide evenly.'),SPRITE_COMPOSITION_MISMATCH:t('组合图与原始选帧不一致，请重新组合。','The composite differs from its retained sources. Assemble again.'),SPRITE_STATE_ANCHORS_REQUIRED:t('请为每个状态填写柜体落地点，使用英文分号分隔。','Enter a cabinet contact point for each state, separated by semicolons.'),SPRITE_PREPARATION_FRAME_DOES_NOT_FIT:t('移动后超出帧边界。请调整目标落地高度或柜体接地点。','The aligned frame does not fit. Adjust target height or cabinet contact points.'),SPRITE_PREPARATION_ABORTED:t('已取消。原图和已有候选保留，可重新处理。','Cancelled. Original and previous candidates are kept. You can process again.'),SPRITE_OTHER_TAB:t('另一窗口正在处理，请稍后再试。','Another tab is processing. Please retry shortly.'),SPRITE_DRAFT_REPLACED:t('草稿已在另一窗口更新，请基于最新记录继续。','Another tab updated the draft. Continue from the latest record.'),SPRITE_STORAGE_FAILED:t('草稿未能保存。请检查浏览器存储后重试。','The draft could not be saved. Check browser storage and retry.'),SPRITE_PREPARATION_EMPTY_FRAME:t('有一帧没有可保留主体，请检查图集类型和背景阈值。','A frame has no retained subject. Check the sheet type and matte threshold.'),SPRITE_PREPARATION_CLIPPED_FRAME:t('主体触及帧边界，可能被截断或仍有背景残留，请检查原图。','A subject touches its frame edge. Inspect the source for clipping or remaining matte.')}
 const issue=error||draft?.error
 const errorNotice=issue&&<p role="alert">{errors[issue]??t('这次操作未完成，请检查图片或参数后重试。','The operation did not complete. Check the image or settings and retry.')} <small>{issue}</small></p>
 return <main className="cl-creator cl-sprite"><header><a href="./creator.html">{t('返回背景制作','Back to background creation')}</a><h1>{t('准备人物与设备素材','Prepare character and equipment art')}</h1><p>{t('原图始终保留。每次处理另存一个候选，检查后再决定是否采用。','Keep the original. Each processing run saves a separate candidate for review.')}</p></header>
 <SpriteGenerationPanel ready={ready} busy={busy} locked={locked} locale={zh?'zh':'en'} producer={generationProducer} adopt={async d=>{await adoptSpriteGeneration(d,repo.current!);setShow('source')}}/>
 <section aria-label={t('原图来源','Source image')}><label htmlFor="sprite-file">{t('选择 PNG 图集（最多 8 MiB）','Choose a PNG sheet (up to 8 MiB)')}</label><input id="sprite-file" type="file" accept="image/png" disabled={!ready||busy} onChange={e=>{const file=e.target.files?.[0];e.target.value='';if(file)void importSource(async()=>{if(file.size>8*1024*1024)throw Error('SPRITE_INVALID_PNG');return inspectSpritePng(new Uint8Array(await file.arrayBuffer()))},file.name,'actor')}}/><button disabled={!ready||busy} onClick={()=>void loadSample('actor')}>{t('载入平台人物样本','Load platform character sample')}</button><button disabled={!ready||busy} onClick={()=>void loadSample('ada')}>{t('载入阿达候选（方向尚未通过）','Load Ada candidate (directions unapproved)')}</button><button disabled={!ready||busy} onClick={()=>void loadSample('states')}>{t('载入平台设备样本','Load platform equipment sample')}</button>{fixture&&<button disabled={!ready||busy} onClick={()=>void importSource(fixture,'synthetic-test-only','actor')}>Load synthetic QA source</button>}</section>
 <details><summary>{t('组合修复前后的状态图','Combine before / after repair images')}</summary><p>{t('选择独立原图或旧组合中保留的原图，也可上传PNG。原先选用的列会保留；组合时保存两张原图，不缩放、不补画。','Choose standalone or retained originals, or upload PNGs. Previous column selections are preserved; both originals are retained without resizing or repainting.')}</p>
 {parts.map((part,i)=><fieldset key={i}><legend>{i===0?t('修复前','Before repair'):t('修复后','After repair')}</legend><label htmlFor={`sprite-part-saved-${i}`}>{t('从已保存素材选择','Choose saved art')}</label><select id={`sprite-part-saved-${i}`} value="" disabled={!ready||busy} onChange={e=>{const saved=savedSources.find(s=>s.key===e.target.value);if(saved)void locked(async()=>{const source=await resolveSavedSpriteSource(repo.current!,saved);setParts(old=>old.map((p,j)=>j===i?source:p))})}}><option value="">{t('选择原图','Select source')}</option>{savedSources.map(s=><option key={s.key} value={s.key}>{s.sourceName}{s.slot!==null?' · '+(s.slot===0?t('保留的修复前原图','Retained before-repair source'):t('保留的修复后原图','Retained after-repair source')):''} · {t('列','Column')} {s.column+1}/{s.columns} · {new Date(s.createdAt).toLocaleTimeString()}</option>)}</select><label htmlFor={`sprite-part-${i}`}>{t('选择PNG','Choose PNG')}</label><input id={`sprite-part-${i}`} type="file" accept="image/png" disabled={!ready||busy} onChange={e=>{const f=e.target.files?.[0];e.target.value='';if(f)void choosePart(i,f)}}/>{part&&<><p>{part.sourceName} · {part.source.width} × {part.source.height}</p><label htmlFor={`sprite-part-columns-${i}`}>{t('图集总列数','Total columns')}</label><input id={`sprite-part-columns-${i}`} type="number" min={1} max={12} disabled={busy} value={part.columns} onChange={e=>{const n=e.target.valueAsNumber;setParts(old=>old.map((p,j)=>j===i&&p?{...p,columns:n}:p))}}/><label htmlFor={`sprite-part-column-${i}`}>{t('使用第几列（从1开始）','Selected column (starting at 1)')}</label><input id={`sprite-part-column-${i}`} type="number" min={1} max={part.columns} disabled={busy} value={part.column+1} onChange={e=>{const n=e.target.valueAsNumber-1;setParts(old=>old.map((p,j)=>j===i&&p?{...p,column:n}:p))}}/></>}</fieldset>)}
 <button disabled={!ready||busy||parts.some(p=>!p)} onClick={()=>void locked(()=>assemble(parts as SpriteCompositionInput[]))}>{t('组合并保存原图','Assemble and retain originals')}</button><button disabled={!ready||busy} onClick={()=>void loadStarter()}>{t('载入启动机状态样本','Load starter state samples')}</button><p>{t('样本是已生成的素材，此操作不发起生图。组合保存前的文件选择尚未持久保存。','Samples are existing generated images; this does not start generation. File selections are not saved until assembly.')}</p></details>
 {draft&&<><section aria-label={t('处理参数','Preparation settings')}><p>{draft.sourceName} · {draft.source.width} × {draft.source.height}</p><label htmlFor="sprite-kind">{t('图集类型','Sheet type')}</label><select id="sprite-kind" value={kind==='states'&&stateSet==='repair'?'repair':kind} disabled={busy||Boolean(draft.composition)} onChange={e=>{const k=e.target.value==='repair'?'states':e.target.value as typeof kind;setKind(k);setStateSet(e.target.value==='repair'?'repair':'cabinet');setFootY(Math.floor(draft.source.height/(k==='actor'?4:1)*.85))}}><option value="actor">{t('人物 · 3 列 × 4 个方向','Character · 3 columns × 4 directions')}</option><option value="states">{t('设备 · 3 列 × 1 行状态','Equipment · 3 columns × 1 row of states')}</option><option value="repair">{t('设备 · 修复前 / 修复后两状态','Equipment · Before / after repair')}</option></select>
 <label htmlFor="sprite-mode">{t('背景处理','Background handling')}</label><select id="sprite-mode" value={mode} disabled={busy} onChange={e=>setMode(e.target.value as typeof mode)}><option value="pale-neutral">{t('去除浅色背景','Remove pale neutral matte')}</option><option value="alpha">{t('保持已有透明，只对齐','Keep existing alpha; align only')}</option></select>
 {draft.generation?.recipe.startsWith('starter-')&&!draft.composition&&<p>{t('这是一张设备单帧原图，请先在上方组合修复前后的两张图。','This is a single equipment frame. Combine before / after sources above first.')}</p>}
 {mode==='pale-neutral'&&<><label htmlFor="sprite-neutral">{t('背景最低亮度（180–255）','Minimum matte brightness (180–255)')}</label><input id="sprite-neutral" type="number" min={180} max={255} value={neutral} disabled={busy} onChange={e=>setNeutral(e.target.valueAsNumber)}/></>}
 <label htmlFor="sprite-foot">{t('目标落地高度（帧内像素）','Target contact height (pixels within frame)')}</label><input id="sprite-foot" type="number" min={1} value={footY} disabled={busy} onChange={e=>setFootY(e.target.valueAsNumber)}/>
 {kind==='states'&&<><label htmlFor="sprite-anchors">{t(`${stateSet==='repair'?'两个':'三个'}柜体接地点（各帧 x,y；用英文分号分隔）`,`${stateSet==='repair'?'Two':'Three'} cabinet contact points (local x,y; separated by semicolons)`)}</label><input id="sprite-anchors" value={anchors} disabled={busy} placeholder="160,440; 160,440; 160,440" onChange={e=>setAnchors(e.target.value)}/><p>{t('使用柜体的落地点，不使用打开后的门角。','Use the cabinet contact point, not the open door corner.')}</p></>}
 <button className="cl-primary" disabled={busy||!ready||Boolean(draft.generation?.recipe.startsWith('starter-')&&!draft.composition)} onClick={()=>void process()}>{busy?t('正在处理…','Processing…'):t('处理并保存新候选','Process and save new candidate')}</button>{busy&&<button onClick={()=>cancel.current?.abort()}>{t('取消处理','Cancel processing')}</button>}
 </section><p role="status">{draft.state==='candidate'?t('候选已保存。','Candidate saved.'):draft.state==='processing'&&!busy?t('上次处理未完成。原图已保留，可以重新处理。','The previous run did not finish. The source is saved; you can process again.'):t('先检查原图与参数。','Inspect the source and settings first.')}</p>
 {errorNotice}<section aria-label={t('素材预览','Art preview')}><label htmlFor="sprite-view">{t('查看版本','View version')}</label><select id="sprite-view" value={show} onChange={e=>setShow(e.target.value as typeof show)}><option value="source">{t('原图','Original')}</option><option value="result" disabled={!draft.result}>{t('处理结果','Processed candidate')}</option></select><label htmlFor="sprite-bg">{t('检查底色','Review background')}</label><select id="sprite-bg" value={background} onChange={e=>setBackground(e.target.value as typeof background)}><option value="dark">{t('深色','Dark')}</option><option value="light">{t('浅色','Light')}</option></select>{url&&<div className={`cl-sprite__preview cl-sprite__preview--${background}`}><img src={url} alt={show==='result'?t('处理后的候选图集','Processed candidate sheet'):t('未经处理的原图集','Original unprocessed sheet')} draggable={false}/></div>}{draft.result&&draft.spec?.kind==='actor'&&<a className="cl-creator__action" href={`./creator.html?scene_preview=north-cape&actor_draft=${encodeURIComponent(draft.id)}`}>{t('在地图里试走这个人物','Try this actor in the map')}</a>}{draft.result&&draft.spec?.kind==='states'&&<a className="cl-creator__action" href={`./creator.html?scene_preview=north-cape&device_draft=${encodeURIComponent(draft.id)}`}>{t('在地图里检查这个设备','Inspect this device in the map')}</a>}{download&&<a download={`sprite-${draft.id}.png`} href={download}>{t('导出候选 PNG','Export candidate PNG')}</a>}</section></>}

 {!draft&&errorNotice}
 {!!history.length&&<section><label htmlFor="sprite-history">{t('已保存记录','Saved records')}</label><select id="sprite-history" value={draft?.id??''} disabled={busy} onChange={e=>{const id=e.target.value;void locked(async()=>{const selected=await repo.current!.get(id);if(!selected)throw Error('SPRITE_CORRUPT');const current=await repo.current!.get();await repo.current!.save(selected,current);setShow(selected.result?'result':'source')})}}>{history.map(d=><option key={d.id} value={d.id}>{d.sourceName} · {d.result?t('候选','candidate'):t('原图/未完成','source/unfinished')} · {new Date(d.createdAt).toLocaleTimeString()}</option>)}</select></section>}
 {draft&&<details><summary>{t('素材记录','Art record')}</summary><dl><dt>{t('记录 ID','Record ID')}</dt><dd>{draft.id}</dd><dt>{t('原图摘要','Source SHA-256')}</dt><dd>{draft.source.sha256}</dd>{draft.generation&&<><dt>{t('平台生成来源','Platform generation source')}</dt><dd>{draft.generation.recipe} · {draft.generation.requestId} · {draft.generation.taskId}</dd></>}{draft.composition?.inputs.map((i,n)=><React.Fragment key={n}><dt>{t('保留的原图','Retained original')} {n+1} · {i.sourceName} · {t('选用列','Column')} {i.column+1}/{i.columns}</dt><dd>{i.source.sha256}</dd>{i.generation&&<><dt>{t('平台生成来源','Platform generation source')}</dt><dd>{i.generation.recipe} · {i.generation.requestId} · {i.generation.taskId}</dd></>}</React.Fragment>)}{draft.result&&<><dt>{t('候选摘要','Candidate SHA-256')}</dt><dd>{draft.result.png.sha256}</dd><dt>{t('处理版本','Algorithm')}</dt><dd>{draft.result.algorithm}</dd></>}</dl></details>}
 {ready&&repo.current&&<SpriteCloudPanel repo={repo.current} draft={draft} busy={busy} setBusy={setBusy} locale={zh?'zh':'en'} onRestore={async d=>{apply(d);setShow('result');setHistory(await repo.current!.list())}}/>}
 <footer><p>{t('保存在当前浏览器。透明边缘、四方向和动作仍需实际检查；完成设备检查后可另行发布；已有旅程保持原样。','Saved in this browser. Alpha edges, directions and animation still need review. Reviewed devices may be published separately; existing journeys keep their assets.')}</p></footer></main>
}
