import type { StoryCartridge, StorySave, Locale, DomainActionRule } from './vendor/story/types'
import { createInitialSave } from './vendor/story/engine/reducer'
import { resolveDomainAction, applyDomainResolution } from './vendor/story/engine/domainRules'

import {admitAttendant,attendantDefinition,attendantIntro,attendantReply} from './attendant'
import {admitDispatcher,dispatcherDefinition,dispatcherIntro,dispatcherReply} from './contacts'

export type { Locale, StorySave }
export const tr = (locale: Locale, zh: string, en: string) => locale === 'zh' ? zh : en
export const labels: Record<string, [string, string]> = {
  cabinet: ['检修柜', 'Service cabinet'], panel: ['配电箱', 'Circuit panel'],
  lin: ['林', 'Lin'], exit: ['车厢出口', 'Carriage exit'], fuse: ['备用保险丝', 'Spare fuse'],
}
export function cartridge(locale: Locale, current?:StorySave): StoryCartridge {
 const f=current?.facts??{},radioPriority=Boolean(f.power_radio)
 const t = (zh:string,en:string) => tr(locale,zh,en)
 const rule = (id:string, requirements:DomainActionRule['requirements'],effects:DomainActionRule['effects'],zh:string,en:string):DomainActionRule => ({id,intent:id,match:[id],matchMode:'exact',requirements,effects,successText:t(zh,en),successChoices:[],dangerPolicy:'suppress'})
 const fact = (id:string,equals:boolean,zh:string,en:string):DomainActionRule['requirements'][number] => ({type:'fact',id,equals,reason:t(zh,en)})
 return {
  schemaVersion:1,id:'carriage-07',locale,coverImage:'./art/direction-study.png',
  copy:{title:'Carriage 07',subtitle:t('雨夜检修','A repair in the rain'),promise:t('让这节车厢重新亮起来。','Bring this carriage back to light.'),enter:t('进入车厢','Enter carriage'),continue:t('继续','Continue'),customAction:t('说说你的想法','Try your own idea'),itemImagingTitle:'',itemImagingBody:''},
  theme:{outer:'#101d24',surface:'#29404b',paper:'#ede7da',ink:'#26343b',muted:'#69777d',accent:'#efbd73',danger:'#cb806c',gold:'#efbd73',material:'wayfarer'},
  audioTheme:{material:'wayfarer',bpm:62,rootHz:110,scale:[0,5,7],levels:{music:0,ambient:0,sfx:0.04,master:0.5},tension:[]},
  statDefinitions:[
   {id:'circuit',label:t('电路','Circuit'),min:0,max:100,initial:20,display:'bar',maxDelta:80,description:t('更换保险丝后恢复；步行不消耗。','Restore by replacing the fuse; walking costs nothing.')},
   {id:'light',label:t('照明','Light'),min:0,max:100,initial:10,display:'bar',maxDelta:90,description:t('修复后恢复；集中供电给电台时客厢保留应急照明。','Restored after repair; radio priority leaves emergency light in the carriage.')},
   {id:'trust',label:t('信任','Trust'),min:0,max:3,initial:0,display:'number',maxDelta:1,description:t('首次与修理工交谈建立联系。','Make a connection by speaking with the mechanic.')},
  ],
  drawerLabels:{party:t('同行者','Companions'),map:t('车厢','Carriage'),inventory:t('随身物品','Inventory'),log:t('旅途记录','Journal')},
  opening:{location:t('07 号车厢','Carriage 07'),time:'23:47',objective:t('先看看检修柜里有什么。','Find out what is in the service cabinet.'),imagePrompt:'',blocks:[{id:'opening',kind:'narration',text:t('列车停在雨里。过道的灯只剩微光，左侧检修柜的把手没有上锁。','The train waits in the rain. A dim light hangs over the aisle. The service cabinet on your left is unlocked.')}],choices:[]},
  initialFacts:{attendant_introduced:false,cabinet_open:false,fuse_taken:false,repaired:false,introduced:false,finished:false,supply_open:false,battery_taken:false,record_read:false,battery_installed:false,rescue_sent:false,power_chosen:false,power_radio:false,signal_acknowledged:false,beacon_set:false,dispatcher_introduced:false,dispatcher_briefed:false},
  characters:[{id:'lin',name:t('林','Lin'),role:t('修理工','Mechanic'),vitality:100,stress:10,skills:[],hiddenUntilIntroduced:true,detail:t('灰色工作服，灰白短发。','Grey work jacket, short grey hair.')},dispatcherDefinition(locale),attendantDefinition(locale)],initialPartyMemberIds:[],
  initialMap:[{id:'carriage',label:t('07 号客厢','Carriage 07'),current:true,visited:true},{id:'baggage',label:t('06 号行李检修车','Baggage & service car'),current:false,visited:false},{id:'cab',label:t('驾驶室','Driving cab'),current:false,visited:false}],initialInventory:[],demoTurns:[],
  domainRules:{rules:[
   rule('meet-attendant',[fact('attendant_introduced',false,'你们已经认识了。','You have already met.')],[{type:'fact',id:'attendant_introduced',value:true}],attendantIntro('zh'),attendantIntro('en')),
   rule('talk-attendant',[fact('attendant_introduced',true,'先走近听她介绍自己。','Approach and hear her introduction first.')],[],attendantReply({facts:f,locale:'zh'}),attendantReply({facts:f,locale:'en'})),
   rule('open-cabinet',[fact('cabinet_open',false,'柜门已经打开了。','The cabinet is already open.')],[{type:'fact',id:'cabinet_open',value:true},{type:'objective',value:t('取出保险丝，再找修理工问问。','Take the fuse, then speak with the mechanic.')}],'你拉开柜门。一枚备用保险丝放在凹槽里，纸条写着“先检查配电箱”。','You pull the cabinet open. A spare fuse rests in its slot. A note reads: “Check the circuit panel first.”'),
   rule('take-fuse',[fact('cabinet_open',true,'先打开检修柜。','Open the service cabinet first.'),fact('fuse_taken',false,'备用保险丝已经取走了。','The spare fuse has already been taken.')],[{type:'fact',id:'fuse_taken',value:true},{type:'inventory',action:'add',itemId:'fuse',count:1,item:{id:'fuse',label:t('备用保险丝','Spare fuse'),count:1,rarity:'common',detail:t('从检修柜取出的陶瓷保险丝。','A ceramic fuse from the service cabinet.'),effect:t('替换配电箱里的损坏部件。','Replaces the damaged fuse in the circuit panel.')}}],'你把保险丝收进随身袋，柜里的凹槽空了。','You place the fuse in your bag. Its slot in the cabinet is now empty.'),
   rule('meet-lin',[fact('introduced',false,'你们已经认识了。可以继续和林交谈。','You have already met. You can keep talking with Lin.')],[{type:'fact',id:'introduced',value:true},{type:'party',change:'add',characterId:'lin'},{type:'stat',id:'trust',delta:1},{type:'objective',value:t('把备用保险丝装进配电箱。','Fit the spare fuse into the circuit panel.')}],'穿灰色工作服的人从配电箱旁抬起头。“叫我林就好。我留在这儿帮你看着，找到保险丝就装进这个槽。”他看着箱里的槽口，等你继续操作。','The person in a grey work jacket looks up from the panel. “Call me Lin. I’ll stay here with you. If you find a spare fuse, put it in this slot.” He watches the slot, ready to help.'),
   rule('repair',[fact('introduced',true,'先问问配电箱旁的修理工，确认该换哪个部件。','Ask the mechanic by the panel which part needs replacing.'),fact('repaired',false,'电路已经修好了，不需要再换保险丝。','The circuit is already repaired; it needs no more fuses.'),{type:'item',id:'fuse',minCount:1,reason:t('需要检修柜里的备用保险丝。','You need the spare fuse from the cabinet.')}],[{type:'inventory',action:'remove',itemId:'fuse',count:1},{type:'fact',id:'repaired',value:true},{type:'stat',id:'circuit',delta:80},{type:'stat',id:'light',delta:90},{type:'objective',value:t('出口亮了。走到车厢前端看看。','The exit is lit. Walk to the front of the carriage.')}],'你装好保险丝，合上配电箱。灯一盏接一盏亮起来，出口的锁舌缩回。林轻轻敲了敲箱盖：“好了。”','You fit the fuse and close the panel. The lights come on one by one; the exit latch retracts. Lin taps the casing. “That’s it.”'),
   rule('leave',[fact('repaired',true,'出口还锁着。先修复配电箱。','The exit is locked. Repair the circuit panel first.'),fact('finished',false,'这一段旅程已经完成。你仍可查看记录。','This part of the journey is complete. You can still read your journal.')],[{type:'fact',id:'finished',value:true},{type:'map',nodeId:'baggage'},{type:'objective',value:t('查看行李车的器材柜与调度记录。','Check the supply cabinet and dispatch record.')}],'你穿过亮起的连接门。金属地板响了一声，捆扎货箱贴着两边墙壁，前方挂着一块调度记录板。林留在客厢照看电路。','You pass through the lit connecting door. Strapped cargo lines the walls; a dispatch clipboard hangs ahead. Lin stays in the carriage to watch the circuit.'),
   rule('go-baggage',[fact('repaired',true,'先修复车厢电路。','Repair the carriage circuit first.')],[{type:'map',nodeId:'baggage'}],'你沿连接通道回到行李检修车，货箱仍停在原位。','You return through the passage to the baggage car. The cargo is where you left it.'),
   rule('back-carriage',[],[{type:'map',nodeId:'carriage'}],radioPriority?'你回到 07 号客厢。顶灯暗下，只留过道的应急光；林守着配电箱，为电台留出功率。':'你回到 07 号客厢。灯光稳定，林还守着配电箱。',radioPriority?'You return to Carriage 07. The aisle has only emergency light; Lin keeps the circuit clear for the radio.':'You return to Carriage 07. The lights are steady; Lin still watches the panel.'),
   rule('enter-cab',[],[{type:'map',nodeId:'cab'}],'车头的雨水沿窗滑下。驾驶室里没有人，前方调度电台的听筒挂在座上。','Rain trails down the front windows. The cab is empty; a handset rests on the dispatch radio.'),
   rule('back-baggage',[],[{type:'map',nodeId:'baggage'}],'你退回行李车，身后电台的状态没有改变。','You return to the baggage car. The radio remains as you left it.'),
   rule('open-supply',[fact('supply_open',false,'器材柜已经打开。','The supply cabinet is open.')],[{type:'fact',id:'supply_open',value:true}],'你打开器材柜。一块带提手的方形电池放在中层。','You open the supply cabinet. A rectangular battery with a handle sits on the middle shelf.'),
   rule('take-battery',[fact('supply_open',true,'先打开器材柜。','Open the supply cabinet first.'),fact('battery_taken',false,'电池已经取走。','The battery has already been taken.')],[{type:'fact',id:'battery_taken',value:true},{type:'inventory',action:'add',itemId:'battery',count:1,item:{id:'battery',label:t('电台电池','Radio battery'),count:1,rarity:'common',detail:t('橄榄色方形外壳，黄铜接线柱与皮提手。','An olive rectangular case, brass terminals and a leather handle.'),effect:t('为驾驶室调度电台供电。','Powers the dispatch radio in the cab.')}}],'你提起电池收进袋中，器材柜的中层空了。','You lift the battery into your bag. The middle shelf is empty.'),
   rule('read-record',[fact('record_read',false,'记录仍写着：救援用 3 频道，1 频道为无人值守的调车频道。','The record still reads: emergency channel 3; yard channel 1 is unattended.')],[{type:'fact',id:'record_read',value:true},{type:'objective',value:t('给驾驶室电台装电池，用 3 频道求援。','Power the cab radio and call for help on channel 3.')}],'记录上画着车头电台的位置，下面写着：“夜间救援：3 频道。1 频道仅供调车，本站夜间无人值守。”你记下了频道。','The record marks the cab radio: “Night emergency: channel 3. Channel 1 is for yard movements, unattended at this station overnight.” You note the channel.'),
   rule('install-battery',[fact('battery_installed',false,'电池已经装好。','The battery is already installed.'),{type:'item',id:'battery',minCount:1,reason:t('电台缺少电池。行李车的器材柜里也许有备用。','The radio needs a battery. Check the baggage car supply cabinet.')}],[{type:'inventory',action:'remove',itemId:'battery',count:1},{type:'fact',id:'battery_installed',value:true}],'你把方形电池推入电台槽内。琥珀色电源灯亮起，听筒里传出轻微沙沙声。','You slide the rectangular battery into the radio. An amber power lamp lights; a soft hiss comes from the handset.'),
   rule('route-radio',[fact('battery_installed',true,'先装入电池。','Install the battery first.'),fact('signal_acknowledged',false,'呼叫已确认，供电路线已锁定。','The call is acknowledged; the power route is locked.'),fact('power_radio',false,'已经集中供电给电台。','The radio already has priority.')],[{type:'fact',id:'power_chosen',value:true},{type:'fact',id:'power_radio',value:true},{type:'stat',id:'light',delta:35-(current?.stats.light??100)}],'你把供电拨向电台增幅。客厢顶灯降为应急光，电台的杂音变得清晰；它可以持续引导接应。发送前仍可改回照明优先。','You route power to the radio amplifier. The carriage falls to emergency light; the clearer radio can guide rescuers continuously. You can change back before sending.'),
   rule('route-lights',[fact('battery_installed',true,'先装入电池。','Install the battery first.'),fact('signal_acknowledged',false,'呼叫已确认，供电路线已锁定。','The call is acknowledged; the power route is locked.'),f.power_chosen?fact('power_radio',true,'已经保持客厢照明。','The carriage lights already have priority.'):fact('power_chosen',false,'已经选好供电路线。','A power route is already selected.')],[{type:'fact',id:'power_chosen',value:true},{type:'fact',id:'power_radio',value:false},{type:'stat',id:'light',delta:100-(current?.stats.light??100)}],'你把功率留给客厢照明。电台只能发出短报文；收到回执后，需要返回客厢配电箱设置引导灯，让接应找到列车。发送前仍可改选。','You keep the carriage lights on. The radio can send a short message only. After acknowledgment, return to the carriage panel to set a guide light so rescuers can find the train. You can change before sending.'),
   rule('set-beacon',[fact('signal_acknowledged',true,'先在 3 频道收到回执。','Get an acknowledgment on channel 3 first.'),fact('power_chosen',true,'先在驾驶室选择供电路线。','Choose a power route in the cab first.'),fact('power_radio',false,'电台正在持续引导，无需再设置灯光信号。','The radio is guiding rescuers continuously; no light signal is needed.'),fact('beacon_set',false,'引导灯已经开启。','The guide light is already set.'),fact('rescue_sent',false,'这一程求援已经完成。','This rescue is already complete.')],[{type:'fact',id:'beacon_set',value:true},{type:'fact',id:'rescue_sent',value:true}],'你将配电箱上的照明开关拨到引导档。连接门的暖灯缓缓明灭，客厢里仍亮着。林望向窗外：“有灯回应了，他们看见我们了。”你保住了车厢的光，也为接应点出了位置。','You set the panel to guide mode. The connecting-door lamp pulses gently while the carriage stays bright. Lin looks outside. “An answering light. They can see us.” You kept the carriage lit and marked the train for rescue.'),
   rule('meet-dispatch',[fact('signal_acknowledged',true,'先在 3 频道建立联络。','Establish contact on channel 3 first.'),fact('battery_installed',true,'先给电台装入电池。','Install the radio battery first.'),fact('dispatcher_introduced',false,'你已经认识这位调度员。','You have already met the dispatcher.')],[{type:'fact',id:'dispatcher_introduced',value:true}],dispatcherIntro('zh')+'她接着确认：此前的回执仍然有效，你可以询问接应进展。',dispatcherIntro('en')+' She confirms the earlier acknowledgment remains valid; you can ask about the rescue.'),
   rule('ask-dispatch',[fact('dispatcher_introduced',true,'先接听调度，听听对方是谁。','Answer the dispatcher and hear her introduction first.'),fact('signal_acknowledged',true,'先建立电台联络。','Establish radio contact first.'),fact('battery_installed',true,'电台需要电池。','The radio needs a battery.')],[],dispatcherReply(current??{facts:{},locale},'zh'),dispatcherReply(current??{facts:{},locale},'en')),
   rule('brief-dispatch',[fact('dispatcher_introduced',true,'先接听调度。','Answer the dispatcher first.'),fact('signal_acknowledged',true,'先建立电台联络。','Establish radio contact first.'),fact('battery_installed',true,'电台需要电池。','The radio needs a battery.'),fact('introduced',true,'先认识客厢里的修理工。','Meet the carriage mechanic first.'),fact('dispatcher_briefed',false,'车内情况已经告知，她会记住。','She already has your report and will remember it.')],[{type:'fact',id:'dispatcher_briefed',value:true}],'你告诉许岚，林留在客厢照看电路。她复述了一遍：“有人在看电路，收到。我会把这个情况告诉接应。”','You tell Xu Lan that Lin is watching the carriage circuit. She repeats it back: “Someone is watching the circuit. Understood. I will pass that on to the rescue team.”'),
   rule('call-yard',[fact('signal_acknowledged',false,'已经收到回执，请保持当前联络。','Acknowledgment received. Keep the current connection.'),fact('battery_installed',true,'先给电台装上电池。','Install the radio battery first.')],[],'你转到 1 频道呼叫。听筒只有静电声，没有回应；电池还在，可以重新选择频道。','You call on channel 1. Only static answers. The battery stays installed; you can choose another channel.'),
   rule('send-signal',[fact('power_chosen',true,'先选择保持客厢照明，或集中供电给电台。','Choose carriage lighting or radio priority first.'),fact('signal_acknowledged',false,'呼叫已确认。照明路线请返回客厢设置引导灯。','The call is acknowledged. On the lighting route, return to set the guide light.'),fact('battery_installed',true,'先给电台装上电池。','Install the radio battery first.'),fact('record_read',true,'先看行李车的调度记录，确认夜间有人值守的频道。','Read the baggage car dispatch record to confirm the attended night channel.'),fact('rescue_sent',false,'求援已经收到。你可以继续查看这列车。','Your call has been received. You can keep exploring the train.')],[{type:'fact',id:'signal_acknowledged',value:true},{type:'fact',id:'rescue_sent',value:radioPriority},{type:'fact',id:'dispatcher_introduced',value:true}],(f.dispatcher_introduced?'':dispatcherIntro('zh'))+(radioPriority?'你在 3 频道报出列车位置。两盏连接灯亮起：“收到，保持联络，我们沿信号靠近。”客厢留着应急光，稳定的电台为列车带来了接应。':'3 频道收到短报文：“收到。请把客厢连接门的灯设为引导信号，我们循光找车。”电台回到低功率待机。回执已到，但还需要你返回配电箱设置引导灯。'),(f.dispatcher_introduced?'':dispatcherIntro('en'))+(radioPriority?'You report the location on channel 3. Two connection lamps light. “Received. Stay on the line; we are following your signal.” The carriage keeps its emergency light while the radio guides help.':'Channel 3 acknowledges the short message: “Received. Set the carriage door light as a guide; we will follow it.” The radio returns to low-power standby. Return to the circuit panel to finish guiding the rescue.')),
  ]},
 }
}
export function initialStory(locale:Locale):StorySave { const s=createInitialSave(cartridge(locale));s.blocks=s.blocks.filter(b=>b.kind!=='image'&&b.kind!=='choices');s.entered=true;return s }
export function journeyObjective(s:StorySave){const f=s.facts;if(f.rescue_sent)return tr(s.locale,f.beacon_set?'引导灯已亮，接应循光靠近。':f.power_radio?'电台持续引导，接应沿信号靠近。':'求援已收到。灯留着，等待接应。',f.beacon_set?'Guide light set. Help is following the light.':f.power_radio?'The radio is guiding help to the train.':'Help is on the way. Leave the light on.');if(f.signal_acknowledged)return tr(s.locale,'回执已到。返回客厢配电箱设置引导灯。','Acknowledged. Return to the carriage panel and set the guide light.');if(!f.record_read)return tr(s.locale,'沿连接门查看行李车的器材柜与调度记录。','Follow the connecting doors to the supply cabinet and dispatch record.');if(!f.battery_installed)return tr(s.locale,'给驾驶室电台装电池。','Install the battery in the cab radio.');if(!f.power_chosen)return tr(s.locale,'选择供电路线，再用 3 频道呼叫。','Choose a power route, then call on channel 3.');return tr(s.locale,'供电已选定。用 3 频道发出求援。','Power is routed. Call for help on channel 3.')}
// Capability migration is independent of map version and never invents a past choice.
export function upgradePowerFacts(s:StorySave){let changed=false;const defaults={power_chosen:false,power_radio:false,signal_acknowledged:Boolean(s.facts.rescue_sent),beacon_set:false};for(const [key,value] of Object.entries(defaults))if(s.facts[key]===undefined){s.facts[key]=value;changed=true}return changed}
export function runRule(base:StorySave,action:string) {
 const c=cartridge(base.locale,base), result=resolveDomainAction(base,c,action)
 if(!result) throw new Error('UNREGISTERED_ACTION')
 if(result.status==='rejected') return {save:base,accepted:false,text:result.reasons.join(' ')}
 const save=structuredClone(base);save.scene++
 const blocks=applyDomainResolution(save,c,result);save.blocks.push(...blocks);if(!base.facts.attendant_introduced&&save.facts.attendant_introduced)admitAttendant(base,save,c,result.successText);if(!base.facts.dispatcher_introduced&&save.facts.dispatcher_introduced)admitDispatcher(base,save,c,result.successText);if(save.facts.finished)save.objective=journeyObjective(save)
 return {save,accepted:true,text:result.successText}
}

export function linResponse(s:StorySave,locale=s.locale){const f=s.facts;return tr(locale,f.beacon_set?'林望着门边缓缓明灭的暖光：“他们看见我们了。灯还在，慢慢等就好。”':f.power_radio?'林站在应急光里：“顶灯暗了，但电台能一直领着接应走。过道我看着。”':f.signal_acknowledged&&!f.rescue_sent?'林指向配电箱：“短报文已经发出。把这里拨到引导档，门边的灯会带他们找到车。”':f.power_chosen?'林看看亮着的灯：“把光留给客厢也好。等回执到了，我陪你把引导灯打开。”':'林守着配电箱：“灯留着，接应会找到这里。”',f.beacon_set?'Lin watches the warm guide light. “They can see us. The lights are still on; we can wait.”':f.power_radio?'Lin stands in emergency light. “The ceiling lights are down, but the radio can guide help all the way. I will watch the aisle.”':f.signal_acknowledged&&!f.rescue_sent?'Lin points to the panel. “The short message is through. Set guide mode here; the door light will show them the train.”':f.power_chosen?'Lin glances at the lights. “We can keep the carriage bright. After the acknowledgment, we will switch on the guide light.”':'Lin watches the panel. “Leave the light on. Help will find us.”')}
